### PR TITLE
Fix discogs reauth bug by avoiding empty queries

### LINKED ISSUE #1345: Discogs crashes beets 1.3.11
```
beets version 1.3.11
plugins: fromfilename, duplicates, lastgenre, mbsync, lastimport, fetchart, ftintitle, discogs
Python 2.7.9
OSX 10.10
```

```
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.11', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/site-packages/beets/ui/__init__.py", line 953, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/site-packages/beets/ui/__init__.py", line 943, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/site-packages/beets/ui/commands.py", line 876, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/site-packages/beets/ui/commands.py", line 853, in import_files
    session.run()
  File "/usr/local/lib/python2.7/site-packages/beets/importer.py", line 316, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python2.7/site-packages/beets/util/pipeline.py", line 301, in run
    out = self.coro.send(msg)
  File "/usr/local/lib/python2.7/site-packages/beets/util/pipeline.py", line 183, in coro
    func(*(args + (task,)))
  File "/usr/local/lib/python2.7/site-packages/beets/importer.py", line 1236, in lookup_candidates
    task.lookup_candidates()
  File "/usr/local/lib/python2.7/site-packages/beets/importer.py", line 567, in lookup_candidates
    autotag.tag_album(self.items)
  File "/usr/local/lib/python2.7/site-packages/beets/autotag/match.py", line 433, in tag_album
    search_album, va_likely)
  File "/usr/local/lib/python2.7/site-packages/beets/autotag/hooks.py", line 565, in album_candidates
    out.extend(plugins.candidates(items, artist, album, va_likely))
  File "/usr/local/lib/python2.7/site-packages/beets/plugins.py", line 344, in candidates
    out.extend(plugin.candidates(items, artist, album, va_likely))
  File "/usr/local/lib/python2.7/site-packages/beetsplug/discogs.py", line 141, in candidates
    self.reset_auth()
  File "/usr/local/lib/python2.7/site-packages/beetsplug/discogs.py", line 86, in reset_auth
    self.setup()
```

Config:

```
directory: /Volumes/Music/beets
library: /Users/sammcj/Music/beetslibrary.blb
import:
    move: yes
    write: yes
    resume: yes
    log: beetslog.txt
plugins:
    fromfilename
    ftintitle
    duplicates
    fetchart
    lastgenre
    mbsync
    lastimport
    discogs
match:
    strong_rec_thresh: 0.30
fetchart:
    auto: yes
lastfm:
    user: sammcj2000
    api_key: <removed>
```

### PR DESCRIPTION
**Pull request by scztt**
This fixes #1345 - or, at least, the secondary issue where the discogs plugin repeatedly tried to authenticate. This is sort of a bug in the Discogs API, since 401 is probably not an appropriate error code for a malformed query.... But this fix sidesteps getting that error for empty queries.

### CODE REVIEW

**Comment by brunal** [comment]
Hi,
I'm not sure this fixes #1345: here I succeed with searching for `""`.
```
>>> client.search("", type="release").page(1)
[<Release 755718 u'Casper Hauser* - Riding'>, <Release 755732 u'Ome Henk - De Beste Liedjes Van Ome Henk'>, <Release 755826 u'Angtoria - God Has A Plan For Us All'>, <Release 755934 u"Tony Steward - Isn't She Lovely / Come Closer">, ...
```

**Comment by brunal** [comment]
Anyway avoiding empty queries is a good idea. Could you take care of the style points raised on the commit?

**Comment by scztt** [comment]
By if/else outside try/catch, you mean structure like:

    if query:
        try: ...
        catch: ...
    else:
        ...

?

I'll fix the style - wrote and submitted ssh'd in to a remote machine. :)

**Comment by brunal** [comment]
Exactly. Since only the "if" expression can raise the exception it should be the only one in the try/except.

**Comment by sampsyo** [comment]
Looking good! And thanks in advance or resolving the style warnings, @scztt. And to @brunal as always for diligent code reviews.

**Comment by brunal** [comment]
Hi @scztt,
Do you plan on fixing the aforementioned style points, so we can merge this?
Thanks

**Comment by arcresu** [comment]
Thanks for your contribution to beets! This PR has picked up conflicts since the last discussion, and from what I can see in the linked issues it seems that the changes here are anyway no longer necessary. If there are still problems with the Discogs API it will be cleaner to start from a new PR anyway at this point, but feel free to reopen if you disagree.

**Pull request closed without merging**
