### PR TITLE
discogs: Skip Discogs query on insufficiently tagged files

### PR DESCRIPTION
**Pull request by JOJ0**
## Description

Fixes #4222.

- When files are missing both, album and artist tags, the Discogs metadata
  plugin sends empty information to the Discogs API which returns arbitrary
  query results. The resulting "Candidates" are not affiliated with the release being searched for at all and thus are more confusing than helpful to the beets user.
- This patch catches this case and states it in beets import verbose output.
- An example output of such arbitrary results with untagged files can be found here: https://github.com/beetbox/beets/discussions/4222#discussion-3769077

## To Do

- [x] Documentation. (If you've add a new command-line flag, for example, find the appropriate page under `docs/` to describe it.) -> Should I add a short note to the Discogs plugin chapter?
- [x] Changelog. (Add an entry to `docs/changelog.rst` near the top of the document.) -> Will do that after this PR is approved. Currently I think the "Bug fixes:" section would be the right one to add to.
- [ ] Tests. (Encouraged but not strictly required.) -> I can add a test if you think it is useful but haven't looked into the testsuite yet.

## Notes

- There might be a similar issue in other metadata source plugins as well (amazon, beetport, ...) but I haven't looked into them since I don't use them (yet).
- There might be a better place to fix this than in the in the candidates method, please point me there / let's discuss. Thanks in advance!

### CODE REVIEW

**Comment by JOJ0** [comment]
This is the beginning of an verbose output with the patch in place, using the same untagged album as used in the issue link above:
```
    ~/git/beets    discogs_skip_untagged ?5  beet -v import --set genre_orig_dir="test import" /remote/data/music-archive/DowntempoTriphopDubAcidjazz/0-ALBUMS/Thievery\ Corporation\ -\ The\ Mirror\ Conspiracy\ C+D        INT ✘ 
user configuration: /home/jojo/.config/beets/config.yaml
data directory: /home/jojo/.config/beets
plugin paths: /home/jojo/git/beets/beetsplug; /home/jojo/git/mried_beetsplug/beetsplug; /home/jojo/.local/lib/python3.9/site-packages/beetsplug
artresizer: method is (2, (7, 1, 0), False)
thumbnails: using IM to write metadata
thumbnails: using GIO to compute URIs
Sending event: pluginload
library database: /home/jojo/jtbeets.db
library directory: /home/jojo/Music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: /remote/data/music-archive/DowntempoTriphopDubAcidjazz/0-ALBUMS/Thievery Corporation - The Mirror Conspiracy C+D
Tagging  - 
No album ID found.
Search terms:  - 
Album might be VA: True
discogs: Skipping Discogs query. Files missing album and artist tags.
Requesting MusicBrainz release 01fdaeb5-f4fc-46d6-a43c-4b2f61e95564
Sending event: mb_track_extract
Sending event: mb_track_extract
...
...
```

**Comment by sampsyo** [comment]
Seems like a great idea! Would you mind adding a quick changelog entry, please?

**Comment by JOJ0** [comment]
Added changelog entry and rebased master into feature branch.

**Comment by JOJ0** [comment]
Also added a short note on general search behaviour and the newly introduced "skipping behaviour" to the plugin docs. I can leave it out if you think it's unnecessary clutter or doesn't fit into this PR.

Since some basic concepts are described in the "Installation" chapter already, I added it there.

**Review by sampsyo — APPROVED** [review]
Great; thanks!!! Seems nice to have for completeness' sake. I think this is good to go once the CI comes back green.

**Comment by martimpassos** [comment]
Hello, is this supposed to have fixed [this scenario](https://discourse.beets.io/t/improve-discogs-matches/2056)? I would think that 
```
Finding tags for album "A.R.T. - Everybody Need Somebody"
```
means my files have decent album and artist tags, but the results seem arbitrary as you mentioned. Am I missing something here?

**Comment by JOJ0** [comment]
Hi @martimpassos please provide the same run using -v and what beets version u are using exactly. Thanks

**Comment by JOJ0** [comment]
Hi @martimpassos, i answered to your forum post with some suggestions that might help to find out if this PR's fix could help.

**Pull request merged**
