### PR TITLE
Replace the clinical "obsessive-compulsive" term

### PR DESCRIPTION
**Pull request by regisb**
This is a follow-up on that conversation on gitter:
https://gitter.im/beetbox/beets?at=5d75ac34b3e2fc579379fe25

### CODE REVIEW

**Comment by jackwilsdon** [comment]
Is it worth opening a PR against the `gh-pages` branch too to get this changed on https://beets.io?

https://github.com/beetbox/beets/blob/gh-pages/index.md

**Comment by jackwilsdon** [comment]
Is it worth opening a PR against the `gh-pages` branch too to get this changed on https://beets.io?

https://github.com/beetbox/beets/blob/4f491be99ce5d27ef43d83663ba5d50087cb7aaa/beets.js

https://github.com/beetbox/beets/blob/4f491be99ce5d27ef43d83663ba5d50087cb7aaa/_layouts/main.html

**Comment by regisb** [comment]
@jackwilsdon Sure thing: https://github.com/beetbox/beets/pull/3421

**Comment by jackwilsdon** [comment]
Looks like this line needs changing too to get tests to pass:

https://github.com/beetbox/beets/blob/0c033bdaf10b78be04e6ebc8f998d9d3d5f70e3d/test/rsrc/lyrics/examplecom/beetssong.txt#L223

**Comment by regisb** [comment]
@jackwilsdon Right. It's strange that my IDE (Atom) didn't find this file when I searched-and-replaced. Maybe because `test/rsrc/lyrics/*` is in `.gitignore`.

**Comment by sampsyo** [comment]
Fantastic; thanks, both of you!

**Pull request merged**
