### PR TITLE
fix: beetsplug web: memory leak #2600 - https://github.com/beetbox/be…

### PR DESCRIPTION
**Pull request by robot3498712**
This should fix
https://github.com/beetbox/beets/issues/2600
beetsplug web: memory leak

### CODE REVIEW

**Comment by sampsyo** [comment]
Hi! Thanks for opening this PR so quickly!

It looks like this change may have broken some tests. Can you take a look and see if there's an easy explanation? (We have a Testing wiki page with lots of instructions about how to run the tests.)

**Comment by robot3498712** [comment]
Hi sampsyo,
my pleasure!

I've been running the server for couple days without problems in regards to functionality or resource usage. Works for me (tm)!

Quick look, appears tests may be failing because attempting to reuse formerly (in my patch) closed db connection.
app => req->open(dbconn->open) => do_something(dbconn) => req->close(dbconn->close*) => test->run(dbconn) == FAIL
* As well see http://flask.pocoo.org/docs/0.12/tutorial/dbcon/ . Based on my observations it is assumed db connections haven't been closed properly, thus binding resources after the request has finished.

I know very little about the inner workings of beets. If my patch in general is fine then I can try fixing the tests. Please let me know in case!
Thank you

**Comment by sampsyo** [comment]
Hmm… oddly, this precise change actually broke the plugin for me on my machine. Using `teardown_appcontext` seems to have gunked things up; I get errors when running `beet web` like this: `RuntimeError: working outside of request context`.

I presume you might be using `teardown_request` locally instead of `teardown_appcontext`? That seems like the right place to manipulate things under Flask's `g` context. That lets me reproduce the test failures we're seeing.

In any case, this seems like a fine change and, yes, the problem is with the tests, not the fix. The problem is that the tests are using `:memory:` for the database path, which means that every time we close the connections we get a fresh, uninitialized database. A standard way around this is to make the tests use an on-disk database in a temporary folder that gets cleaned up after the tests run.

Thanks again for looking into this!

**Comment by robot3498712** [comment]
Thanks for trying it out (and finding a problem)!

I can confirm this is the exact and only change to web plug (or otherwise) here; double checked with winmerge. Anyway, all things being non-deterministic ...
teardown_request seems to be fine as well, memory usage is stable - I'll push the change :)

I appreciate the test pointers, will try to have a look upcoming days.
Ciao

**Comment by sampsyo** [comment]
Cool; thanks for changing that. Please let me know if you need help digging into the tests.

**Comment by jtpavlock** [comment]
@robot3498712 do you still intend to work on this?

**Pull request closed without merging**
