### PR TITLE
hook: switch to using check_call

### PR DESCRIPTION
**Pull request by jackwilsdon**
A small change but hopefully part of a larger piece of work around #2835.

### CODE REVIEW

**Comment by sampsyo** [comment]
Seems right to me! Maybe we should also catch [CalledProcessError](https://docs.python.org/3.7/library/subprocess.html#subprocess.CalledProcessError) and print a friendly message when the hook fails?

**Comment by jackwilsdon** [comment]
Aha, good catch! I clearly didn't look into the `check_call` documentation enough to see it can throw things other than an OSError :grimacing:

**Comment by jackwilsdon** [comment]
I've gotten half way through implementing support for `on_error` - I've implemented `on_error: abort` by raising a `ui.UserError` which does seem to quit beets, although I'm not too sure on what state it actually leaves beets in :confused: I may as well go ahead and finish it off a bit more (thinking of just implementing `abort`, `log` and `ignore` without any of the `skip_*` handlers) and I'll open a PR for it so we can discuss whether or not it is worth implementing there.

**Comment by sampsyo** [comment]
Perfect; thanks! I merged this as is.

That's cool; thanks for looking into `on_error`. And indeed, I'm actually also not entirely sure how dangerous just raising a `UserError` might be—it seems to depend a lot on the context, such as the particular event that is aborting things? Maybe we can get feedback from the original requester about what exactly they wanted to happen and why…

**Pull request merged**
