### PR TITLE
Get the date of the parentwork, which may be different from the date of the child work.

### LINKED ISSUE #3650: work_date of parentwork with parentwork plugin
I currently have my beets library paths looking like this (I mostly have classical music, so I use the parentwork plugin): parent_composer_sort/work_date - parentwork/..., but if different subworks have different dates, this can store them in different directories.  Is there a way to work around this, perhaps in the path config?  Or would I need to write a plugin or edit the parentwork plugin?

### PR DESCRIPTION
**Pull request by aereaux**
##  Description

Fixes #3650.

## To Do

- [x] Documentation. (If you've add a new command-line flag, for example, find the appropriate page under `docs/` to describe it.)
- [x] Changelog. (Add an entry to `docs/changelog.rst` near the top of the document.)
- [ ] Tests. (Encouraged but not strictly required.)

### CODE REVIEW

**Comment by dosoe** [comment]
Looks fine to me! I'm wondering if we should keep the ```work_date``` tag, maybe this new one makes it redundant.

**Comment by dosoe** [comment]
There are two ways to get the date: either you just go up the work tree and pick the first one you find (```work_date```) or you go up to the parentwork and take its date (```parentwork_date```). Generally they are the same, but on MB all works don't have a date so picking the first date you find makes it more probable that you will actually end up with a date. On the other hand, especially for collections, different parts of a work can have different composition dates so with ```work_date``` you end up with different dates for the same parentwork whereas with ```parentwork_date``` you most probably end up with no date at all in these cases, but at least a given parentwork always has the same ```parentwork_date```.

**Comment by dosoe** [comment]
One maybe: is there some kind of formatting for dates in beets that the dates should be converted to?

**Comment by aereaux** [comment]
I'm not sure if there is a specific date format style, but I copied this more or less from the way `work_date` is generated, so I don't think there is.

**Comment by dosoe** [comment]
Then it should be fine and ready to merge.

**Comment by sampsyo** [comment]
Excellent!

**Pull request merged**
