### PR TITLE
Cache tox and pip directories for travis

### PR DESCRIPTION
**Pull request by jrobeson**
See discussion in: https://github.com/beetbox/beets/pull/1987

### CODE REVIEW

**Comment by jackwilsdon** [comment]
Perfect! It seems like the rest of the file uses 4 spaces for indentation and your changes only use 2, do you think you could change this?

**Comment by jrobeson** [comment]
yeah.. that was silly of me.  i rebased it with 4 space indent

**Comment by jackwilsdon** [comment]
Just a note for the future: There's not really any need to rebase your PRs, just add another commit :smile:.

Do you think you could maybe remove the `$HOME` pip cache and instead let travis handle the pip caching like this?

```YAML
cache:
    pip: true
    directories:
        - .tox
```

Thanks so much!

**Comment by jrobeson** [comment]
none of the example repositories you linked to did, so I didn't either.  I've had problems combining options like this on travis before, so i decided to stay conservative.

I know i didn't have to rebase, but i prefer it when fixing the equivalent of a typo

**Comment by jrobeson** [comment]
here goes, let's see if it works.

**Comment by jackwilsdon** [comment]
Well it certainly looks like it's working!

[`cache.1`](https://travis-ci.org/beetbox/beets/jobs/128137774#L162)

[`cache.pip`](https://travis-ci.org/beetbox/beets/jobs/128137774#L174)

**Pull request merged**
