### PR TITLE
Really fix album replaygain calculation with gstreamer backend.

### LINKED ISSUE #2845: Calculating album replaygain with gstreamer still causes error
### Problem

I have the same issue as in #2636 when calculating replaygain for my whole collection.
Upgrading from 1.4.5 (which do not contain the fix for #2636 ) to 1.4.6 only reduces the error occurrence rate from 80% to 30%.

### Setup

* OS: Gentoo Linux
* Python version: 2.7.14
* beets version: 1.4.6

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    sources: '*'
    google_API_key: REDACTED
    force: no
    auto: yes
    genius_api_key: REDACTED
    google_engine_ID: REDACTED
    bing_lang_to:
    bing_client_secret: REDACTED
    fallback:
    local: no

paths:
    comp: ${album_genre}/Various Artits/${year} - ${album}%aunique{}/${disc_and_track} - ${title} ($artist)
    singleton: ${single_genre}/${artist}/%if{${year},${year} - }${title}
    default: ${album_genre}/${albumartist}/${year} - ${album}%aunique{}/${disc_and_track} - ${title}
fetchart:
    minwidth: 500
    maxwidth: 600
    sources: filesystem coverart amazon albumart fanarttv
    fanarttv_key: REDACTED
    auto: yes
    google_engine: 001442825323518660753:hrh5ch1gjzm
    enforce_ratio: no
    cautious: no
    store_source: no
    google_key: REDACTED
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
library: /srv/music/.beets.db

replace:
    '''': "\u2019"
    ^\.: _
    \s+$: ''
    ^\s+: ''
    ^-: _
original_date: yes
replaygain:
    auto: no
    backend: gstreamer
    targetlevel: 89
    r128: [Opus]
    overwrite: no
badfiles:
    commands:
        mpc: mpcdec -c

plugins: discogs chroma fetchart embedart scrub lastgenre badfiles missing edit inline info convert duplicates replaygain types web mbsync lyrics
types:
    mp3car: bool
    myrip: bool
web:
    reverse_proxy: yes
    include_paths: yes
    host: 127.0.0.1
    port: 8337
    cors: ''
convert:
    dest: /srv/music-export
    command: /usr/local/bin/gapless-mp3enc $source $dest
    never_convert_lossy_files: yes
    embed: no
    album_art_maxwidth: 0
    format: mp3
    auto: no
    threads: 2
    copy_album_art: no
    tmpdir:
    max_bitrate: 500

    paths: {}
    pretend: no
    quiet: no
    formats:
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    no_convert: ''
item_fields:
    disc_and_track: u'%i%02i' % (disc, track) if disctotal > 1 else u'%02i' % (track)
    single_genre: genre.split(', ')[0] if genre else u'Other'
per_disc_numbering: yes
id3v23: yes
album_fields:
    album_genre: genre.split(', ')[0] if genre else u'Other'
lastgenre:
    source: artist
    count: 1
    prefer_specific: yes
    whitelist: /srv/music/.beets.genres.txt
    canonical: /srv/music/.beets.genres-tree.yaml
    force: yes
    min_weight: 10
    auto: yes
    separator: ', '
    fallback:
path_sep_replace: '~'
directory: /srv/music

import:
    timid: yes
    detail: yes
acoustid:
    apikey: REDACTED
discogs:
    user_token: REDACTED
    tokenfile: discogs_token.json
    apikey: REDACTED
    apisecret: REDACTED
    source_weight: 0.5
embedart:
    compare_threshold: 0
    auto: yes
    ifempty: no
    remove_art_file: no
    maxwidth: 0
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
edit:
    itemfields: track title artist album
    albumfields: album albumartist
    ignore_fields: id path
missing:
    count: no
    album: no
    total: no
chroma:
    auto: yes
scrub:
    auto: yes
pathfields: {}
```

### PR DESCRIPTION
**Pull request by sdrik**
Fixes #2845

### CODE REVIEW

**Comment by sampsyo** [comment]
Interesting; thanks!! Can you please describe a little bit about why this seems to be the right fix?

Also, please add a quick changelog entry if you have a moment.

**Comment by sdrik** [comment]
As I'm not a gstreamer expert this was almost trial and error, but the existing comment about "ensuring that the filesrc and decodebin elements received the paused state of the pipeline in a blocking manner" led me to the right direction.

What I understand is that even if the paused state is set in a blocking manner on the pipeline in _set_next_file, it is propagated asynchronously to its child elements (filesrc and decodebin), thus the sync_state_with_parent/get_state calls in _set_file.
But those synchronization calls were made _after_ the unlink/set_state/set_property calls, leading to a race condition.
So my fix is simply to move the synchronization calls before any calls affecting filesrc and decodebin.
I also remove the added set_state(PLAYING) because it is obviously redundant with the one in _set_next_file.

**Comment by sampsyo** [comment]
Got it! That makes a lot of sense. Thank you for looking into it and finding this fix—trial-and-error is usually the way I sort things out with GStreamer too. :sparkles:

**Comment by Chingon2** [comment]
Got it also, thanks.
http://goodsiteslike.com/sites-like-opploans/

**Pull request merged**
