### PR TITLE
Removes support for bs1770gain.

### LINKED ISSUE #3127: replaygain: bs1770gain backend is associated with white nationalism
### Problem

It appears the creator of the bs1770gain backend used as an optional backend in the replaygain plugin is a staunch white nationalistAnd has dedicated the project "to [his] European heritage". This seems like something beets should distance itself from.
I've included the full quote from the [project website](http://bs1770gain.sourceforge.net) which is linked to in the [replaygain plugin manual](https://beets.readthedocs.io/en/v1.3.17/plugins/replaygain.html#bs1770gain). Clicking through to the creator's [personal site](http://home.snafu.de/pbelkner/) reveals much more of a similar nature.
> Nanos gigantum humeris insidentes: This project is dedicated to my European heritage. It is strictly to be understood as a statement against the saccarine "sweet" liberal lie of "multiculturalism" which is going to destroy Europe as we know it, in particular against the Merkel regime selling out Europe for nothing as we watch. #TeamWhite

### PR DESCRIPTION
**Pull request by SamuelCook**
References in the documentation to this plugin were removed in beetbox/beets#3127 (beetbox/beets#3130) but no actual code changes were made.

This PR removes support for this dependency entirely.

## Description

Fixes #3127.

- [x] Changelog. (Add an entry to `docs/changelog.rst` near the top of the document.)

### CODE REVIEW

**Comment by wisp3rwind** [comment]
> [x] Changelog. (Add an entry to docs/changelog.rst near the top of the document.)

Since this changes optional dependencies, I think it should also get an entry in the _For packagers_ section of the changelog.

**Comment by sampsyo** [comment]
Seems about right to me.

**Comment by SamuelCook** [comment]
Good call. I've done that, and also spotted and removed one additional bs1770gain changelog entry for 1.5.0 that is no longer accurate.

**Review by sampsyo — APPROVED** [review]
Nicely done. Thank you for the thorough audit.

**Pull request merged**
