### PR TITLE
Added new playlister plugin

### PR DESCRIPTION
**Pull request by marcwie**
Hi,

I have developed a small plugin that let's the user add imported tracks directly to a set of playlists. Please let me know what you think about it. 

Cheers,
Marc

### CODE REVIEW

**Comment by sampsyo** [comment]
Interesting idea. This seems to work something like the `smartplaylist` plugin, except that you get to choose using an on-the-fly interactive prompt from a menu of possible destinations (instead of query rules).

A slightly more beets-y way of accomplishing this would be to use flexible attributes. That is, you set up `smartplaylist` to make playlists based on queries of particular attributes of music and, on import, you set those attributes. This makes the decision about the playlist *persistent:* it's stored in the database and you can view or change the decision later. Does that suggestion make sense?

There's also a somewhat fundamental problem with plugins that query the user for input. No plugins do this currently because of beets' multi-threaded importer. By the time we get to the file-copying stage, the user may be looking at tag changes for a different album, several directories down the line. If we add something like this, we will need new plugin hooks that let you talk to the user in the correct stage.

**Comment by marcwie** [comment]
Thanks for you quick feedback :)

Yeah, I think using attributes and ``smartplaylist`` does make a lot of sense. In that case, however, it would be nice if the user could set the attributes during the import. I am speaking from my personal experience here, as this would help me to sort my music correctly right away (this is also one of the reasons why I started this little project). It would also ensure that all tracks that I import are sorted in some fashion. At least if I want it to. 

What I would find helpful is that users are prompted a list of all existing attributes (as it is implemented now with the list of existing playlists). At some point it is probably impossible to remember all attributes (including spelling, capitalization, etc...) and enter them without any guidance. But may be this also goes to far. 

In the end, this would still require for some user given inputs, right? I am sorry, that I did not know about the problem with the multi-threaded importer. This could certainly cause some trouble. 

The advantage about the current approach is probably, that users can also simply copy existing playlists into their playlist folder and add new tracks to those playlists on import. But I agree that this is not very beets-y as well.

**Comment by sampsyo** [comment]
Yes, I do like the idea of adding some way to ask the user for information during import. The most basic, and probably most user-unfriendly, way would be to have you specify the key and value every time you want to add an attribute during import.

Perhaps a better match for this scenario would be to pre-configure a plugin with a set of attributes to ask about. If, for example, you want to categorize music based on whether it's "pop" or not, then you could tell the plugin to specifically ask:

    pop? [yn]

for every new album.

Something generally like this would be awesome to explore.

**Comment by jtpavlock** [comment]
closing as abandoned

**Pull request closed without merging**
