### PR TITLE
DO NOT MERGE - Single commit of "multi-tags PR" (4743)

### PR DESCRIPTION
**Pull request by jmbannon**
For testing, merge https://github.com/beetbox/beets/pull/4743 instead

### CODE REVIEW

**Comment by arsaboo** [comment]
Is there any additional config required to get this running? I installed it using `pip install --upgrade --force-reinstall --no-deps git+https://github.com/jmbannon/beets.git@j/multi-single3`

However, I still see (notice the second artist is stripped):

image

**Comment by jmbannon** [comment]
No additional config'ing needed @arsaboo . It still uses the original `artist` tag in that view. Apply and then view that song's tags

**Comment by jmbannon** [comment]
Also @arsaboo , multi-tags only get read from Musicbrainz currently - I think that song's metadata is getting scraped from spotify

**Comment by arsaboo** [comment]
Ok, [here's](https://beta.musicbrainz.org/release/ce2ea861-20c0-4ffa-ba26-3415aaa2f768) the album I am trying to import from MB. Here's how it appears:
image

The album is ID 30. 
image

I do see multiple artists in `albumartist_sort` and `albumcredit_sort`. Is it consistent with our expectations?

**Comment by jmbannon** [comment]
The tags are `albumartists`, `artists`, `albumartists_sort`, etc which aren't in your screenshot. You might need to use ffprobe to see them, not sure which app you are using

**Comment by jmbannon** [comment]
Beets CLI should show them as well, I forget the command, let me try to find it

**Comment by jmbannon** [comment]
You need to enable the `info` plugin and do `beet info <query>`, should see the multi-tags there. That will list what's in the DB though, use ffprobe to verify its on the files themselves

**Comment by jmbannon** [comment]
Removed the multi-tag for this song in Musicbee, did a write in beets and see:
image

**Comment by jmbannon** [comment]
Here is the `beet info` for that song:
```
/tagged/B.B. King _ Eric Clapton/[2000] Riding With the King/03 - Key to the Highway.mp3
            album: Riding With the King
      albumartist: B.B. King / Eric Clapton
     albumartists: B.B. King; Eric Clapton
      albumstatus: official
        albumtype: album
       albumtypes: album
              art: False
           artist: B.B. King & Eric Clapton
      artist_sort: King, B.B. & Clapton, Eric
          artists: B.B. King; Eric Clapton
          barcode: 9325583007156
         bitdepth: 0
          bitrate: 256000
     bitrate_mode: 
       catalognum: 9362476122
      catalognums: 9362476122
         channels: 2
          country: AU
             date: 2000-01-01
             disc: 1
        disctotal: 1
     encoder_info: 
 encoder_settings: 
           format: MP3
            genre: Blues
           genres: Blues; Soul
             isrc: USRE10000578
            label: Reprise Records
           length: 220.00325
 mb_albumartistid: dcb03ce3-67a5-4eb3-b2d1-2a12d93a38f3
mb_albumartistids: dcb03ce3-67a5-4eb3-b2d1-2a12d93a38f3; 618b6900-0618-4f1e-b835-bccb17f84294
       mb_albumid: b5d8ea9b-cc7b-45bd-bd57-c004a21e4d1e
      mb_artistid: dcb03ce3-67a5-4eb3-b2d1-2a12d93a38f3
     mb_artistids: dcb03ce3-67a5-4eb3-b2d1-2a12d93a38f3; 618b6900-0618-4f1e-b835-bccb17f84294
mb_releasegroupid: 866529e9-0ca2-35fa-8c6f-65ec1424ff0e
mb_releasetrackid: b8bd83f8-1343-4909-8122-9f0e8a386546
       mb_trackid: e059a6c6-e327-40f1-bff2-612fd7e92e95
            media: CD
    original_date: 2000-06-07
     original_day: 7
   original_month: 6
    original_year: 2000
    rg_track_gain: -3.1
    rg_track_peak: 1.135011
       samplerate: 44100
           script: Latn
            title: Key to the Highway
            track: 3
       tracktotal: 12
             year: 2000
```

**Comment by jmbannon** [comment]
from my test, everything works as expected

**Comment by arsaboo** [comment]
Yes, I see them now 👍 

image

I am browsing the database using SQlite.

**Comment by JOJ0** [comment]
Since #4743 is merged, closing.

**Pull request closed without merging**
