### PR TITLE
Create walkthrough with images

### PR DESCRIPTION
**Pull request by zacharybmeyers**
## Description

Creates a guided walkthrough for first-time users of Beets. 

The goal of this contribution is to help people with little to no experience get started with the Beets CLI, and provide them with a sample music library of public domain songs/albums to manipulate and experiment with. I went through this process of getting started on my own and figured it could help others in the future if I documented my progress.

The sample library that I've compiled for use during the walkthrough is hosted at a public Google Drive link. Ideally, I would've preferred to use `git-lfs`, but I wasn't able to on my fork since I don't have GitHub Enterprise. If there's a better way to store the .zip please let me know.

## To Do

- [ ] Documentation. (If you've add a new command-line flag, for example, find the appropriate page under `docs/` to describe it.)
- [x] Changelog. (Add an entry to `docs/changelog.rst` near the top of the document.)
- [ ] Tests. (Encouraged but not strictly required.)

### CODE REVIEW

**Comment by wisp3rwind** [comment]
> Creates a guided walkthrough for first-time users of Beets.

Seems like a great idea to have a more visual introduction to beets! I've not (yet) taken the time to read through this in detail, so here are only a few high-level thoughts:

- I don't like the idea of pointing from our documentation to someone's private Google Drive folder, via a URL shortener, when most people will probably have their own music they want to import (in which case we could recommend to copy a few of their albums to a separate folder to play around with safely before going all-in and importing their entirely collection). We could still retain the links to the freely-licensed music and recommend that as an alternative.

- By merging this as-is, we would effectively duplicate the [Getting started](https://beets.readthedocs.io/en/stable/guides/main.html#getting-started) guide. I think it would be much better to modify that page instead, adding screenshots showing the results of the various commands explained there.

- Explaining the `web` plugin seems to be somewhat out-of-place for an introductory tutorial. (It might be nice to generally mention the existence and capabilities of plugins.)

In my opinion (which might not be shared by all beets contributors), this PR in its current format would be better suited for a blog post on your personal blog given that it does not really integrate with the "official" documentation. We could still link to this, maybe similar to what I proposed here: https://github.com/beetbox/beets/pull/4363#issuecomment-1153142536

**Comment by sampsyo** [comment]
Wow! Thank you for the really nice writeup here; there is a lot of detail—and the use of concrete examples really helps a lot. Fantastic work on this.

I'm open to helping publish this in any format; many ways of doing it seem reasonable. One option, if you're interested, would be to make it a proper post on [the extremely occasional beets blog](https://beets.io/blog/), which has hosted detailed/evergreen articles like this in the past.

**Comment by zacharybmeyers** [comment]
Thank you both for the feedback! I'm open to whatever works best for the project: publishing to the beets blog or a new `Third-party Tutorials` section like @wisp3rwind mentioned. I'll leave that choice to your preference. I made this guide without knowing exactly where it would fit in for the project so I am flexible and happy to modify or publish it wherever it helps the most.

**Comment by wisp3rwind** [comment]
> Thank you both for the feedback! I'm open to whatever works best for the project: publishing to the beets blog or a new `Third-party Tutorials` section like @wisp3rwind mentioned. I'll leave that choice to your preference. I made this guide without knowing exactly where it would fit in for the project so I am flexible and happy to modify or publish it wherever it helps the most.

How about doing both, i.e. convert it to a post on the beets blog, and also add a link in that section? Other opinions on what is the best venue for the tutorial?

**Comment by arsaboo** [comment]
I agree with the blog post route since there is a lot of user-specific information.

**Comment by sampsyo** [comment]
Sounds like this is a great fit for the blog. Let's do that, and take @wisp3rwind's suggestion to also link to it from the appropriate place in the docs.

@zacharybmeyers, what would you think about moving this content to a blog post and opening a new PR against [the `gh-pages` branch](https://github.com/beetbox/beets/tree/gh-pages) in this repository? 🙏

**Comment by zacharybmeyers** [comment]
Can do, @sampsyo! I'll close this PR and get that new one started over on the gh-pages branch.

**Pull request closed without merging**
