### PR TITLE
Add write option to bpm plugin

### PR DESCRIPTION
**Pull request by jackwilsdon**
Add write option to `bpm` plugin and tidy up command function.

It looks like a write option was going to be implemented but never ended up being added? The reason I think this is that there's an unused `write` argument for `get_bpm` that writes the item after the BPM is updated.

See #1991 and [#1991 (comment)](https://github.com/beetbox/beets/issues/1991#issuecomment-217119879) for more information.

### CODE REVIEW

**Comment by sampsyo** [comment]
Good idea; thanks!

We actually have some generic machinery for this kind of thing in the form of the `beets.ui.should_write()` function. The idea is that the `import.write` option serves as a default, but plugins can override with their own one-off write option too. Here's an example in the `mbsync` function:
https://github.com/beetbox/beets/blob/db36d68f5bb05683d954a9e3dfcc6959cbfbba88/beetsplug/mbsync.py#L68

Can we use that so users like @jfunction get what they expect the first time around?

**Comment by jackwilsdon** [comment]
So should I remove the `bpm.write` configuration value? Or should I pass it's value to `should_write` so it can be set either in `bpm.write` or `import.write`?

**Comment by sampsyo** [comment]
Probably the most straightforward way would be to remove that option, yes. If you like, we could also add a command-line override flag like `mbsync` has.

**Comment by Kraymer** [comment]
lgtm

**Comment by sampsyo** [comment]
Hey! @Kraymer's comment reminded me that this was still open. Sorry for letting this slip through the cracks! It looks like this is 100% ready to go (modulo moving the changelog entry)?

**Comment by sampsyo** [comment]
Merged with changelog entry moved! :sparkles: Many belated thanks, @jackwilsdon.

**Pull request merged**
