### PR TITLE
Fix changelog reminder workflow

### PR DESCRIPTION
**Pull request by snejus**
Quote the breaking glob as noted by @bal-e.

### CODE REVIEW

**Comment by snejus** [comment]
I was expecting it to remind me to update the changelog on this PR too 🕵🏼 🤨

**Comment by bal-e** [comment]
I'm going to try rebasing #5303 on top of this to trigger the changelog action.

**Comment by snejus** [comment]
Not sure, I think there's only one way to test it 🤷🏼‍♂️ at least now we know it shouldn't break!

**Comment by Serene-Arc** [comment]
How bizarre. This is why testing GH actions are such a pita. They run in very strange ways. If you look at the checks, it hasn't been attempted. Maybe there's a restriction on running jobs that are being updated?

**Comment by Serene-Arc** [comment]
It might still be running the version on master, rather than the one on the PR?

**Comment by bal-e** [comment]
Yeah, maybe we should just try merging this PR and seeing if it helps.  I can't think of a better option, which sucks.

**Comment by Serene-Arc** [comment]
GitHub actions and CI are amazing and useful but not easy to test and honestly, half of the time the only way TO test it is to push to production and just see what breaks. When I was writing the release workflow, I pushed to MY repo, and did a bunch of breaking changes, and then just reset it to upstream. And it *still* didn't find everything.

**Comment by snejus** [comment]
I think it's happier now: https://github.com/beetbox/beets/actions/runs/9525145560/job/26258903712

**Comment by Serene-Arc** [comment]
Wonderful

**Pull request merged**
