### PR TITLE
Fetch original_year from master releases for Discogs (#1122)

### PR DESCRIPTION
**Pull request by dbogdanov**
This adds an additional Discogs API call from inside get_album_info() via a very basic fetch method (it only returns year). This may be expanded in the future to fetch other fields from the master release (genres, styles, etc.) if necessary.

Assume that ``original_year`` equals to ``year`` for releases without a master release. If parsing the original year in the master release fails, the resulting value is kept as ``None``. 

I am not sure how to update tests, because the API call is inside ``get_album_info``. The functionality is so basic that possibly it is not necessary (and other API calls aren't tested as well).

### CODE REVIEW

**Comment by sampsyo** [comment]
Looks great! This information will be useful to have.

I notice that we now have some similar-looking exception-handling code for the calls into the Discogs API. (The handlers for `DiscogsAPIError` and `CONNECTION_ERRORS` are very similar between the `Master` and `Release` fetching code, for example.) Would it make sense to refactor that code so it can be shared between the different resource retrievals?

**Comment by dbogdanov** [comment]
May be, but it may also complicate the code. The code is similar for ``candidates()``, ``album_for_id()`` and ``get_master_year()`` methods. The return values, retry method and log messages are different though. If there will be more methods like this than yes.

**Comment by sampsyo** [comment]
OK, cool. It's only worth pursuing if it can be done in a way that makes the code simpler, not more complex. Other than that, I think all we need is a changelog entry here.

**Comment by sampsyo** [comment]
Perfect. Thanks again! :sparkles:

**Comment by sampsyo** [comment]
...and thanks for all your contributions over the last week or two. I’ve invited you as an organization member, so you should now be able to commit directly. Of course, pull requests are always still an option as a way to get code reviews!

**Pull request merged**
