### PR TITLE
Add FFmpeg requirement info and links to installation guides

### PR DESCRIPTION
**Pull request by hardyoyo**
## Description

- Add documentation re: the requirement for FFmpeg, and links to installation guides for FFmpeg.
- Refs #1250

### CODE REVIEW

**Comment by snejus** [comment]
By default beets does not depend on ffmpeg. Plugins like `replaygain` and `convert` do, so maybe docs of these plugins would be more relevant for these installation instructions?

**Comment by hardyoyo** [comment]
You're right, and the Chroma plugin *does* [mention needing FFmpeg](https://beets.readthedocs.io/en/v1.3.17/plugins/chroma.html) (among other things). I believe this PR would be better if it instead directed users to investigate the dependencies of any plugins they wish to use, instead of blindly instructing folks to install FFmpeg. I'll revise it.

**Comment by hardyoyo** [comment]
actually, this seems like an unnecessary hint... I'm just going to close this PR

**Comment by snejus** [comment]
> instead directed users to investigate the dependencies of any plugins they wish to use,

Some more clarity in our docs sounds like a good idea!

**Pull request closed without merging**
