### PR TITLE
Use template when modifying tag values

### PR DESCRIPTION
**Pull request by PierreRust**
First part of the implementation for #488. This provides template support when modifying tag's value.

### CODE REVIEW

**Comment by sampsyo** [comment]
Seems good to me! I agree this is actually pretty straightforward—no need to get fancy.

A few comments:

* No need for that performance optimization for now, IMO. This will make things a bit more brittle and it's not 100% clear that it gains us that much. Let's measure first.
* Let's do the templating in the modify command, not in `dbcore`. If we put it in `dbcore`, then there is no way around the feature: it will be impossible for code to set the value of a field to an arbitrary string that doesn't get interpreted. It's better if this is kept local to where we're exposing the functionality to users.
* In that context, it might be a good idea to parse the template strings once (i.e., instantiate a `Template` object once) and re-use it many times for all the matched items. This is a clearer win than the other performance shortcut.
* We'll need to add documentation.

**Comment by PierreRust** [comment]
Yes, I also thought this could be done in the modify command, but for #488 I'd also like to allow this kind of interpretation when importing (on the command line and in configuration)  and I'd like to avoid duplicating the code in both command. I'll see what I can do.

**Comment by sampsyo** [comment]
Yes, we do want this to happen in multiple places, so we may need to factor out some code that each of those places can re-use. Fortunately, though, using the template system is so straightforward that not much code needs to be duplicated for each instance.

**Comment by jtpavlock** [comment]
@PierreRust do you still have any interest in getting this merged?

**Pull request closed without merging**
