### PR TITLE
Add flake8 problem matcher

### PR DESCRIPTION
**Pull request by jackwilsdon**
## Description

This PR implements the flake8 half of #3614 using a [problem matcher](https://github.com/actions/toolkit/blob/1cc56db0ff126f4d65aeb83798852e02a2c180c3/docs/problem-matchers.md), giving us nice inline errors like this on PRs:

inline error

I've had to disable `PY_COLORS` here, as the ANSI escape sequences were tripping up the regex used in the matcher.

## To Do

- [ ] Documentation. (If you've add a new command-line flag, for example, find the appropriate page under `docs/` to describe it.)
- [ ] Changelog. (Add an entry to `docs/changelog.rst` near the top of the document.)
- [ ] Tests. (Encouraged but not strictly required.)

### CODE REVIEW

**Comment by jackwilsdon** [comment]
Hmm, I've noticed that even though we're setting the `code` group, GitHub isn't actually showing the error code anywhere. Is it worth us compounding this back into the message and dropping the code completely? We'd get something like this instead:

inline error

**Comment by jtpavlock** [comment]
I just want to double check this won't be affected by the changes in https://github.com/beetbox/beets/pull/3694? In particular, the output from `pre-commit run -a` would display flake8 errors as such:

```
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

beetsplug/chroma.py:1:1: FI10 __future__ import "division" missing
beetsplug/chroma.py:1:1: FI11 __future__ import "absolute_import" missing
beetsplug/chroma.py:1:1: FI13 __future__ import "print_function" missing
```

**Comment by jackwilsdon** [comment]
Provided we output `::add-matcher::.github/flake8-problem-matcher.json` in one of our steps, it should continue to work with flake8 output no matter where it is:

image

**Comment by jtpavlock** [comment]
> Hmm, I've noticed that even though we're setting the `code` group, GitHub isn't actually showing the error code anywhere. Is it worth us compounding this back into the message and dropping the code group completely? We'd end up with the code in the message like this:

I like it with the error code, but probably not worth it if it's too much trouble

**Comment by jackwilsdon** [comment]
Changed it to add the error code back in - was a nice and easy fix :+1:

**Comment by jtpavlock** [comment]
will anything change if you do `[^\s]` rather than `[^ ]` ? (sorry for not asking this before you changed it 😄 )

**Comment by jackwilsdon** [comment]
I don't think so — the match is working correctly but GitHub just doesn't display the code anywhere in their UI.

I'll give it a shot in a bit though to see if anything interesting happens.

**Comment by jtpavlock** [comment]
> the match is working correctly but GitHub just doesn't display the code anywhere in their UI.

Ah okay, I see what you're saying now. Well this looks cool! I'm excited to see it in action. I think you should feel free to merge when you're ready 👍

**Comment by jackwilsdon** [comment]
Awesome, thanks!

**Comment by sampsyo** [comment]
Wow, this is awesome! I didn't know this was possible. This will be such a time saver!!

**Comment by jef** [comment]
Wow... This was a lot easier than expected. Nice work guys.

**Comment by jackwilsdon** [comment]
There may be some beneifts to using custom actions but this seemed like the path of least resistance for the time being.

**Comment by jef** [comment]
That makes sense to me. Much easier just to put in this way rather than wrap it up another action.

We could've used local actions, but IMO that would be even worse (readability) I suppose.

Nice work!

**Pull request merged**
