### PR TITLE
fix 'the' plugin regex

### LINKED ISSUE #3701: "the" plugin uses incorrect regex
### Problem

Running this command:

```sh
~ ❯ beet move artist:trance -p
Moving 40 items.
M:\TET - Travailleur En Trance\[2008] Cobra Coded Escalation\01-01 - Cobra Reporting In.mp3
  -> M:\‒ Travailleur En Trance, TET\[2008] Cobra Coded Escalation\01-01 - Cobra Reporting In.mp3
```

Led to this problem:

"TET" is recognized by the "the" plugin as something it should move. This is because the regex used in the.py, line 26, is
```
PATTERN_THE = u'^[the]{3}\\s'
```
which matches "TET". It should probably be:
```
PATTERN_THE = u'^the\\s'
```

### Setup

* OS: Windows 10 2004
* Python version: 3.8
* beets version: latest trunk
* Turning off plugins made problem go away (yes/no): obviously, if I disable 'the' it no longer does this

### PR DESCRIPTION
**Pull request by gschmidl**
## Description

Fixes #3701.  

## To Do

- [x] Changelog. (Add an entry to `docs/changelog.rst` near the top of the document.)
- [x] Tests. (Encouraged but not strictly required.)

### CODE REVIEW

**Comment by sampsyo** [comment]
Excellent; thank you!! That looks like a pretty strange mistake—good work tracking it down. :smiley:

**Comment by jtpavlock** [comment]
@gschmidl thanks for your work on this and https://github.com/beetbox/beets/pull/3688 !

Would you be interested in joining the beets team?

**Comment by gschmidl** [comment]
@jtpavlock I'm not sure how much use I can be since I'm on Windows (I initially tried WSL2 but that immediately did not work, asking me for a musicbrainz server) and have rather limited Python knowledge. I can try to get a working setup but I'm not sure how much I'll be able to contribute given time constraints.

**Comment by jtpavlock** [comment]
There aren't any contribution requirements, and being on windows could bring a unique perspective to the team! 

No worries if you feel you can't make it work, but the offer is there 😊

**Comment by jtpavlock** [comment]
Awesome! I sent you an email invite to our chat, and @sampsyo should add you to the org!

**Comment by sampsyo** [comment]
Invitation sent!

**Pull request merged**
