### PR TITLE
Importer UI overhaul

### PR DESCRIPTION
**Pull request by sampsyo**
This is [mxmerz/ui](https://github.com/mxmerz/beets/tree/ui), pulled into the main tree. See screenshots and such at #1593.

### CODE REVIEW

**Comment by sampsyo** [comment]
Hi! This was looking pretty close to ready for beta-level publicity. Shall we regroup and finish it off? Maybe we should start by making a to-do list of outstanding changes.

**Comment by mxmerz** [comment]
I’m very sorry for the long silence from my side – I had a busy November and December and am currently in my exam period… I hope to be able to help with this again in 1-2 weeks. From what I immediately remember, the dirty code I hastily hacked together worked okayish, but was severely lacking in quality, simplicity, documentation, and tests. And I am sure that the new UI is not showing changes for some tags, eg. track length, or when the chroma id didn’t match.
Sorry again for this half-assed amateur work, if no-one else dares to touch it I promise to get to it as soon as my exams are over and I have a bit more free time.

**Comment by sampsyo** [comment]
Fantastic! And no problem whatsoever—open-source hacking necessarily has to take second place behind exams. Thanks for keeping it in mind, and no rush at all.

I'll let you take the lead, but I'm happy to pitch in with code quality and such.

**Comment by ekjaker** [comment]
And maybe I can help out with some testing. I have been using these modifications for a large tagging job, and it worked nicely. As it is now, it's already a huge improvement.

**Comment by sampsyo** [comment]
Awesome! Yes, testing is great. Please do post if you run into any problems.

Adjusting the unit tests for the new UI would be helpful too.

**Comment by mxmerz** [comment]
I have a few new commits over at [mxmerz/ui](https://github.com/mxmerz/beets/tree/ui).

The “old” color definitions with a single string should work again.

I tried to refactor the `show_change` function in `ui/commands.py` – I split the function into `show_match_header`, `show_match_details`, and `show_match_tracks` and tried to split these again into smaller functions. My python skills are limited; I am not sure whether this is the best way to approach this and would appreciate feedback before I continue.

In `ui/__init__.py`, I added a function `uncolorize` which strips ANSI codes from a string and `color_len`, which measures the length of a colored string (`len(uncolorize(string))`). In `uncolorize`, I used a StackOverflow-inspired regex, do you know whether that is compatible with beet’s license and correctly attributed? I actually hope to get rid of both functions again, it does not seem to be a very elegant way…

**Comment by sampsyo** [comment]
Great! This looks like solid progress.

I sent you an invitation to join the @beetbox organization, which should let you merge your changes into the `ui` branch on this repository. Would you mind doing that?

And while `uncolorize` looks like a useful stopgap, I agree with you about eventually finding a solution that doesn't require it. Ideally, we'd be able to do things like getting the length of the string once, before adding colors, and avoid the cost of colorizing and then re-de-colorizing to recover the length.

**Comment by GuilhermeHideki** [comment]
For the colorize problem, you could subclass or composite `str` or `unicode` and create a field with the length, and in a colorize method, you would "overwrite" the uncolorized string with the colorized.

**Comment by jtpavlock** [comment]
Anything else that needs to be done here?

**Comment by sampsyo** [comment]
I think what this needs is some good old fashioned TLC—taking some time to review everything in detail and think carefully about the changes. I think the outcome (i.e., the resulting UI) already looks awesome.

**Pull request closed without merging**
