### PR TITLE
Replace confit with confuse

### PR DESCRIPTION
**Pull request by jackwilsdon**
Use [sampsyo/confuse](https://github.com/sampsyo/confuse) (previously named confit) throughout beets instead of having our own copy of it.

This is part of #1966 that has been separated at the request of @jrobeson. Go there if you would like to see our discussion so far.

**Note**: [This PR should not be merged until we've notified packagers of the new dependency](https://github.com/beetbox/beets/pull/1966#issuecomment-225643360) (i.e. the 1st of August and 1.4.0).

### CODE REVIEW

**Comment by sampsyo** [comment]
Nice!! This is looking fantastic! Great work!

There's one last unresolved question in my mind: should we somehow provide an alias so `import` statements in old plugins still work? Or should we depend on their developers to `import confuse` directly?

**Comment by jackwilsdon** [comment]
See I was thinking about that before but I'm not entirely sure, what do you think of making a `confit` alias but logging a deprecation message in verbose mode? We could make this more severe in the future (i.e. log in normal info mode).

**Comment by sampsyo** [comment]
Great idea! I'm not 100% sure how to accomplish such a warning, but I have every confidence that you do. :+1:

**Comment by jackwilsdon** [comment]
Well when you import a file the file is only executed once, meaning we could just get the beets logger (using `logger.getLogger`) and log a warning to that. It would only be printed once no matter how many times it is imported 😄.

**Comment by jackwilsdon** [comment]
Well I've found a rather interesting (and slightly confusing) trick:

`beets/util/confit.py`
```python
for key, value in __import__('confuse').__dict__.items():
    globals()[key] = value

del key, value
```

```python
from beets.util import confit
print(confit.__file__) # .../confuse-0.4.0-py2.7.egg/confuse.py
```

I don't know if this is good or not, maybe we should ignore all variables prefixed with `__`?

**Comment by jrobeson** [comment]
If we're really about to do this, then I'd like to get my changes merged into confit first.  Also, what do folks think about making six a confit dependency?

**Comment by jackwilsdon** [comment]
What features of `six` do we need in confuse? If you're looking to make changes you may be best making them both here and in [sampsyo/confuse](https://github.com/sampsyo/confuse) for now, as this isn't going to be merged for a while (at least the 1st of August).

**Comment by sampsyo** [comment]
Confuse is already Python 2/3 hybrid, FWIW.

**Comment by jrobeson** [comment]
depends on how you feel about the ergonomics of some things.  There are places in beets where we have to work around set bytes, and then don't decode them on exit when it seems like they should

**Comment by jrobeson** [comment]
@jackwilsdon : why not until august?

**Comment by jackwilsdon** [comment]
See the linked comment from @sampsyo in the OP 😄

**Comment by jrobeson** [comment]
i should learn to read. I didn't go that far up!

**Comment by jrobeson** [comment]
@sampsyo : if that's the case, why did you tell me to announce six already, and that we could start using it once your bugfix release is over?

**Comment by sampsyo** [comment]
six is an easier dependency to add, since it's already packaged for all distributions. The other ones will require downstream people to introduce new packages for the code we're splitting off.

**Comment by arcresu** [comment]
It looks like this branch has fallen behind. If I'm understanding correctly, the original hold up was about notifying distro packagers about the new dependency. From my experience with Debian packaging there's quite a bit of inertia to adding new packages in general given that they so often get neglected over time. "We need to package `confuse` to be able to update `beets`" makes for a stronger argument than "we should package `confuse` because `beets` is thinking about using it". I would propose that we just go ahead and introduce the dependency and at worst the distro packages would lag behind for a little bit. I'm not familiar with other distros though so things might work a bit differently to Debian's workflow.

**Comment by sampsyo** [comment]
In my fairly narrow experience, Debian represents the "high water mark" for difficulty in getting new packages and updates approved. (This is not meant as a criticism; it's just that Debian has settled on a careful, methodical, "high-touch" process that's at the opposite end of the spectrum from most other distros.) You're right that jumping right in and making it a dependency might be just what's needed to spur packaging.

**Pull request closed without merging**
