### PR TITLE
Replace __cmp__ with rich comparisons for Distance

### PR DESCRIPTION
**Pull request by jrobeson**
I'm not actually sure if this is enough or if we want to use total_ordering vs implement
the rest of the comparison operators.

Let me know your thoughts!

### CODE REVIEW

**Comment by jrobeson** [comment]
I should have mentioned this, but `__cmp__` (and `cmp()`)  are both gone in py3.

**Comment by sampsyo** [comment]
Cool! This looks like the right way to leave `cmp` behind. The decorator looks nice. Do things still work if we delete the `__cmp__` implementation?

**Comment by jrobeson** [comment]
oh, i thought i had done that.. lemme try that again!

**Comment by sampsyo** [comment]
Perfect! Thank you!

**Pull request merged**
