### PR TITLE
Media field

### PR DESCRIPTION
**Pull request by tigranl**
So, this is starting point for  https://github.com/beetbox/beets/issues/2511.

### CODE REVIEW

**Comment by sampsyo** [comment]
Thanks! Can you please also include some instructions showing how to reproduce the problem you're seeing? As I understand it, the issue is that the "Digital" media tag still isn't applied. Maybe you can include a transcript of a `beet -vv import` followed by a `beet list` command that shows the missing field?

**Comment by tigranl** [comment]
Here is `-vv` output (`beet -vv import -t`): https://gist.github.com/tigranl/352087d808ae413839741cd69c01192c
 `beet list`: 
```Aphex Twin - Syro - minipops 67 [120.2][source field mix]
Aphex Twin - Syro - XMAS_EVET10 [120][thanaton3 mix]
Aphex Twin - Syro - produk 29 [101]
Aphex Twin - Syro - 4 bit 9d api+e+6 [126.26]
Aphex Twin - Syro - 180db_ [130]
Aphex Twin - Syro - CIRCLONT6A [141.98][syrobonkus mix]
Aphex Twin - Syro - fz pseudotimestretch+e+3 [138.85]
Aphex Twin - Syro - CIRCLONT14 [152.97][shrymoming mix]
Aphex Twin - Syro - syro u473t8+e [141.98][piezoluminescence mix]
Aphex Twin - Syro - PAPAT4 [155][pineal mix]
Aphex Twin - Syro - s950tx16wasr10 [163.97][earth portal mix]
Aphex Twin - Syro - aisatsana [102]
```
I should have included config file:
```
directory: /Music
plugins: beatport
path:
    default: $albumartist - $album ($media) [$format]/%if{$disc_layer,$disc_layer/}$track - $title
```

**Comment by tigranl** [comment]
How should I use the `-f` key?

**Comment by tigranl** [comment]
Also, sorry for the delayed response.

**Comment by sampsyo** [comment]
No problem! It’s a nifty feature; please try playing around with it and reading the documentation to see what it can do. It’s our primary way of seeing the information on items in the beets database.

Specifically, try `-f ‘$media’` or similar to show that field.

**Comment by tigranl** [comment]
It actually shows media sources along with some blank lines.

**Comment by sampsyo** [comment]
Hmm; are you able to use more elaborate queries to find out which tracks have a medium and which ones are missing the medium? IIRC, we’re trying to get a reproducible test case to show how that field is not getting populated despite your change.

**Comment by tigranl** [comment]
I've found that all music data collected by beatport is missing. So, I think it isn't `autotag`'s  fault. There's something going on with beatport plugin.

**Comment by jtpavlock** [comment]
@tigranl are you still interested in getting this merged?

**Pull request closed without merging**
