### PR TITLE
missing changelog for #5153

### PR DESCRIPTION
**Pull request by Dr-Blank**
## Description

title

## To Do

- [x] Changelog. (Add an entry to `docs/changelog.rst` to the bottom of one of the lists near the top of the document.)

### CODE REVIEW

**Comment by Serene-Arc** [comment]
You can add these to the PR you've already opened. Please don't open a new PR for each small change, it makes it much harder to review. Just keep to the one PR and any changes you need or bug fixes can be pushed to that branch.

**Comment by Dr-Blank** [comment]
@Serene-Arc

> You can add these to the PR you've already opened. Please don't open a new PR for each small change, it makes it much harder to review. Just keep to the one PR and any changes you need or bug fixes can be pushed to that branch.


I apologize if my approach to submitting pull requests has caused any inconvenience. My intention was to streamline the review process and reduce lead time, not to create additional work.

In my academic and professional experience, I've learned that smaller, focused PRs can often lead to quicker reviews and less complex merges. They're easier to understand, verify, and can be reviewed simultaneously by different maintainers if they are separate and unrelated. This is the rationale behind my approach of submitting separate PRs for unrelated changes.


I also want to acknowledge the often thankless nature of maintaining open source projects. Your work is greatly appreciated, and I understand the significant effort that goes into reviewing and managing contributions.

However, I understand that every project has its own workflow and I respect that. I'm here to learn and contribute effectively to this project. If you prefer that I combine my changes into fewer PRs, I'm more than willing to adapt my approach.

Thank you for your guidance.

Best Regards

**Comment by Serene-Arc** [comment]
Thank you for the thoughtful response, but in this case you are totally right. I had a bit of brain short circuit and thought this was related to #5152, not #5153. That's on me, I didn't read that right. Yes, as #5153 is closed, it's great that you added a new PR and this definitely should not be part of #5152. I'll reopen and merge.

**Comment by Dr-Blank** [comment]
> Thank you for the thoughtful response, but in this case you are totally right. I had a bit of brain short circuit and thought this was related to #5152, not #5153. That's on me, I didn't read that right. Yes, as #5153 is closed, it's great that you added a new PR and this definitely should not be part of #5152. I'll reopen and merge.

I can now see how it might have been frustrating if it seemed like I opened a new PR just for adding a changelog, which could have been included in an existing open PR 😅.

In hindsight, I realize I should have made it clearer in the PR description that this changelog was for a previously closed PR, not an open one. This would have made the situation more clear to you and other maintainers.

I appreciate your time and the work you do maintaining this project. I'll make sure to provide more context in my future PRs to avoid any confusion.

**Comment by Serene-Arc** [comment]
Thanks for your understanding :) And don't worry, you did the right thing! Looking forwards to seeing your contributions

**Pull request merged**
