### PR TITLE
Edit README.rst structure

### PR DESCRIPTION
**Pull request by CampbellOwen**
- Add repository title
- Add `Features` header
- Move installation instructions to dedicated `Install` header
- Add wiki link to `Contributing` section

### CODE REVIEW

**Comment by sampsyo** [comment]
Hello! Can you please elaborate on why you want to see these changes made? Personally, the headings (especially the top one, with the name of the project) don’t really help much. And linking to the root of the GitHub wiki seems like it could be confusing. What’s your thinking here?

**Comment by CampbellOwen** [comment]
Most of my edits come down to, in my opinion, improving readability. I find that most people looking through github want to very quickly decide whether or not the project solves their problem or will be useful to them. A large part of this comes down to quick discoverability of features and information. Creating a header for each section allows people to quickly find what they are looking for and move on. 

For the title, while I agree that it's functionally not very useful as everyone knows what project they're on, it does wonders to creating a strong hierarchy. All the individual header feels disconnected when they're all at the same level. Creating a strong main header helps unify them. 

For the wiki link, I think it's important for allowing people to easily contribute. Most github users are conditioned to see a `Contributing` header on a project where they can find information about how to contribute. I didn't even know there was a wiki, let alone all the valuable information in it, until I randomly clicked that tab one day. Letting people know quickly and boldly where the information they need is located will make developers more likely to contribute.

This is, of course, just my opinion of ways to improve. I understand completely if you disagree - it's your project!

**Comment by sampsyo** [comment]
OK! To take some of the ideas here, let me suggest removing the H1 header, or at least lower-casing it and putting it after the badges, removing the “features” header (which I think is redundant), and linking to our “Hacking” page, which has the information you’re probably expecting.

Have you read our documentation? There’s a lot of similar information on there—spending some quality time with the docs might help inform where things should link and what should get highlighted, etc.

**Comment by CampbellOwen** [comment]
The reason I linked to the root of the wiki is because the links and descriptions in there do a great job introducing the different pages and where to look. Maybe I should still link to the root of the wiki to avoid duplicating the links and descriptions but make it more clear that it's not a link to an introduction? Otherwise I could link to the Hacking page solely and let users explore the rest of the wiki on their own. What's your opinion on that?

I agree with your other suggestions and will make the appropriate changes.

**Comment by sampsyo** [comment]
Thanks! Merged with some fiddling round.

**Pull request merged**
