### PR TITLE
Rich CLI Overhaul

### PR DESCRIPTION
**Pull request by tandy-1000**
## Description

Snejus overhauled Beets' UI, this PR attempts to mainline these changes.
https://github.com/beetbox/beets/issues/1593#issuecomment-1072069587

## To Do

- [ ] Improve the UI's usage of vertical space on import, e.g split things into various tables
- [ ] Add an option to only display the differing fields on imprort

### CODE REVIEW

**Comment by tandy-1000** [comment]
@sampsyo could you allow CI to run so I can test this?

**Comment by snejus** [comment]
@tandy-1000 Could you by any chance share some screenshots how it looks like now?

**Comment by tandy-1000** [comment]
Hey @snejus unfortunately I didn't get a chance to continue with this, I can have a look again this weekend potentially.
It would help to pair on this if that would work for you?

**Comment by snejus** [comment]
@tandy-1000 I'm so sorry, I haven't seen your message until now. I'd be very interested to see what you have done here

**Review by snejus — APPROVED** [review]

**Pull request closed without merging**
