### PR TITLE
bitesize to good first issue: Update changelog.rst

### PR DESCRIPTION
**Pull request by RollingStar**
- is the language too eager?
- do `:bug:` links work for gh discussions?

### CODE REVIEW

**Comment by snejus** [comment]
Hmm I'm wondering whether the package changelog is the best place for this kind of message.

What about sharing this on mastodon or the blog?

**Comment by RollingStar** [comment]
We can trim it back, but since it generates links on our github page I think it's as legitimate as docs changes.

**Comment by RollingStar** [comment]
The text could be truncated:  Changed `bitesize` label to `good first issue`. Our   [contribute](https://github.com/beetbox/beets/contribute) page is now  automatically populated with these issues.

**Comment by snejus** [comment]
> The text could be truncated: Changed `bitesize` label to `good first issue`. Our [contribute](https://github.com/beetbox/beets/contribute) page is now automatically populated with these issues.

Agree 🙂

**Review by snejus — APPROVED** [review]
Nice 👍🏼

**Pull request merged**
