### PR TITLE
Reorder shields and add new shields

### PR DESCRIPTION
**Pull request by jackwilsdon**
Reorder shields and add weekly PyPI downloads, GitHub issues and GitHub license shields.

### CODE REVIEW

**Comment by jackwilsdon** [comment]
So after taking a look at the new [`README.rst`][new readme] and it seems we've now got a case of badge/shield spam! Maybe this PR isn't such a good idea...

[new readme]: https://github.com/jackwilsdon/beets/blob/2a9305fba5b9d114fdc90cbbe507ea11f940d92f/README.rst

**Comment by sampsyo** [comment]
Always nice to pay some attention to these! I'm not super wild about the license (seems pretty easy to find) and issues (doesn't really matter, IMHO) badges, but the other ones seem cool.

**Comment by jackwilsdon** [comment]
I'll remove those and just keep the PyPI downloads one 👍.

**Comment by sampsyo** [comment]
Yay! Would you like to click the big green button here and on #1961, or shall I?

**Comment by jackwilsdon** [comment]
I'd love to 😁!

**Pull request merged**
