### PR TITLE
Always use syspath conversions

### PR DESCRIPTION
**Pull request by wisp3rwind**
## Description

As mentioned in https://github.com/beetbox/beets/pull/3670, our tests often don't use `syspath` conversions. Since the tests usually involve nice short file/directory names, there have not been any issues. However, on Python 3.5, which deprecated the bytes API on Windows, we get a lot of `DeprecationWarning`s like

```
C:\projects\beets\test\_common.py:186: DeprecationWarning: The Windows bytes API has been deprecated, use Unicode filenames instead
    if os.path.isdir(self.temp_dir):
```
see for example https://ci.appveyor.com/project/beetbox/beets/builds/34307016/job/7ju959dh8uyxwq0f

Deprecation never happened, since these interface became a new meaning with [PEP 529](https://www.python.org/dev/peps/pep-0529/). However, PEP 529 does not imply that we don't need `syspath` anymore, since `syspath` also the adds the magic prefix that allows long file names. Related: https://bugs.python.org/issue27731

This attempts to add the missing conversions (I searched the codebase for `os\.` and `shutil\.` to find these). In some cases, it appears that the actual code (i.e. not the tests) also lacked those conversions.

No need to review this yet, I mainly pushed this to run it on all CI platforms.

## To Do

- [ ] Observe behaviour on CI, fix issues.

### CODE REVIEW

**Comment by jtpavlock** [comment]
Is this something that would be a side effect of implementing https://github.com/beetbox/beets/issues/1409 or is this unrelated.

**Comment by wisp3rwind** [comment]
> Is this something that would be a side effect of implementing #1409 or is this unrelated.

As far as I understand it, #1409 would get rid of all/many of these explicit conversions. I'm not familiar with pathlib, though, so I can't really judge the extent of #1409. This PR is only about ensuring that our current path handling is always applied.

**Comment by sampsyo** [comment]
Wow; thank you for tracking all this down!! This is a heroic effort.

To weigh in briefly on the pathlib thing: it is also not clear to me how much pathlib solves the encoding issue. In particular, the library's documentation does not entirely explain how much it endeavors to preserve the bytes-oriented nature of paths on Unix, which is critical to reliably representing any path. It's possible it just Does The Right Thing, but it needs a deeper exploration to understand if so & how.

**Comment by wisp3rwind** [comment]
Not stale, I should really just have another look at it and mark the PR as ready.

**Comment by wisp3rwind** [comment]
Split the changes into more commits for easier review and rebased on master. The commit which should be looked at in particular is `add missing syspath conversions (3/3, beets)`. It changes beets' core and as such would have the largest fallout in case of incorrect path handling. Maybe I'll actually try to come up with tests to show that the old version of the respective code is indeed wrong.

**Comment by sampsyo** [comment]
Awesome! I looked over all the changes in that commit and didn't see any red flags there. Thank you for pursuing this!

**Comment by wisp3rwind** [comment]
Still not stale...

**Comment by wisp3rwind** [comment]
All commits here have now been moved to separate PRs:
- #4830
- #4848
- #4849
- #4850

**Pull request closed without merging**
