### PR TITLE
LOGO

### PR DESCRIPTION
**Pull request by foways**
ORIGINAL FILE (EDITABLE) https://drive.google.com/drive/folders/1Z60AO1oMiXXaN11EclIDS20REjvkJMBD?usp=sharing

### CODE REVIEW

**Comment by sampsyo** [comment]
Cool! Thanks for continuing to work on this! Linking to #2923 to preserve the paper trail. I'm still interested in hearing more feedback from the community about what they like and dislike about possible new branding.

**Comment by k-syusteem** [comment]
Well I am also happy to hear feedback and feedback from this community. Thanks @sampsyo

**Comment by ArchangeGabriel** [comment]
Well, I preferred model 2, but I can understand the confusion. Other than that the colours proposed here are nice, especially the gradient one.

**Comment by dosoe** [comment]
Hi! I also prefer model 2, model 1 feels like 'too many colors' but of course that's personal. All 3 are great though!

**Comment by daks** [comment]
2 & 3 for me, as multiple versions depending of background where is inserted

**Comment by tecosaur** [comment]
@foways could you try changing 2/3 to a beetroot-y colour? I plonked a beetroot-y coloured circle ontop of 3 and this is what I got (couldn't select individual shapes from svg in inkscape)

image

**Comment by jtpavlock** [comment]
If a new logo is still wanted, perhaps a poll on discourse is the best way to clear it up?

**Pull request closed without merging**
