### PR TITLE
Allow Discogs Plugin to respond during Singleton Import Mode

### PR DESCRIPTION
**Pull request by benrbray**
## Description

The purpose of this change is to allow the Discogs plugin to respond as expected during singleton import mode.  Before, the Discogs plugin did not run at all in singleton mode, leading to some confusion, as in #2544 .  Changes to the Discogs plugin include:

* Implemented `DiscogsPlugin.item_candidates`, allowing the plugin to provide track candidates during singleton import.
* Implemented `DiscogsPlugin.track_for_id`, allowing the plugin to respond to Id queries of the form `release_id/position`.  For example, `5240807/B2` refers to position B2 of release 5240807.

This change required a few minor changes to how plugin output is handled during import.  This change does not break existing plugin behavior, but allows plugins to return more information than they did before.

* `Plugin.tracks_for_id` and `Plugin.item_candidates` can now optionally return / yield a `TrackAlbumTuple`, containing both `TrackInfo` and `AlbumInfo` objects.  In the case of Discogs, this is useful because Discogs release IDs correspond to albums rather than individual songs.  As far as I can tell, it makes sense to associate the extra AlbumInfo with a track, even during singleton import mode.  (thereby making tracks modified in this manner non-singletons)
* Every `TrackMatch` candidate can optionally specify some `album_info`, with a default value of `None`.

## Use case

I would like to use beets to assign album information to a random assortment of songs which currently only have a title and artist.  The discogs database has information for most of these songs, while MusicBrainz does not.  The `--group-albums` options works OK for this use case, but presents albums as candidates rather than tracks themselves.  I prefer to use singleton mode to search for tracks directly, but still have the option to attach album info based on the track I've chosen.

## To Do

- [x] **Documentation.** I briefly searched, but didn't identify any appropriate places in the docs to mention these changes.  Feedback welcome.
- [x] **Changelog.** (Add an entry to `docs/changelog.rst` near the top of the document.)
- [x] **Tests.**  I added a few tests of the new Discogs plugin, but could not identify an appropriate way to test the other changes (other than the fact that existing plugin tests still pass).  Feedback welcome.

### CODE REVIEW

**Comment by benrbray** [comment]
There appears to be an issue with the Python 2.7 tests.  Something to do with string encodings?  Input appreciated, as I am not familiar with Python 2.  Although, since [Python 2.7] has [reached end-of-life](https://pythonclock.org/), are Python 2.7 tests needed?

**Comment by jtpavlock** [comment]
Hey! Thanks for tackling this. As far as the errors, what may help is converting the strings to unicode strings e.g. `u'string'` 

Also, it may make your life easier if you use `tox` to run the tests/linting locally. Check out our[ CONTRIBUTING.rst](https://github.com/beetbox/beets/blob/master/CONTRIBUTING.rst#running-the-tests) for more info.

**Comment by sampsyo** [comment]
Hi! Thanks so much for getting this started! The discogs thing will be very useful.

Is there any chance I could convince you to break this up into two separate PRs? The extension to the discogs plugin to work for singletons should be fairly modular and straightforward. The change to allow album-based matching of tracks (i.e., the new `TrackAlbumTuple`) is much more complex and will need to be treated with care because it touches multiple sensitive parts of the beets core. We will need to think about the right way to do this. If we can consider these changes separately, that would be extremely useful to both.

**Comment by benrbray** [comment]
Sure, I wouldn't mind splitting it into two PRs.  Is the best way to do that just to copy the changes into a new PR entirely, or is there a way to split this PR into multiple?

At the moment my additions to the discogs plugin rely on the ability of plugins to return an `TrackAlbumTuple`, since it seemed like the least invasive way to add that functionality.  Perhaps the same thing could be accomplished by instead changing how plugins interact with the import session, but I wasn't able to figure out a way to make the Discogs fix without touching files in the main beets repo.  Suggestions are welcome!

Do you think it's possible for the Discogs plugin to attach album info during a singleton import session?  Or do you think it will have to wait until after deciding which changes should be made to the plugin system?

**Comment by sampsyo** [comment]
Great. If possible, I think the best place to start would be by _just_ implementing `item_candidates` in Discogs, and—again, if possible—just providing TrackInfo for individual tracks. Even if that's missing some information, that will provide a good foundation for understanding where we need to go from there.

There's no magic GitHub way to split a single PR into multiple, unfortunately, but maybe a good place to start here would be by just removing the core changes for now in this branch (and possibly opening a new PR with them based on this one).

**Pull request closed without merging**
