### PR TITLE
added beets-popularity plugin

### PR DESCRIPTION
**Pull request by abba23**

### CODE REVIEW

**Comment by Kraymer** [comment]
Files are missing but I really like the idea behind this plugin ! :hurtrealbad:

**Comment by abba23** [comment]
What files are you missing? I thought a reference to the github page in the docs was enough for external plugins.

**Comment by sampsyo** [comment]
Awesome; thank you!

**Comment by Kraymer** [comment]
@abba23 miscomprehension from my part. because of the PR title, I expected it to contain both code and docs. but it seems the code itself was pushed in another PR.

**Comment by abba23** [comment]
@Kraymer I think you're still misunderstanding. There wasn't a second PR. This is literally just a link in the 'Other Plugins' (for plugins made by the community) section of the docs to the plugin's repository. No code was or was supposed to be pulled into the beets repository.

**Pull request merged**
