### PR TITLE
ftintitle: Add option: `broad`.

### PR DESCRIPTION
**Pull request by Freso**
Determines how lenient ftintitle should be when catching "feat." strings. If set to False, it will not catch "with", "&", "vs", etc. The exact strings are defined in beets/plugins.py's `feat_tokens()`.

Defaults to current behaviour if not set.

See also #1184.

### CODE REVIEW

**Comment by sampsyo** [comment]
Good point. I think the most intuitive situation from the user's perspective would be for the configuration to be per-plugin; i.e., this would go under the `ftintitle:` section at the very least. Does that mean we only need one option for this plugin, or would we still need two?

**Comment by Kraymer** [comment]
A reason why it hasn't been merged yet ? :mag: 
Configurable tokens list can be done in another PR.

**Comment by sampsyo** [comment]
I would love to do a configurable token list *instead* of the `broad` option. The single flag is definitely simpler, but if we have the former it might be confusing to have the latter also. I can anticipate people wanting to change this, so better to preemptively supply that.

**Comment by Kraymer** [comment]
Ah yes, I didn't catch that it was *instead*.

**Comment by jtpavlock** [comment]
Closing as it seems to be abandoned by the original author. Also perhaps a niche case as it hasn't seen any mention (including #1184) in over 5 years...

**Pull request closed without merging**
