### PR TITLE
docs/plugins/discogs.rst: Update plugin documentation

### PR DESCRIPTION
**Pull request by allesmi**
I have found that the documentation of DiscogsPlugin does not mention the 'source_weight' option. This PR adds that information:

Add Configuration section and describe the 'source_weight' option.

### CODE REVIEW

**Comment by jackwilsdon** [comment]
Thanks for this change! It seems like this is missing from `docs/plugins/beatport.rst` too - would you mind adding it in there as well?

**Comment by allesmi** [comment]
I can certainly add it to the documentation of the beatport plugin as well.
But in the future more plugins might follow and we risk that documentation
of plugins drifts apart.

The only mention of this option in the docs is in the SpotifyPlugin but it
should apply to every plugin that provides a source of metadata. Is there a
central place in the docs to mention this?

Issues #3355 and #3371 extracted a lot of code into the superclass
MetadataSourcePlugin. Documentation could follow and describe
'source_weight' in only one place in the docs. What do you think?

**Comment by sampsyo** [comment]
Good question. It would be nice to centralize this information, especially because it's a pretty specialized thing that most people won't want to worry about—and if you do, then you'll worry about it _in concert_ between multiple plugins, not just by configuring a single plugin at a time.

I don't have a perfect idea about where that would be, however. Maybe on the main page about using plugins in general? I'd be open to suggestions.

**Comment by allesmi** [comment]
How about a section under Using Plugins in docs/plugins/index.rst that describes configuration options common to all plugins that provide a metadata source. Then, for each individual plugin a section about configuration that starts with a reference to first section followed by additional configurations.

I think of something like this:

> ### Configuration
> 
> This plugin provides a source of metadata and shares configuration options as described in [Using MetadataSourcePlugins](link-to-metadata-source-plugins). In addition, it provides the following configuration options:
> - **Option A**: Description of option A
> - **Option B**: Description of option B.

**Comment by sampsyo** [comment]
That's a great idea! Yeah, linking to the section seems very good.

**Comment by allesmi** [comment]
I have added the description of the source_weight option to docs/plugins/index.rst and updated the plugin documentation with references back to that description for beatport, deezer, discogs, and spotify.

**Comment by sampsyo** [comment]
This looks lovely! Thank you!!!

**Pull request merged**
