### PR TITLE
advancedrewrite: Support simple syntax and improve advanced syntax

### PR DESCRIPTION
**Pull request by Maxr1998**
## Description

Rework the `advancedrewrite` plugin as discussed in #5002.

## Checklist

- [X] Update documentation
- [x] Write tests
- [ ] Add changelog

### CODE REVIEW

**Comment by Maxr1998** [comment]
Should be ready for review. Only need to add a changelog now, but I'll do that once the changes themselves are reviewed.

**Review by sampsyo — APPROVED** [review]
Awesome; really nice work on this! The new mode looks great to me. :clap:

**Comment by sampsyo** [comment]
(I actually think this is ready to merge whenever you like, even without a changelog entry, since the plugin itself is new.)

**Comment by Maxr1998** [comment]
Fine for me, the original changelog should already cover this plugin fairly well!

**Comment by sampsyo** [comment]
Wonderful!

**Pull request merged**
