### PR TITLE
Make `ignore_data_tracks` `yes` by default

### PR DESCRIPTION
**Pull request by fortes**
Follow up for https://github.com/beetbox/beets/pull/3021

### CODE REVIEW

**Comment by sampsyo** [comment]
Hmm, looks like one test is failing—maybe it just needs its expectations updated?

**Comment by fortes** [comment]
> Hmm, looks like one test is failing—maybe it just needs its expectations updated?

@sampsyo I feel like an idiot, but I'm not sure why those two tests are failing. There seems to be some interaction between the tests, because I can make unrelated tests fail depending on my changes within these data track tests. I kinda suck at python, so I'm not quite sure what I'm doing wrong here, any chance you can pull down the branch and take a quick look?

**Comment by sampsyo** [comment]
Sure thing; I'll take a look tomorrow.

**Comment by sampsyo** [comment]
Hmm… correct me if I'm wrong, but I think the failing test should logically fail. I only see one test failing (on my machine and on Travis), for starters:
https://travis-ci.org/beetbox/beets/jobs/424390152#L1102

That test looks like this:

```py
def test_no_skip_video_data_tracks_if_configured(self):
    config['match']['ignore_video_tracks'] = False
    tracks = [self._make_track('TITLE ONE', 'ID ONE', 100.0 * 1000.0),
              self._make_track('TITLE TWO', 'ID TWO', 200.0 * 1000.0)]
    data_tracks = [self._make_track('TITLE VIDEO', 'ID VIDEO',
                                    100.0 * 1000.0, False, True)]
    release = self._make_release(tracks=tracks, data_tracks=data_tracks)
    d = mb.album_info(release)
    self.assertEqual(len(d.tracks), 3)
```

In other words, it configures beets to *not* ignore video tracks. But data tracks are still ignored. Then it makes a release with a track that's *both video and data*. It asserts that this track should not be ignore, but in fact it should—because it's a data track! That's certainly what mb.py does:

```py
if ('data-track-list' in medium
        and not config['match']['ignore_data_tracks']):
    all_tracks += medium['data-track-list']
```

All data track lists are ignored when data tracks are ignored, regardless of whether they're video or audio. Does that make sense?

**Comment by fortes** [comment]
@sampsyo Yup, you're right. Just pushed a fix. In my multitasking-addled mind I managed to misread the `skip_video` tests as `skip_audio`, and was looking at the wrong tests.

This does, however, bring up something I did not think about, this new setting overlaps with `ignore_video_tracks` -- should we be combining the config here?

**Comment by sampsyo** [comment]
Great! I did the same thing a couple of times when reading the code.

Hmm—is it the case that *all* video tracks (in MB, at least) are also data tracks? That does seem like something that *could* be combined, but I actually don't have any creative proposals for how to do so—it still seems like you might want to allow data tracks but not video tracks, which requires both settings to exist. Hmm…

**Comment by fortes** [comment]
Yeah, I don't know that there's a great answer. My quick take is that defaults matter, and ignoring video + data seems like a good default. Folks that want something different will have to change config.

**Comment by sampsyo** [comment]
Yep, sounds right to me.

**Pull request merged**
