### PR TITLE
Attempt adding bs1770gain to .travis.yml

### PR DESCRIPTION
**Pull request by jrobeson**
This might not even work, but let's find out

### CODE REVIEW

**Comment by jrobeson** [comment]
ah yeah, it has to be safelisted. I guess we need to wait til we try migrating to trusty.

**Comment by jackwilsdon** [comment]
We could try opening an issue on [travis-ci/apt-package-whitelist](https://github.com/travis-ci/apt-package-whitelist) asking for the package?

**Comment by sampsyo** [comment]
Yeah, they're pretty responsive there—most packages get added to the whitelist immediately.

**Comment by jrobeson** [comment]
i was wrong about the safelisting, it's not even packages in trusty or precise

**Comment by jrobeson** [comment]
i couldn't even find a ppa :(

**Comment by jackwilsdon** [comment]
We might have to end up pulling the binary directly with `wget` and just adding it to the `PATH`.

e.g.

```YAML
install:
    - wget http://downloads.sourceforge.net/project/bs1770gain/bs1770gain/0.4.9/bs1770gain-0.4.9-linux32.tar.bz2 -P /tmp
    - tar -xjvf /tmp/bs1770gain-0.4.9-linux32.tar.bz2 -C /tmp
    - export PATH=$PATH:/tmp/bs1770gain-0.4.9/bin
```

I don't know if all of the dependencies are there but it should work 😄.

**Comment by jrobeson** [comment]
we need to make a note of trying to replicate this stuff with appveyor. Our config is (or will be) woefully incomplete. I feel bad about it, but not yet bad enough to spend time on it :(.  It'd be really nice to have someone familiar with windows/appveyor take care of it.

**Comment by jrobeson** [comment]
@jackwilsdon : can you add this that comment to https://github.com/beetbox/beets/issues/2109 since we are tracking that there (and this PR is closed)

**Pull request closed without merging**
