### PR TITLE
Web audio

### PR DESCRIPTION
**Pull request by webpro**
See #986. This is the generic idea. Plenty of improvements possible, but I've just tried to stick with the current setup for the client-side application as much as possible.

Note that I've not considered any performance and (cross-browser) compatibility issues, so this should not be merged right away. I can do this later on, but wanted you/others to have a look at what I have now.

Let's discuss the idea, issues, and directions.

### CODE REVIEW

**Comment by magne4000** [comment]
Hi, I'm working on a [web player (festival)](https://github.com/magne4000/festival) for several years now, and I would like to be able to use beets as the library.
I developed a subset of the [subsonic API](https://github.com/magne4000/festival/tree/master/api) that, I think, could be easily ported to beets firstly (at least a piece of it).
I'll give it a shot.

**Comment by sampsyo** [comment]
Very nice! This player looks great. Maybe we should chat about the upcoming AURA API?

**Comment by magne4000** [comment]
@sampsyo You can find me as Magne` on Freenode

**Comment by magne4000** [comment]
Made a PR #2321

**Comment by webpro** [comment]
Sorry guys, no more activity (from my end), so I'm closing this issue.

**Pull request closed without merging**
