### PR TITLE
Fix fetchart hardcoding the image extension

### LINKED ISSUE #2053: fetchart: Use the right filename extension according to the image's MIME type
This is something I noticed today when using fetchart with the fanarttv plugin - one random albumart file it downloaded was actually a PNG file, not a JPG. This wasn't fetchart's fault - I verified that the source image was indeed a PNG from fanarttv despite having the .jpg extension.

But, I think a nice feature would be to include some form of image validty check and perhaps offer to convert to the image to the desired default format.

### PR DESCRIPTION
**Pull request by wordofglass**
When downloading files from any source, fetchart used to hardcode the extension to `jpg` but also support `png` images. As there are misnamed (i.e. with a `jpg` extension) files in the wild with a correct `Content-Type` set, use that to determine the extension.

Missing
- [x] Changelog
- [ ] Test on real-world data
- [x] https://github.com/beetbox/beets/commit/d9974081a77573c9045dbf5e7abc48bf1e276686 -> check whether the proxy returns correct `Content-Type`s -> It does.

EDIT: doesn't fix #2053, see there. This PR fixes our part of the issue, the image header based correction to work around the server-side problem is split out into a new PR as its fate is not as clear: #2072.

### CODE REVIEW

**Comment by sampsyo** [comment]
Hey! Awesome! Thank you for looking into this!

It looks like this PR does two different things:

- Get the download extension right based on the MIME type.
- Use `imghdr` to validate images when adding them to the database.

The first is actually enough to fix #2053, where the MIME type is correct and we're just ignoring it in `fetchart`.

I'm a little less confident in the second change, which incurs a second access to every file when adding album art, even though the common case is that everything's in order. How would you feel about *just* merging the first change, and leaving the second case GIGO for now? We can revisit type validation separately.

**Comment by wordofglass** [comment]
The problem is https://github.com/beetbox/beets/issues/2053#issuecomment-227388016. You may be right about the second change being overkill; I don't know about the performance impact.

I'll merge the first change after adding the changelog, and have a look how I could move the `imghdr` check only to the fanart source. Although as mentioned in the issue, the right thing would be to report this upstream get the API fixed in the first place.

**Comment by sampsyo** [comment]
Aha! I'm sorry for not reading the other thread carefully. Let's see how the investigation goes.

In any case, the MIME-to-extension thing is a shoo-in; we can merge that regardless of the fanart.tv misbehavior.

**Comment by wordofglass** [comment]
Force-pushed to move the `imghdr` part to a new PR, updated the initial post.

**Comment by sampsyo** [comment]
Looks perfect; thank you! :tada: And thanks for writing a cogent changelog entry.

**Pull request merged**
