### PR TITLE
Use beets API key for lastimport plugin.

### PR DESCRIPTION
**Pull request by SJoshBrown**
#1859 

Hi, just found this project and was poking around. Figured this was a pretty easy fix to get started.

This worked in my testing and I hope it solves the issue. Please let me know if there is something I should be doing differently in regards to branching and pull requests. I'm pretty new to this.

### CODE REVIEW

**Comment by evaryont** [comment]
I think it would be wise to include support for a user's configured LastFM API key. I don't think it's likely, but it's entirely possible that the key could be revoked. Being able to support a configuration value means that users can at least get it working until the next version with an updated key is released.

**Comment by sampsyo** [comment]
Awesome! Thanks for dropping by!

As mentioned above, if you just drop that value in here instead, in the config defaults: https://github.com/beetbox/beets/blob/master/beetsplug/lastimport.py#L35

Then the key will be overridable by the configuration. Nifty.

And then, if you wouldn't mind adding a short Changelog entry, this should be ready to merge!

**Comment by SJoshBrown** [comment]
Thanks! I made the suggested changes. Let me know if anything else is needed before merging.

**Comment by sampsyo** [comment]
Fantastic! :sparkles: Thanks for the quick fix.

**Pull request merged**
