### PR TITLE
Add gstreamer deps to travis config

### PR DESCRIPTION
**Pull request by jrobeson**
[appveyor skip]

### CODE REVIEW

**Comment by jackwilsdon** [comment]
Hmm, it looks like that didn't work?

```
test.test_replaygain.ReplayGainGstCliTest.test_cli_saves_album_gain_to_file: 'gstreamer cannot be found'
test.test_replaygain.ReplayGainGstCliTest.test_cli_saves_track_gain: 'gstreamer cannot be found'
test.test_replaygain.ReplayGainGstCliTest.test_cli_skips_calculated_tracks: 'gstreamer cannot be found'
```

**Comment by jrobeson** [comment]
yeah it's not complete, because tox doesn't know about it. I need to install the gobject introspection python libs, but they aren't installable via pypi

**Comment by jrobeson** [comment]
Oh, i should mention that there is no gstreamer package, only the libraries and plugins.

**Comment by jrobeson** [comment]
@jackwilsdon :  We have to install them in the virtualenv somehow like one of these methods http://stackoverflow.com/questions/26678457/how-do-i-install-python3-gi-within-virtualenv

**Comment by jrobeson** [comment]
using --system-site-packages is the easiest way to accomplish it, but that isn't what we want is it?

**Comment by jackwilsdon** [comment]
Is there a reason you don't want to put them in `tox.ini`?

**Comment by jrobeson** [comment]
only pygobject is available via pip (and that's not even yet in a released version), and pycairo one of it's deps is not.

**Comment by jackwilsdon** [comment]
Ah, I see. Well from [this SO answer](http://stackoverflow.com/a/19459977/2664985), we might be able to use site packages and force tox to "overinstall" any packages we depend on? It's a horrible hack IMO but we might have to do it.

The only issue I can see is that if we depend on something that is pre-installed on the system (i.e. the site) but we don't add it to tox, causing some unexpected failures on systems without the package.

Try adding this to `tox.ini` and seeing what it does:

```INI
install_command = pip install -U {opts} {packages}
sitepackages = True
```

CCing @sampsyo to get his opinion. 😄

**Comment by jrobeson** [comment]
@jackwilsdon:  two concerns on that one.

I read on one stackoverflow post (I don't have the link handy anymore) that due to the ordering of `sys.path` that the packages wouldn't get used on that case, but maybe that was for an older version of pip or tox.

The other is is about distribution packages. If the goal is to get distributions to package beets, then shouldn't we be testing against the versions  of python packages included in the distributions too?

**Comment by jackwilsdon** [comment]
> I read on one stackoverflow post (I don't have the link handy anymore) that due to the ordering of sys.path that the packages wouldn't get used on that case, but maybe that was for an older version of pip or tox.

I'm not quite sure if this is true, as it seems virtualenv does some weird things with the path order:

```Bash
$ python -c 'import sys; print("\n".join(sys.path))'

/private/tmp/venv/lib/python27.zip
/private/tmp/venv/lib/python2.7
/private/tmp/venv/lib/python2.7/plat-darwin
/private/tmp/venv/lib/python2.7/plat-mac
/private/tmp/venv/lib/python2.7/plat-mac/lib-scriptpackages
/private/tmp/venv/lib/python2.7/lib-tk
/private/tmp/venv/lib/python2.7/lib-old
/private/tmp/venv/lib/python2.7/lib-dynload
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
/private/tmp/venv/lib/python2.7/site-packages
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
```

Note that even though some of my system Python's files are above `site-packages`, it looks like the virtualenv's `site-packages` is still above the system `site-packages`.

> The other is is about distribution packages. If the goal is to get distributions to package beets, then shouldn't we be testing against the versions of python packages included in the distributions too?

What do you mean by this? Aren't we testing against 27, 34 and 35?

**Comment by jrobeson** [comment]
I don't mean python versions, but python library package versions.  Since python is so flexible, it'd be easy for us to use a function/method in one of our dependencies that doesn't exist in the versions packaged in distributions (but is installed by pip) and then, not manifest an error/warning until runtime.

Distribution packages don't always run their various packaged program test suites, and they certainly don't do much more than that unless they actively use the package daily.

**Comment by jackwilsdon** [comment]
Well in theory we depend on everything we'll ever need in our `setup.py` (and the versions needed), so I don't see the issue?

**Comment by jrobeson** [comment]
we only set minimum versions at most, no maximums.

**Comment by jackwilsdon** [comment]
Ah, makes sense. Well it seems the sitepackages hack hasn't worked and it seems like a terrible idea anyway. I'm honestly not sure what to do in this situation 😕.

**Comment by jrobeson** [comment]
Perhaps we actually need another option to always run against site-packages and no pip

**Comment by jrobeson** [comment]
oh, as far as the hack went, it actually worked for me locally on Fedora, so maybe I'm just missing another dep.

```sh
env NOSE_SHOW_SKIPPED=1 tox -e py27-test test/test_replaygain.py
GLOB sdist-make: /home/johnny/src/beetstmp/setup.py
py27-test inst-nodeps: /home/johnny/src/beetstmp/.tox/dist/beets-1.4.0.zip
py27-test installed: alabaster==0.7.8,ansible==2.1.0.0,apsw==3.12.2.post1,arandr==0.1.7.1,argcomplete==1.0.0,Babel==2.3.4,Beaker==1.5.4,BeautifulSoup==3.2.1,beautifulsoup4==4.4.1,beets==1.4.0,bzr==2.6.0,CDDB==1.4,cffi==1.4.1,characteristic==14.3.0,chardet==2.2.1,CherryPy==3.5.0,click==6.6,codecov==2.0.3,colorama==0.3.5,cookies==2.2.1,copr==1.70,copr-cli==1.51,coverage==4.1,cryptography==1.3.1,cssselect==0.9.1,cssutils==1.0.1,csvkit==0.9.0,cycler==0.9.0,dbf==0.94.3,deluge==1.3.12,discogs-client==2.2.1,dnspython==1.12.0,dockerfile-parse==0.0.5,docutils==0.12,ecdsa==0.13,enum34==1.1.6,fedpkg==1.24,feedparser==5.2.0,flake8==2.5.5,-e git+git@github.com:beetbox/beets.git@498f3e4fcd9fc3c0eab8eb837d86395e9dfa5dd2#egg=Flask,funcsigs==1.0.2,functools32==3.2.3.post2,futures==3.0.5,Genshi==0.7,GeoIP==1.3.2,gitdb==0.6.4,GitPython==1.0.1,greenlet==0.4.10,hgapi==1.7.2,html5lib==0.999,httplib2==0.9.2,idna==2.0,iniparse==0.4,intelhex==2.0,ipaddress==1.0.16,itsdangerous==0.24,jdcal==1.0,jedi==0.9.0,jellyfish==0.5.6,Jinja2==2.8,jsonpointer==1.10,jsonschema==2.5.1,keyring==5.0,kitchen==1.2.4,liveusb-creator==3.14.2,lockfile==0.11.0,lxml==3.4.4,Magic-file-extensions==0.2,Mako==1.0.3,MarkupSafe==0.23,marshmallow==2.2.1,matplotlib==1.5.2rc2,mbed-test-wrapper==0.0.2,mccabe==0.2.1,mechanize==0.2.5,meld==3.16.1,mercurial==3.7.3,mock==2.0.0,msgpack-python==0.4.7,munch==2.0.4,munkres==1.0.8,musicbrainzngs==0.6,mutagen==1.33.2,ndg-httpsclient==0.4.0,neovim==0.1.9,netifaces==0.10.4,nose==1.3.7,nose-show-skipped==0.1,numpy==1.11.0,oauthlib==1.0.3,odfpy==0.9.6,openpyxl==2.2.0,ordered-set==2.0.0,osbs-client==0.24,packagedb-cli==2.13,pants==1.0.1,paramiko==1.16.0,Paste==2.0.2,pathlib==1.0.1,pbr==1.10.0,pep8==1.6.2,pex==0.9.0,Pillow==3.2.0,pluggy==0.3.1,ply==3.8,project-generator==0.8.2,project-generator-definitions==0.2.2,psutil==3.2.1,py==1.4.31,pyasn1==0.1.9,pyasn1-modules==0.0.8,PyAudio==0.2.3,pycparser==2.14,pycrypto==2.6.1,pycryptopp==0.6.0.1206569328141510525648634803928199668821045408958,pycurl==7.43.0,pyelftools==0.23,pyflakes==1.2.3,pygame==1.9.2a0,PyGithub==1.26.0,Pygments==2.1.3,pygobject==3.20.1,pygpgme==0.3,pyinotify==0.9.6,PyJWT==1.4.0,pylast==1.6.0,pyliblzma==0.5.3,pyOCD==0.6.1,pyOpenSSL==16.0.0,pyparsing==2.1.5,pyparted==3.10.7,pyquery==1.2.8,pyserial==3.0.1,PySocks==1.5.6,pytest==2.9.2,python-bugzilla==1.2.2,python-dateutil==2.2,python-fedora==0.8.0,python-keyczar==0.71rc0,python-libtorrent==1.0.9,python-mpd2==0.5.5,python-musicbrainz2==0.7.0,pytz==2015.7,pyusb==1.0.0b2,pywatchman==1.3.0,pyxattr==0.5.3,pyxdg==0.25,PyYAML==3.11,quodlibet==3.6.2,rarfile==2.8,rencode==1.0.3,requests==2.10.0,requests-toolbelt==0.6.2,responses==0.5.1,rpkg==1.45,rpm-python==4.13.0rc1,semantic-version==2.4.2,service-identity==14.0.0,setproctitle==1.1.9,simplejson==3.5.3,six==1.10.0,smmap==0.9.0,snowballstemmer==1.2.0,Sphinx==1.3.1,sphinx-rtd-theme==0.1.9,SQLAlchemy==1.0.13,Tempita==0.5.1,tox==2.3.1,trollius==2.1,Twisted==15.4.0,unicode-nazi==1.1,Unidecode==0.4.19,urlgrabber==3.10.1,urllib3==1.15.1,valinor==0.0.12,virtualenv==14.0.6,Werkzeug==0.11.10,xlrd==0.9.3,xmltodict==0.9.2,yotta==0.16.4,yum-metadata-parser==1.1.4,zenmap==7.12,zope.event==4.2.0,zope.interface==4.1.3
py27-test runtests: PYTHONHASHSEED='3599282187'
py27-test runtests: commands[0] | python -m nose test/test_replaygain.py

----------------------------------------------------------------------
Ran 9 tests in 0.787s

OK (SKIP=3)

----------------------------------------------------------------------------------------------------------
test.test_replaygain.ReplayGainLdnsCliTest.test_cli_saves_album_gain_to_file: 'bs1770gain cannot be found'
test.test_replaygain.ReplayGainLdnsCliTest.test_cli_saves_track_gain: 'bs1770gain cannot be found'
test.test_replaygain.ReplayGainLdnsCliTest.test_cli_skips_calculated_tracks: 'bs1770gain cannot be found'

**Comment by jackwilsdon** [comment]
Well it seems to be a relatively simple check for GStreamer, so maybe there's something funky going on with Travis?

```Python
try:
    import gi
    gi.require_version('Gst', '1.0')
    GST_AVAILABLE = True
except (ImportError, ValueError):
    GST_AVAILABLE = False
```

**Comment by jrobeson** [comment]
I'm not sure how to prove that one way or the other without installing a trusty VM.

**Comment by jrobeson** [comment]
It is now clear why it fails on travis!   Debian (and thus Ubuntu) ustore apt installable packages in `dist-packages`, not `site-packages`.  That's why it worked for me on Fedora! Of course, this leads us back to the original problem :)

**Comment by jrobeson** [comment]
I'm dropping the tox modifications and just adding the gstreamer deps. I'll see if #2183 can handle it. If not I'll add that in a separate PR.

**Pull request merged**
