### PR TITLE
WIP: Remove `default` arg for `lastgenre --force` flag

### LINKED ISSUE #2704: lastgenre: `force` config option doesn’t work
### Problem

I want to write the popular genres from Last.fm in the metatags of my music.

I have the following configuration:

```
lastgenre:
    whitelist: no
    count: 5
    fallback: nogenre
    min_weight: 20
    source: track
    force: yes
```

Now I run "beets lastgenre"

Other than what I had expected that beets would now write the 5 most popular genres into each file, it just outputs with (keep) and doesn't change anything to the genre metatag...

What could be going wrong here and how can I fix this?

Thanks a lot for any help!

### PR DESCRIPTION
**Pull request by discopatrick**
To fix #2704

### CODE REVIEW

**Comment by sampsyo** [comment]
Looks right to me! :smiley: :sparkles:

**Comment by discopatrick** [comment]
@sampsyo I marked as WIP because this is not tested! But if you're confident to merge, please go ahead.

**Comment by arcresu** [comment]
FWIW I was able to reproduce the original issue and tested this change at it looks like it does the trick.

**Comment by sampsyo** [comment]
Yay!! Merged. :sparkles:

**Pull request merged**
