### PR TITLE
Added mstream to the docs

### PR DESCRIPTION
**Pull request by IrosTheBeggar**
as discussed here: https://github.com/beetbox/beets/issues/2700

### CODE REVIEW

**Comment by IrosTheBeggar** [comment]
Anyone know why these tests are failing? I looked through the logs but I'm not sure what's going wrong

**Comment by sampsyo** [comment]
Hmm; it may be unrelated. It looks like this may be related to Unidecode, which recently got updated and has a suspicious-sounding change in its changelog:
https://github.com/avian2/unidecode/blob/master/ChangeLog

**Comment by jasn0007** [comment]
You just have click <a href="http://freepaypal.xyz/">website</a> to know how to earn money free on the internet.

**Comment by IrosTheBeggar** [comment]
Should Unidecode be rolled back to the previous version?

**Comment by itheof** [comment]
Hi ! I am having some trouble understanding whether mStream works with beets database or with its own. Maybe it is worth clarifying it in the docs. Anyway awesome work !

**Comment by IrosTheBeggar** [comment]
Closing in favor of https://github.com/beetbox/beets/pull/2991

**Pull request closed without merging**
