### PR TITLE
Fix the version error in the release workflow

### PR DESCRIPTION
**Pull request by Serene-Arc**
This hopefully fixes the issue we experienced where the version was not incremented before the package was built. This should make sure that it works correctly.

### CODE REVIEW

**Comment by Serene-Arc** [comment]
Hey @snejus if you wanna push your markdown code to this branch, we can get it all working and fixed in one PR.

**Comment by snejus** [comment]
Cool, will do! To be clear, do you mean the code that converts `rst` changelog to `md`?

**Comment by Serene-Arc** [comment]
Yes, the part I removed. I removed a bunch of stuff but if you actually have it working, then we might as well add it back in. It'll be a bit of a pain to make it so it's output as part of the action (which is why I removed it in the first place) but it should be manageable.

**Comment by snejus** [comment]
@Serene-Arc thanks for the confirmation - this makes sense. I don't think this should pose too many issues - let me get on it.

**Comment by snejus** [comment]
@Serene-Arc See the commits I have just pushed

**Comment by snejus** [comment]
See the resulting changelog for `2.0.0` below

With this release, beets now requires Python 3.7 or later (it removes support for Python 3.6).

### Major new features

- The beets importer UI received a major overhaul. Several new configuration options are available for customizing layout and colors: `ui_options`. :bug: (#3721) :bug: (#5028)

### New features

- --from-logfile now parses log files using a UTF-8 encoding in `beets/beets/ui/commands.py`. :bug: (#4693)
- A new configuration option, `duplicate_keys`, lets you change which fields the beets importer uses to identify duplicates. :bug: (#1133) :bug: (#4199)
- A new configuration option, `duplicate_verbose_prompt`, allows changing how duplicates are presented during import. :bug: `4866`
- Add `%sunique{} <sunique>` template to disambiguate between singletons. :bug: (#4438)
- Add `exact match <exact-match>` queries, using the prefixes `=` and `=~`. :bug: (#4251)
- Add a new `import.ignored_alias_types` config option to allow for specific alias types to be skipped over when importing items/albums.
- Add query prefixes `=` and `~`.
- Add support for `artists` and `albumartists` multi-valued tags. :bug: (#505)
- Add support for `barcode` field. :bug: (#3172)
- Add the item fields `bitrate_mode`, `encoder_info` and `encoder_settings`.
- Added `spotify_updated` field to track when the information was last updated.
- Added a `-P` (or `--disable-plugins`) flag to specify one/multiple plugin(s) to be disabled at startup.
- Added additional error handling for `spotify` plugin. :bug: (#4686)
- Added option to specify a URL in the `embedart` plugin. :bug: (#83)
- Added option to use `cover_art_url` as an album art source in the `fetchart` plugin. :bug: (#4707)
- Command **`config`**: Prefer editor from `VISUAL` environment variable over `EDITOR`.
- Command **`import`**: Expose `import.incremental_skip_later` as CLI option.
- Command **`import`**: Expose import.quiet_fallback as CLI option.
- Command **`list`** `singleton:1` and `singleton:0` can now alternatively be used in queries, same as `comp`
- Command **`list`** `singleton:true` queries have been made faster
- Command **`list`** lookups using the pattern operator `::` have been made faster
- Command **`update`**: added `` `-e ``\` flag for excluding fields from being updated.
- Create the parental directories for database if they do not exist. :bug: (#3808) :bug: (#4327)
- Fetch the `release_group_title` field from MusicBrainz. :bug: `4809`
- Fetchart: Use the right field (`spotify_album_id`) to obtain the Spotify album id :bug: (#4803)
- Make ArtResizer work with `PIL`/`pillow` 10.0.0 removals. :bug: (#4869)
- Plugin **`advancedrewrite`**: Add an advanced version of the `rewrite` plugin which allows to replace fields based on a given library query.
- Plugin **`autobpm`**: Add the `autobpm` plugin which uses Librosa to calculate the BPM of the audio. :bug: (#3856)
- Plugin **`bareasc`** lookups have been made faster
- Plugin **`convert`**: Add a new `auto_keep` option that automatically converts files but keeps the *originals* in the library. :bug: (#1840) :bug: (#4302)
- Plugin **`convert`**: Add support for generating m3u8 playlists together with converted media files. :bug: (#4373)
- Plugin **`convert`**: Don't treat WAVE (`.wav`) files as lossy anymore when using the `never_convert_lossy_files` option. They will get transcoded like the other lossless formats.
- Plugin **`deezer`**: Import rank and other attributes from Deezer during import and add a function to update the rank of existing items. :bug: (#4841)
- Plugin **`discogs`**: Add support for applying album information on singleton imports. :bug: `4716`
- Plugin **`discogs`**: Check for compliant discogs_client module.
- Plugin **`discogs`**: Implement item_candidates for matching singletons.
- Plugin **`discogs`**: Permit appending style to genre.
- Plugin **`discogs`**: supply a value for the `cover_art_url` attribute, for use by `fetchart`. :bug: (#429)
- Plugin **`edit`**: Prefer editor from `VISUAL` environment variable over `EDITOR`.
- Plugin **`embyupdate`**: Add handling for private users by adding `userid` config option. :bug: (#4402)
- Plugin **`fetchart`**: Fix the error with CoverArtArchive where no cover would be found when the `maxwidth` option matches a pre-sized thumbnail size, but no thumbnail is provided by CAA. We now fallback to the raw image.
- Plugin **`fetchart`**: Fix the error with CoverArtArchive where the `maxwidth` option would not be used to download a pre-sized thumbnail for release groups, as is already done with releases.
- Plugin **`fetchart`**: The plugin can now get album art from `spotify`.
- Plugin **`fromfilename`**: Add debug log messages that inform when the plugin replaced bad (missing) artist, title or tracknumber metadata. :bug: (#4561) :bug: (#4600)
- Plugin **`importfeeds`**: Add a new output format allowing to save a playlist once per import session. :bug: `4863`
- Plugin **`kodiupdate`**: Now supports multiple kodi instances :bug: (#4101)
- Plugin **`listenbrainz`**: Add initial support for importing history and playlists from `ListenBrainz` :bug: (#1719)
- Plugin **`lyrics`**: Add LRCLIB as a new lyrics provider and a new `synced` option to prefer synced lyrics over plain lyrics.
- Plugin **`mbsubmit`**: Added a new `mbsubmit` command to print track information to be submitted to MusicBrainz after initial import. :bug: (#4455)
- Plugin **`mbsubmit`**: add new prompt choices helping further to submit unmatched tracks to MusicBrainz faster.
- Plugin **`smartplaylist`**: A new `--pretend` option lets the user see what a new or changed smart playlist saved in the config is actually returning. :bug: (#4573)
- Plugin **`smartplaylist`**: Add new config option `smartplaylist.fields`.
- Plugin **`smartplaylist`**: Add new option `smartplaylist.output`.
- Plugin **`smartplaylist`**: Add new option `smartplaylist.uri_format`.
- Plugin **`smartplaylist`**: During explicit runs of the `splupdate` command, the log message "Creating playlist ..."" is now displayed instead of hidden in the debug log, which states some form of progress through the UI. :bug: (#4861)
- Plugin **`smartplaylist`**: Expose config options as CLI options.
- Plugin **`spotify`**: The plugin now provides an additional command `spotifysync` that allows getting track popularity and audio features information from Spotify. :bug: (#4094)
- Plugin **`spotify`**: The plugin now records Spotify-specific IDs in the `spotify_album_id`, `spotify_artist_id`, and `spotify_track_id` fields. :bug: (#4348)
- Plugin **`spotify`**: We now fetch track's ISRC, EAN, and UPC identifiers from Spotify when using the `spotifysync` command. :bug: (#4992)
- Plugin **`subsonicupdate`**: Updates are now triggered whenever either the beets database is changed or a smart playlist is created/updated. :bug: `4862`
- Plugin **`substitute`**: Add the new plugin `substitute` as an alternative to the `rewrite` plugin. The main difference between them being that `rewrite` modifies files' metadata and `substitute` does not. :bug: (#2786)
- Preserve mtimes from archives :bug: (#4392)
- Prevent reimporting album if it is permanently removed from Spotify :bug: (#4800)
- Sorted the default configuration file into categories. :bug: (#4987)
- We now import and tag the `album` information when importing singletons using Spotify source. :bug: (#4398)
- We now import the remixer field from Musicbrainz into the library. :bug: (#4428)
- `import-options`: Add support for re-running the importer on paths in log files that were created with the `-l` (or `--logfile`) argument. :bug: (#4379) :bug: (#4387)
- `musicbrainz-config`: MusicBrainz release pages often link to related metadata sources like Discogs, Bandcamp, Spotify, Deezer and Beatport. When enabled via the `musicbrainz.external_ids` options, release ID's will be extracted from those URL's and imported to the library. :bug: (#4220)
- `musicbrainz-config`: a new `musicbrainz.enabled` option allows disabling the MusicBrainz metadata source during the autotagging process
- resolve transl-tracklisting relations for pseudo releases and merge data with the actual release :bug: (#654)

### Bug fixes

- Fix a crash when the Spotify API timeouts or does not return a `Retry-After` interval. :bug: (#4942)
- Fix a regression in the previous release that caused a `TypeError` when moving files across filesystems. :bug: (#4168)
- Fix bug regarding displaying tracks that have been changed not being displayed unless the detail configuration is enabled.
- Fix bug where `zsh` completion script made assumptions about the specific variant of `awk` installed and required specific settings for `sqlite3` and caching in `zsh`. :bug: (#3546)
- Fix bug where all media types are reported as the first media type when importing with MusicBrainz as the data source :bug: (#4947)
- Fix bug where an interrupted import process poisons the database, causing a null path that can't be removed. :bug: (#4906)
- Fix bug where some plugin commands hang indefinitely due to a missing `requests` timeout.
- Fix bug where unimported plugin would not ignore children directories of ignored directories. :bug: (#5130)
- Fix implicit paths OR queries (e.g. `beet list /path/ , /other-path/`) which have previously been returning the entire library. :bug: (#1865)
- Fix issue where `beet write` continuously retags the `albumtypes` metadata field in files. Additionally broken data could have been added to the library when the tag was read from file back into the library using `beet update`. It is required for all users to **check if such broken data is present in the library**. Following the instructions [described here](https://github.com/beetbox/beets/pull/4582#issuecomment-1445023493), a sanity check and potential fix is easily possible. :bug: (#4528)
- Fix issue where deletion of flexible fields on an album doesn't cascade to items :bug: (#4662)
- Fix updating "data_source" on re-imports and improve logging when flexible attributes are being re-imported. :bug: (#4726)
- Modifying flexible attributes of albums now cascade to the individual album tracks, similar to how fixed album attributes have been cascading to tracks already. A new option `--noinherit/-I` to `modify <modify-cmd>` allows changing this behaviour. :bug: (#4822)
- Plugin **`convert`**: Deleting the original files during conversion no longer logs output when the `quiet` flag is enabled.
- Plugin **`convert`**: Fix a bug with the `wma` format alias.
- Plugin **`convert`**: Resize album art when embedding :bug: (#2116)
- Plugin **`convert`**: Set default `max_bitrate` value to `None` to avoid transcoding when this parameter is not set. :bug: (#4472)
- Plugin **`deezer`**: Fix auto tagger pagination issues (fetch beyond the first 25 tracks of a release).
- Plugin **`deezer`**: Fixed the error where Deezer plugin would crash if non-Deezer id is passed during import.
- Plugin **`deezer`**: Improve Deezer plugin error handling and set requests timeout to 10 seconds. :bug: (#4983)
- Plugin **`deezer`**: Tolerate missing fields when searching for singleton tracks. :bug: (#4116)
- Plugin **`discogs`**: Fix "Discogs plugin replacing Feat. or Ft. with a comma" by fixing an oversight that removed a functionality from the code base when the MetadataSourcePlugin abstract class was introduced in PR's \#3335 and \#3371. :bug: (#4401)
- Plugin **`discogs`**: Fix bug where empty artist and title fields would return None instead of an empty list. :bug: (#4973)
- Plugin **`discogs`**: Skip Discogs query on insufficiently tagged files (artist and album tags missing) to prevent arbitrary candidate results. :bug: (#4227)
- Plugin **`embedart`**: Add support for ImageMagick 7.1.1-12 :bug: (#4836)
- Plugin **`embedart`**: Fix a crash when using recent versions of ImageMagick and the `compare_threshold` option. :bug: (#4272)
- Plugin **`fetchart`**: Correctly select the cover art from fanart.tv with the highest number of likes
- Plugin **`fetchart`**: Fix fetching from Cover Art Archive when the `maxwidth` option is set to one of the supported Cover Art Archive widths.
- Plugin **`fromfilename`**: Fix failed detection of \<track\> \<title\> filename patterns. :bug: (#4561) :bug: (#4600)
- Plugin **`importadded`**: Fix a bug with recently added reflink import option that causes a crash when ImportAdded plugin enabled. :bug: (#4389)
- Plugin **`lastgenre`**: Fix a duplicated entry for trip hop in the default genre list. :bug: (#4510)
- Plugin **`lastimport`**: Improve error handling in the `process_tracks` function and enable it to be used with other plugins.
- Plugin **`limit`**: Better header formatting to improve index
- Plugin **`lyrics`**: Fix Genius search by using query params instead of body.
- Plugin **`lyrics`**: Fix a crash with the Google backend when processing some web pages. :bug: (#4875)
- Plugin **`lyrics`**: Fixed issue with Genius header being included in lyrics, added test case of up-to-date Genius html
- Plugin **`lyrics`**: Fixed issue with Tekstowo backend not actually checking if the found song matches. :bug: (#4406)
- Plugin **`lyrics`**: Fixed issues with the Tekstowo.pl and Genius backends where some non-lyrics content got included in the lyrics
- Plugin **`replaygain`**: Avoid a crash when errors occur in the analysis backend. :bug: (#4506)
- Plugin **`replaygain`**: Correctly handle the `overwrite` config option, which forces recomputing ReplayGain values on import even for tracks that already have the tags.
- Plugin **`replaygain`**: The type of the internal `r128_track_gain` and `r128_album_gain` fields was changed from integer to float to fix loss of precision due to truncation. :bug: (#4169)
- Plugin **`scrub`**: Fixed the import behavior where scrubbed database tags were restored to newly imported tracks with config settings `scrub.auto: yes` and `import.write: no`. :bug: (#4326)
- Plugin **`spotify`**: Add a limit of 3 retries, instead of retrying endlessly when the API is not available.
- Plugin **`spotify`**: Add bad gateway (502) error handling.
- Plugin **`spotify`**: Fix auto tagger pagination issues (fetch beyond the first 50 tracks of a release).
- Plugin **`spotify`**: Improve handling of ConnectionError.
- Plugin **`unimported`**: The new `ignore_subdirectories` configuration option added in 1.6.0 now has a default value if it hasn't been set.
- Plugin **`web`**: Fix get file from item.
- Plugin **`web`**: Fix handling of "query" requests. Previously queries consisting of more than one token (separated by a slash) always returned an empty result.
- Plugin **`web`**: Fix range request support, allowing to play large audio/ opus files using e.g. a browser/firefox or gstreamer/mopidy directly.
- Remove unused functions :bug: (#5103)
- The Discogs release ID is now populated correctly to the discogs_albumid field again (it was no longer working after Discogs changed their release URL format). :bug: (#4225)
- The autotagger no longer considers all matches without a MusicBrainz ID as duplicates of each other. :bug: (#4299)
- We now respect the Spotify API's rate limiting, which avoids crashing when the API reports code 429 (too many requests). :bug: (#4370)
- We now use Python's defaults for command-line argument encoding, which should reduce the chance for errors and "file not found" failures when invoking other command-line tools, especially on Windows. :bug: (#4507)

### For plugin developers

- Allow reuse of some parts of beets' testing components. This may ease the work for externally developed plugins or related software (e.g. the beets plugin for Mopidy), if they need to create an in-memory instance of a beets music library for their tests.
- beets now explicitly prevents multiple plugins to define replacement functions for the same field. When previously defining `template_fields` for the same field in two plugins, the last loaded plugin would silently overwrite the function defined by the other plugin. Now, beets will raise an exception when this happens. :bug: (#5002)

### For packagers

- As noted above, the minimum Python version is now 3.7.
- The minimum required version of `mediafile` is now 0.9.0.
- We fixed a version for the dependency on the [Confuse]() library. :bug: (#4167)

### Other changes

- Add `sphinx` and `sphinx_rtd_theme` as dependencies for a new `docs` extra :bug: (#4643)
- Plugin **`absubmit`**: Deprecate the `absubmit` plugin since AcousticBrainz has stopped accepting new submissions. :bug: (#4627)
- Plugin **`acousticbrainz`**: Deprecate the `acousticbrainz` plugin since the AcousticBrainz project has shut down. :bug: (#4627)
- Plugin **`fish`**: Add `--output` option.
- Plugin **`limit`**: Limit query results to head or tail (`lslimit` command only)
- Plugin **`lyrics`**: Remove Musixmatch from default enabled sources as they are currently blocking requests from the beets user agent. :bug: (#4585)
- Refactor the test cases to avoid test smells.
- `/faq`: `multidisc`: Elaborated the multi-disc FAQ :bug: (#4806)
- `/faq`: `src`: Removed some long lines.

**Comment by snejus** [comment]
I rebased the PR off the most recent `master` @Serene-Arc .

**Comment by Serene-Arc** [comment]
Cool, thanks. I've reviewed the changes and it seems good to me. I'll merge and we can make another release whenever.

**Pull request merged**
