### PR TITLE
Rebase our .gitignore on top of gitignore.io

### PR DESCRIPTION
**Pull request by jrobeson**
The gitignore is located here: https://www.gitignore.io/api/python

I kept our settings at the top

### CODE REVIEW

**Comment by sampsyo** [comment]
As I said in https://github.com/sampsyo/confuse/pull/26, I'm not in love with really exhaustive ignore files. But ours was already pretty thorough, so maybe this doesn't really hurt here?

**Comment by jrobeson** [comment]
i'm not really in love with them either, but there's not much there that we don't already use, or isn't popular in the ecosystem. I removed the django stuff because I knew we'd never run into that. I kept everything that it seemed like we'd actually run into.

I was certainly being cautious because it's hard for me to know what's really used in the python community. I don't really spend much time doing python, so I haven't kept up with it. 

If you have some specifics to remove, then let me know.

**Comment by sampsyo** [comment]
Cool; no specific comments. Feel free to merge if you like! We can just use good judgement to avoid including too much cruft.

**Comment by jrobeson** [comment]
i don't think we'll need much more than this,    It'd be cool to remove man and the lyrics thing, but I don't wanna pick through the code now.

**Pull request merged**
