### PR TITLE
Add tests for safe_cast with float

### PR DESCRIPTION
**Pull request by jrobeson**
test safe_casting floats with only a dot

### CODE REVIEW

**Comment by sampsyo** [comment]
Nice catch! Looks like the thing to do is to add a special case to `safe_cast`, right?

**Comment by jrobeson** [comment]
or a regex like `r'[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?$'`

**Comment by jrobeson** [comment]
it'd be most certain with a try/catch, but if you wanna keep the regex, then I think something like that is the way to go

**Comment by jrobeson** [comment]
now included in #2014

**Pull request closed without merging**
