### PR TITLE
add tag, database entry, data population for musicbrainz release track id

### PR DESCRIPTION
**Pull request by Rawrmonkeys**

### CODE REVIEW

**Comment by Rawrmonkeys** [comment]
If I set up Tox, am I able to run all these tests locally?

**Comment by sampsyo** [comment]
Yes! You might be interested in the “Testing” page in the wiki for this repository.

**Comment by sampsyo** [comment]
Also, thanks for getting this work started! Linking to https://github.com/beetbox/beets/issues/406#issuecomment-374585705 for posterity.

**Comment by jdetrey** [comment]
Hi! What's the status on this PR?

I have fixed the unit tests so that all checks should pass, taking this new tag into account. However, this is in my own fork of https://github.com/Rawrmonkeys/beets/tree/feature/406. Concerned commits are on branch https://github.com/jdetrey/beets/commits/feature/406 (https://github.com/jdetrey/beets/commit/f74899ab9af4427fc87e6535fffeb0c85329ad65, https://github.com/jdetrey/beets/commit/9f4c5c8096832fdf1f289e0843250e3758ce05fe, and https://github.com/jdetrey/beets/commit/f01799207a11fc71ca1287b20be3a2718c98bcee), but I'm not sure how I can add them to this PR... Any idea?

Cheers!

**Comment by sampsyo** [comment]
Awesome; thanks!!

I don't think it's possible on GitHub to add commits to someone else's PR (just one way in which the git collaboration model is not the best of all possible worlds). I think the thing to do is to open another, separate PR from your extended branch—and reference this one in the description.

**Comment by jdetrey** [comment]
Hi! Thanks for your quick reply! Here goes, then: the new PR is #2896.
Cheers!

**Comment by sampsyo** [comment]
Finished up in #2896. Woohoo!

**Pull request closed without merging**
