### PR TITLE
chore(ci): add informational Codecov status checks

### PR DESCRIPTION
**Pull request by thomasrockhu-codecov**
## Description
Hi, Tom from Codecov here. I noticed that you were using Codecov but weren't actually getting any notifications on pull requests. I figured it would be useful to get some idea if code being changed is being tested, but also not blocking CI/merging. Let me know if this makes sense or if we can do something that would be helpful.

## To Do

- [x] Documentation. (If you've add a new command-line flag, for example, find the appropriate page under `docs/` to describe it.)
- [ ] Changelog. (Add an entry to `docs/changelog.rst` near the top of the document.)
- [x] Tests. (Encouraged but not strictly required.)

### CODE REVIEW

**Comment by wisp3rwind** [comment]
We disabled those on purpose a while back, since the reports seemed overly intrusive (https://github.com/beetbox/beets/commit/0395e7fd8095a1c03d2b9d1c3c0576ea4b95ce6e). Is there any documentation (or rather, examples) on what they look like nowadays?

**Comment by wisp3rwind** [comment]
Ok, thanks for clarification. Let's wait for a few more opinions on this one, though.

**Comment by sampsyo** [comment]
OK; thanks for looking into this! Let's at least give it a shot and see how it looks. I've installed the Codecov GitHub app; presumably that will make this PR start showing the status on next update?

**Comment by sampsyo** [comment]
Hmm… oddly, I'm not seeing anything here! The normal GitHub Actions are running as usual, but I don't see anything from Codecov…

**Comment by wisp3rwind** [comment]
Screenshot from 2022-04-24 13-01-42

Seems to work here.

**Comment by sampsyo** [comment]
Got it! I think I just didn't wait long enough. Looks good to me; let's give it a shot! Thanks again for your help.

**Pull request merged**
