### PR TITLE
Wikipedia plugin

### PR DESCRIPTION
**Pull request by sarikaya**
Add a plugin that is able to obtains metadata with HTML parsing by retrieving from Wikipedia source this content after accessing the URL created in the plugin with the title and album title of the musical material in order to use the desired tag information.

Please check it out and provide feedback. The plugin is [here](https://github.com/sarikaya/beets/blob/wikipedia/beetsplug/wikipedia.py)
Thanks

### CODE REVIEW

**Comment by sampsyo** [comment]
Wow! This is a pretty wild idea—great work getting it to do something useful!

In order to begin the process of putting this in core, there are a few hurdles that new plugins need to meet. Most prominently:

* Include the standard comments at the top of the file.
* Match the project's coding style. You can read more in the Hacking page on the project's wiki, or you can take a look at the flake8 report in Travis.
* Plugins need documentation.
* Some modicum of testing is nice to have too although not required.

Let us know if you'd be interested in pursuing that! This seems like a cool addition.

**Comment by sarikaya** [comment]
I am glad you like it. I'll do the things you mentioned. I hope something comes out nicely.

**Comment by gokturkgok** [comment]
Hi,
At first test especially on AppVeyor, it passed successfully but we have just modified project's coding syntax as flake8 style as it is required then both of the tests have given errors. 

Please, let us know if you have thoughts to handle this.
Thanks.

**Comment by sampsyo** [comment]
Hmm, that’s odd—there seem to be unrelated test failures having to do with parsing date queries. Very strange! Do these errors happen if you run the tests locally? (The Testing wiki page has instructions.)

**Comment by sarikaya** [comment]
Yes, it looks irrelevant test failures. We ran the 'test_plugins.py' locally and output is here:

> C:\Users\sarikaya\Documents\GitHub\beets\test>python test_plugins.py

> Sending event: import_begin
> Sending event: import_task_created
> Album: c:\users\sarikaya\appdata\local\temp\tmpammrih\testsrcdir\album
>   c:\users\sarikaya\appdata\local\temp\tmpammrih\testsrcdir\album\01 - track.mp3
> 
>   c:\users\sarikaya\appdata\local\temp\tmpammrih\testsrcdir\album\02 - track.mp3
> 
> .Sending event: import_begin
> Sending event: import_task_created
> Singleton: c:\users\sarikaya\appdata\local\temp\tmpghkdi6\testsrcdir\album\01 -
> track.mp3
> Singleton: c:\users\sarikaya\appdata\local\temp\tmpghkdi6\testsrcdir\album\02 -
> track.mp3
> ....Sending event: database_change
> Sending event: database_change
> no user configuration found at c:\users\sarikaya\appdata\local\temp\tmpoyvg_g\co
> nfig.yaml
> data directory: c:\users\sarikaya\appdata\local\temp\tmpoyvg_g
> plugin paths:
> Sending event: pluginload
> Sending event: cli_exit
> 
> no user configuration found at c:\users\sarikaya\appdata\local\temp\tmpoyvg_g\co
> nfig.yaml
> data directory: c:\users\sarikaya\appdata\local\temp\tmpoyvg_g
> plugin paths:
> Sending event: pluginload
> Modifying 1 items.
> aaa -  -
>   rating: 2.0
> Sending event: write
> open failed: [Errno 2] No such file or directory: u'\\\\?\\apath'
> error reading apath: [Errno 2] No such file or directory: u'\\\\?\\apath'
> Sending event: database_change
> Sending event: cli_exit
> no user configuration found at c:\users\sarikaya\appdata\local\temp\tmpoyvg_g\co
> nfig.yaml
> data directory: c:\users\sarikaya\appdata\local\temp\tmpoyvg_g
> plugin paths:
> Sending event: pluginload
> Sending event: cli_exit
> aaa -  -
> 
> no user configuration found at c:\users\sarikaya\appdata\local\temp\tmpoyvg_g\co
> nfig.yaml
> data directory: c:\users\sarikaya\appdata\local\temp\tmpoyvg_g
> plugin paths:
> Sending event: pluginload
> Sending event: cli_exit
> 
> .Sending event: database_change
> Sending event: database_change
> Sending event: item_copied
> Sending event: database_change
> Sending event: database_change
> Sending event: write
> Sending event: after_write
> .Sending event: event
> Sending event: event_foo
> .Sending event: event1
> Sending event: event2
> Sending event: event3
> Sending event: event4
> Sending event: event5
> Sending event: event6
> Sending event: event7
> Sending event: event8
> Sending event: event9
> ..Sending event: import_begin
> Sending event: import_task_created
> Sending event: import_task_start
> Looking up: c:\users\sarikaya\appdata\local\temp\tmpcp1ozn\testsrcdir\the_album
> Tagging Tag Artist - Tag Album
> No album ID found.
> Search terms: Tag Artist - Tag Album
> Album might be VA: False
> Sending event: albuminfo_received
> Candidate: Applied Artist - Applied Album (albumid)
> Computing track assignment...
> ...done.
> Success. Distance: 0.44
> Evaluating 1 candidates.
> Sending event: before_choose_candidate
> Prompt choice 'A foo' removed due to conflict with 'Apply' (short letter: 'a')
> Prompt choice 'Zupe' removed due to conflict with 'baZ' (short letter: 'z')
> Prompt choice 'Zoo' removed due to conflict with 'baZ' (short letter: 'z')
> Sending event: import_task_choice
> .Sending event: import_begin
> Sending event: import_task_created
> Sending event: import_task_start
> Looking up: c:\users\sarikaya\appdata\local\temp\tmpav_e4m\testsrcdir\the_album
> Tagging Tag Artist - Tag Album
> No album ID found.
> Search terms: Tag Artist - Tag Album
> Album might be VA: False
> Sending event: albuminfo_received
> Candidate: Applied Artist - Applied Album (albumid)
> Computing track assignment...
> ...done.
> Success. Distance: 0.44
> Evaluating 1 candidates.
> Sending event: before_choose_candidate
> Sending event: before_choose_candidate
> Sending event: import_task_choice
> .Sending event: import_begin
> Sending event: import_task_created
> Sending event: import_task_start
> Looking up: c:\users\sarikaya\appdata\local\temp\tmp7lmhia\testsrcdir\the_album
> Tagging Tag Artist - Tag Album
> No album ID found.
> Search terms: Tag Artist - Tag Album
> Album might be VA: False
> Sending event: albuminfo_received
> Candidate: Applied Artist - Applied Album (albumid)
> Computing track assignment...
> ...done.
> Success. Distance: 0.44
> Evaluating 1 candidates.
> Sending event: before_choose_candidate
> Sending event: import_task_choice
> .Sending event: import_begin
> Sending event: import_task_created
> Sending event: import_task_start
> Looking up: c:\users\sarikaya\appdata\local\temp\tmprrxkaa\testsrcdir\the_album
> Tagging Tag Artist - Tag Album
> No album ID found.
> Search terms: Tag Artist - Tag Album
> Album might be VA: False
> Sending event: albuminfo_received
> Candidate: Applied Artist - Applied Album (albumid)
> Computing track assignment...
> ...done.
> Success. Distance: 0.44
> Evaluating 1 candidates.
> Sending event: before_choose_candidate
> Sending event: import_task_choice
> .Sending event: import_begin
> Sending event: import_task_created
> Sending event: import_task_start
> Looking up: c:\users\sarikaya\appdata\local\temp\tmpybff86\testsrcdir\the_album\
> track_1.mp3
> Item search terms: Tag Artist - Tag Title 1
> Sending event: trackinfo_received
> Found 1 candidates.
> Sending event: before_choose_candidate
> Sending event: import_task_choice
> Sending event: import_task_created
> Sending event: import_task_start
> Looking up: c:\users\sarikaya\appdata\local\temp\tmpybff86\testsrcdir\the_album\
> track_2.mp3
> Item search terms: Tag Artist - Tag Title 2
> Sending event: trackinfo_received
> Found 1 candidates.
> Sending event: before_choose_candidate
> Sending event: import_task_choice
> Sending event: import_task_apply
> 0 of 1 items replaced
> Sending event: database_change
> Sending event: database_change
> Sending event: item_copied
> Sending event: database_change
> Sending event: write
> Sending event: after_write
> Sending event: database_change
> Sending event: import_task_files
> Sending event: item_imported
> Sending event: import_task_created
> Sending event: import_task_start
> Looking up: c:\users\sarikaya\appdata\local\temp\tmpybff86\testsrcdir\the_album\
> track_3.mp3
> Item search terms: Tag Artist - Tag Title 3
> Sending event: trackinfo_received
> Found 1 candidates.
> Sending event: before_choose_candidate
> Sending event: import_task_choice
> Sending event: import_task_apply
> 0 of 1 items replaced
> Sending event: database_change
> Sending event: database_change
> Sending event: item_copied
> Sending event: database_change
> Sending event: write
> Sending event: after_write
> Sending event: database_change
> Sending event: import_task_files
> Sending event: item_imported
> .
> ----------------------------------------------------------------------
> Ran 15 tests in 0.895s
> 
> OK

**Comment by jtpavlock** [comment]
This seems like it would be a pain to upkeep as opposed to an api source.

**Comment by sarikaya** [comment]
hell yeah indeed!

**Comment by jtpavlock** [comment]
Might be worth keeping as a third-party plugin then?

**Comment by sarikaya** [comment]
If metadata parsing going well, good coverage can be achieved to tagging. I think it's worth to try, third party would be handle.

**Comment by jtpavlock** [comment]
Does the code still work today?

**Comment by sarikaya** [comment]
not sure, it's been 3 years. but seems no changes so far.

**Pull request closed without merging**
