### PR TITLE
Compare case insensitive paths with SUBSTR and BYTELOWER

### PR DESCRIPTION
**Pull request by jrobeson**
Create a custom `bytelower` sqlite function so we can compare bytestrings in a semi
case insensitive fashion.  This is to work around sqlite builds are that compiled
with `-DSQLITE_LIKE_DOESNT_MATCH_BLOBS`.

See https://github.com/beetbox/beets/issues/2172 for details.

### CODE REVIEW

**Comment by jrobeson** [comment]
so while it does work, I'm not yet usre if connections are the keeper of functions, or the db as a whole. If it's the db as a whole, then the connection should probably explicitly be added to `connection[0]` or be moved into dbcore

**Comment by jrobeson** [comment]
so.. it breaks on py2 with

`AttributeError: 'buffer' object has no attribute 'lower'` :(

**Comment by sampsyo** [comment]
:confused: I suppose we need to convert the buffer to str, call lower, and convert back.

**Comment by jrobeson** [comment]
done.

**Comment by sampsyo** [comment]
Nice work! :sparkles: Since the tests pass, I say merge it. Thank you!!

**Pull request merged**
