### PR TITLE
[WIP] Truncate on character boundaries

### LINKED ISSUE #1418: max_filename_length creates invalid unicode characters
When using the max_filename_length config option to truncate long filenames, setting it to a number that is not a multiple of 4 seems to create invalid unicode characters at the end. Example from my server (CentOS 6.6, Beets 1.3.11), with an album by Belye Flagi Zazhigayte Medlenno, the full album name is:

Даже если пролетариат возьмёт власть в свои руки, весна всё равно достанется нам, а цели войны останутся целями войны

I set max_filename_length to 25, run beet mv and then beet ls -p and get this:

```
$ beet ls -p Белые
/var/subsonic/music/Белые флаги з/Даже если про/01 08.01.07.mp3
/var/subsonic/music/Белые флаги з/Даже если про/02 Мы вооруж.mp3
/var/subsonic/music/Белые флаги з/Даже если про/03 16.11.06.mp3
```

But if I try to actually ls the folder, when trying to tab complete I get this:

```
$ ls /var/subsonic/music/Белые\ флаги\ з
Белые флаги з�/ 
```

The final character is invalid, and I can't seem to input it, so I can't actually interact with the folder without using the inode. The same happens if I use a longer value like 100, with the exception that the full artist name comes out while the longer album name has the invalid character at the end.

I noticed that, in the case above using 25, the artist name was truncated even though it's only 13 unicode characters (<25), so I'm assuming that it's counting the bytes that make up the 1-4 byte unicode character, rather than each unicode character itself. I haven't tested this on a non-unicode album name, but I did test it with different numbers: even numbers don't necessarily work (100 did not), but powers of 2 (64) and multiples of 4 (24) both work without causing any invalid characters. Since it displays the path without issues through beets, I suspect it might be something to do with the way python handles the characters vs the way bash/ls does.

### PR DESCRIPTION
**Pull request by untitaker**
Fix #1418

### CODE REVIEW

**Comment by untitaker** [comment]
Alright, I think we have another problem with this:

* On Windows, the **path** is limited to 260 **characters** (https://stackoverflow.com/questions/4677234/python-ioerror-exception-when-creating-a-long-file)
* On Unix, the **filename/basename** is limited to 200 **bytes** (https://stackoverflow.com/questions/6571435/limit-on-file-name-length-in-bash)

So I think truncate_path shouldn't actually expose a `length` parameter and just do the right thing on each platform. This makes for a less confusing API IMO.

**Comment by sampsyo** [comment]
Interesting. To refine this a little bit:

* The *component* length limit on Unix is filesystem-dependent, and reported by [statvfs](http://linux.die.net/man/2/statvfs). (See `beets.util.max_filename_length`.)
* On Windows, we use the magical `\\?\` prefix to get long filenames. This gives us ("approximately") 32,767 characters for the *total* length, according to [the reference](https://msdn.microsoft.com/en-us/library/aa365247(v=vs.85).aspx). The component is still limited separately, to "commonly" 255 characters.

**Comment by sampsyo** [comment]
The upshot is that both platforms have component length limits. You're right, though, that the Windows limit is in characters.

**Comment by jtpavlock** [comment]
closing as abandoned

**Pull request closed without merging**
