### PR TITLE
add azlyrics to lyrics plugin

### PR DESCRIPTION
**Pull request by matlads**
Add azlyrics as a source backend for lyrics

### CODE REVIEW

**Comment by sampsyo** [comment]
Nice; looks good! I think Travis is complaining about a too-long line, which includes that HTML comment. Any chance there's a shorter way to match on that? Otherwise, you can pull it out into a multi-line string literal constant.

Also, would you mind adding a quick entry to the changelog about your addition?

**Comment by Moonbase59** [comment]
Did you try some more exotic artists and titles? I think maybe they might need some conversion, don’t know how much beets would do beforehand.

Take "AC/DC" with "Thunderstruck" (→ "acdc", "thunderstruck").
AZLyrics URI: https://www.azlyrics.com/lyrics/acdc/thunderstruck.html

**Comment by jackwilsdon** [comment]
It seems in certain cases that azlyrics switches to using IDs instead (see https://www.azlyrics.com/lyrics/hatters/810433.html) - I'm not sure how much we can do here except possibly look into using their search feature?

It seems like removing all non alphanumeric characters is the safest bet in regards to things such as "AC/DC".

**Comment by Moonbase59** [comment]
See https://www.azlyrics.com/lyrics/massiv/ichhabemeinetraumewahrgemacht.html ("Ich Habe Meine Träume Wahr Gemacht").

Looks like they somehow ASCII-fy and then remove special characters, reverting to IDs for non-ASCII languages. Without knowing their code, probably not easy to hack.

**Comment by sampsyo** [comment]
Indeed—this is sort of a cross-cutting concern across all the lyrics backends. See also #3340. Because it will never be possible to do this perfectly, I think it's fine to merge this as is (pending a line-length fix and a changelog entry) and incrementally improve the heuristic in the future.

**Comment by jtpavlock** [comment]
Is there evidence this provides any worthwhile additions to the current lyrics sources?

**Comment by jtpavlock** [comment]
A non-ideal solution could be to lookup the artist's page using the first letter of their (sorted) name and then using azlyric's alphabetized pages e.g. https://www.azlyrics.com/a.html for all artists starting the "A". Scrape the page for the matching artist, follow the link, then scrape that page for the matching song, follow the link, then finally scrape the lyrics.

**Pull request closed without merging**
