### PR TITLE
 smartplaylist: Change base directory for exported paths

### PR DESCRIPTION
**Pull request by nathdwek**
An attempt at solving #2547 .

To do:
* Add warnings if both `relative_to` and `target_dir` are truthy at the same time.
* Tests

This should be pretty straightforward all considered.
@duckpuppy Could you try running beets from this branch as an "early adopter" to give some feedback if there is some to be given?

### CODE REVIEW

**Comment by sampsyo** [comment]
Nice! This looks good from here, but it would be great to have @duckpuppy try it out.

About those Travis failures: we're having some unrelated trouble, which I hope I've fixed in a recent commit.

**Comment by duckpuppy** [comment]
Certainly - I'll see if I can give this a try tonight.

**Comment by duckpuppy** [comment]
Sorry I've taken a few days to test this out - life gets in the way of things occasionally.

It's not working quite right, unless I've missed updating something else in the PR branch.

I'm using the following config:
```yaml
smartplaylist:
#  target_dir: G:/Music
  playlist_dir: ~/.config/beets/playlists
  playlists:
    - name: beatles.m3u
      query: 'artist:Beatles'
```

Without the `target_dir` option, I get:
```
...
/mnt/barry/music/The Beatles/Yesterday... and Today/01 Drive My Car.mp3
/mnt/barry/music/The Beatles/Yesterday... and Today/02 I'm Only Sleeping.mp3
/mnt/barry/music/The Beatles/Yesterday... and Today/03 Nowhere Man.mp3
/mnt/barry/music/The Beatles/Yesterday... and Today/04 Dr. Robert.mp3
/mnt/barry/music/The Beatles/Yesterday... and Today/05 Yesterday.mp3
/mnt/barry/music/The Beatles/Yesterday... and Today/06 Act Naturally.mp3
/mnt/barry/music/The Beatles/Yesterday... and Today/07 And Your Bird Can Sing.mp3
/mnt/barry/music/The Beatles/Yesterday... and Today/08 If I Needed Someone.mp3
/mnt/barry/music/The Beatles/Yesterday... and Today/09 We Can Work It Out.mp3
/mnt/barry/music/The Beatles/Yesterday... and Today/10 What Goes On.mp3
/mnt/barry/music/The Beatles/Yesterday... and Today/11 Day Tripper.mp3
...
```

Uncommenting `target_dir: G:/Music` gives me:
```
...
/home/duckpuppy/G:/Music/The Beatles/Yesterday... and Today/01 Drive My Car.mp3
/home/duckpuppy/G:/Music/The Beatles/Yesterday... and Today/02 I'm Only Sleeping.mp3
/home/duckpuppy/G:/Music/The Beatles/Yesterday... and Today/03 Nowhere Man.mp3
/home/duckpuppy/G:/Music/The Beatles/Yesterday... and Today/04 Dr. Robert.mp3
/home/duckpuppy/G:/Music/The Beatles/Yesterday... and Today/05 Yesterday.mp3
/home/duckpuppy/G:/Music/The Beatles/Yesterday... and Today/06 Act Naturally.mp3
/home/duckpuppy/G:/Music/The Beatles/Yesterday... and Today/07 And Your Bird Can Sing.mp3
/home/duckpuppy/G:/Music/The Beatles/Yesterday... and Today/08 If I Needed Someone.mp3
/home/duckpuppy/G:/Music/The Beatles/Yesterday... and Today/09 We Can Work It Out.mp3
/home/duckpuppy/G:/Music/The Beatles/Yesterday... and Today/10 What Goes On.mp3
/home/duckpuppy/G:/Music/The Beatles/Yesterday... and Today/11 Day Tripper.mp3
...
```

`/home/duckpuppy` is my user's home directory, and it's there no matter where I run the `beets splupdate` command from.

**Comment by duckpuppy** [comment]
I think the problem is that `normpath` doesn't deal well with Windows style drive letter paths.

**Comment by duckpuppy** [comment]
Using a simple test, I was able to get things to work locally.

```
import ntpath
import posixpath

...
if re.match("^[a-zA-Z]:[/\\\\].*", target_dir):
    target_dir = ntpath.normpath(target_dir)
else:
    target_dir = posixpath.normpath(target_dir)
...
```

Though... can this be a simple replace of the beets directory substring with the `target_dir` rather than using the path manipulation to rebase things?

**Comment by sampsyo** [comment]
Interesting! So it looks like things are mostly working aside from trying to normalize a Windows path on a Unix system.

I suppose one option would just be to not normalize the `target_dir` path at all. That way, users could even use relative paths there that would not get "absolutified" in the output.

**Comment by nathdwek** [comment]
In my opinion this is getting too specific for this use case to make it into beets like this.
I'd say the better option would be a 'playlist generated' hook.

**Comment by duckpuppy** [comment]
I'm not sure how this is too specific. The request was for the ability to have a simple replacement for the start of a string with another string. The PR is too complex for the simple case.

**Pull request closed without merging**
