### PR TITLE
Parallelize absubmit

### PR DESCRIPTION
**Pull request by bemeurer**
Solves #2442

### CODE REVIEW

**Comment by sampsyo** [comment]
Looks like just what the doctor ordered! :sparkles: Would you mind adding a changelog entry?

**Comment by bemeurer** [comment]
@sampsyo Almost! Trying to fix this right now
```Python
Traceback (most recent call last):
  File "./beet", line 23, in <module>
    beets.ui.main()
  File "/home/bemeurer/src/beets/beets/ui/__init__.py", line 1256, in main
    _raw_main(args)
  File "/home/bemeurer/src/beets/beets/ui/__init__.py", line 1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/bemeurer/src/beets/beetsplug/absubmit.py", line 110, in command
    pool.map(self.analyze_submit, items)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
    put(task)
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib64/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle _thread._local objects
```

Any ideas?

**Comment by sampsyo** [comment]
Hmm, not exactly. Maybe the problem is that multiprocessing is trying to pickle `self` to send it across the channel there, which could be causing problems? Maybe it’s possible to use `pdb` to find out what `obj` is here.

**Comment by bemeurer** [comment]
Good idea, on it!

**Comment by bemeurer** [comment]
@sampsyo Tested and ready for merging!

**Comment by sampsyo** [comment]
Hmm; threads do seem like the right thing here, but I’m slightly concerned that `ThreadPool` isn’t documented in the stdlib. Does this work on Python 2? If not, maybe we’d be better off with [the thread pool in concurrent.futures](
https://docs.python.org/dev/library/concurrent.futures.html#threadpoolexecutor)?

**Comment by bemeurer** [comment]
Oh, I don't have Python2 on my machine. Let me install it and test.

**Comment by bemeurer** [comment]
It explodes with Python2

**Comment by bemeurer** [comment]
@sampsyo I think I can make it works in parallel for both Python 2 and Python 3, but with slightly different techniques. I am giving it a shot right now :)

**Comment by bemeurer** [comment]
@sampsyo I couldn't get it to work in Python 2, so I reverted to the nice original multithreding code for Python 3, and made it fallback to sequential on Python 2.

**Comment by sampsyo** [comment]
Looks fantastic; thank you for your help!

**Pull request merged**
