### PR TITLE
mediafile: prefer latin-1 encoding for ID3 APIC descriptions. Fixes #899

### LINKED ISSUE #899: MediaFile: use older text encodings in ID3v2.3 mode
I am trying to create an auto-tagging configuration in which my tags are saved in ID3v2.3 (as 2.4 lacks compatibility with some players I use) and I like the cover art to be embedded in each music file. However, the cover art of the output files is not recognised by OS X 10.9.4 (i.e. in Finder) or iTunes.

Here is a simple configuration with which the problem occurs:

``` yaml
directory: /mnt/data/home/Music

plugins: mbsync fetchart embedart
per_disc_numbering: yes
id3v23: yes

import:
    copy: yes
    write: yes

paths:
    default: $albumartist/$album%aunique{}/$disc-$track $title
```

When I comment the `id3v23: yes` option the covers of the output files are correctly recognised in Mac.

The cover art of the ID3v2.3 output files is recognised in Windows, so it seems a Mac-specific issue. Strangely enough, the input files I used already have ID3v2.3 tags and embedded cover art and are correctly recognised in Mac. Below you have a diff of the ID3v2.3 tags (sorted by name) between an input and an output file taken with `mid3v2`:

``` diff
1c1,2
< APIC= (image/jpeg, 32205 bytes)

---
> APIC= (image/jpeg, 111083 bytes)
> COMM=iTunNORM='eng'= 00001700 00001700 00003981 00003981 00000000 00000000 00008187 00008187 00000000 00000000
3a5,6
> TBPM=0
> TCMP=0
5a9
> TLAN=eng
12a17,19
> TXXX=Album Artist Credit=The Beatles
> TXXX=ALBUMARTISTSORT=Beatles, The
> TXXX=Artist Credit=The Beatles
14a22
> TXXX=MusicBrainz Album Comment=UK mono
17c25
< TXXX=MusicBrainz Album Status=official

---
> TXXX=MusicBrainz Album Status=Official
27a36
> USLT=[unrepresentable data]
```

### PR DESCRIPTION
**Pull request by lazka**
iTunes has problems with everything but latin-1
Try to use latin-1 if possible and fall back to utf-16.

### CODE REVIEW

**Comment by sampsyo** [comment]
Cool! This seems like a reasonable policy. And as far as I can tell, this is the right thing to do on v2.4, right? There's no sense in preferring UTF-8 on v2.4 and Latin-1 on v2.3?

**Comment by lazka** [comment]
> And as far as I can tell, this is the right thing to do on v2.4, right? There's no sense in preferring UTF-8 on v2.4 and Latin-1 on v2.3?

See https://github.com/beetbox/beets/issues/899#issuecomment-62437773

utf-16 and latin-1 are the only working encodings in both cases.

An alternative strategy would be `utf-16 if desc else latin-1` (empty utf-16 doesn't work) but preferring latin-1 seems like a better choice given the problems described in #2264

**Comment by gboysko** [comment]
This change looks great to me. My only suggestion would be to use the symbolic constants (mutagen.id3.Encoding.UTF-16, etc) instead of the numeric values (0, 1).

**Comment by gboysko** [comment]
Thanks @lazka. Looks great! I'm eager to try it out as soon as it gets merged!

**Comment by sampsyo** [comment]
Yes, thank you, @lazka! I've merged the fix.

**Pull request merged**
