### PR TITLE
add file check to move command

### PR DESCRIPTION
**Pull request by pszxzsd**
Currently missing files, including album art, cause move operations to error out midway, leaving things in a dirty state with half moved albums.

This patch adds a pre-check to the move command and aborts if any audio file to be moved is missing. Missing album art triggers a warning and is dereferenced in the library.

### CODE REVIEW

**Comment by sampsyo** [comment]
Hey, thanks for looking into this! It's definitely annoying when a command leaves you in a half-completed state.

This made me ask a couple of questions about these cases:

* As #1926 suggests, another alternative is just to log an error for the files that can't be moved and just keep going. In some ways, that seems more friendly—you still get messages telling you how to fix the situation, but you don't then need to re-run the command. Any opinions on choosing between those two behaviors?
* Whatever policy we choose, maybe we can find a way for it to apply to all similar operations—not just `move`. That shouldn't stop us from fixing this now, but we should open another ticket to generalize the solution.
* Clearly the worst thing that could happen is that a file gets moved but the database entry stays the same. Let's make sure that whatever we do can't lead to that. (This PR does the right thing, of course.)

**Comment by pszxzsd** [comment]
Okay, then I would suggest to add a file check to item.move_file, similar to what I added to album.move_art here. If the file doesn't exit emit a error (warning?) and remove it from the library.

That being said, knowing beforehand if the operation will succeed entirely seems like a boon to me. We could still add this pre-check, but I would turn it into an option for the move command (disabled by default). Thoughts?

**Comment by sampsyo** [comment]
Yeah, an optional pre-check does seem useful for the `move` command in particular. If we do that, it would be worth thinking about how extensive it should be. Should it check whether the destination path is writeable for each item, for example? It will be impossible to avoid all errors, of course (such as out-of-space problems), but we should be clear about which ones we will catch.

It's a good question about automatically removing "dangling" database entries. This could be really surprising if files were just temporarily unavailable, for example. Logging a warning seems good, of course, but automatically removing database entries without user consent seems dangerous. We may need to put this in a separate command—along the lines of the current `update`, which does exactly this (among other things).

**Comment by jtpavlock** [comment]
It seems there may be some more gameplanning involved in implementing this feature, and as it's been a number of years since this was last updated, I've opted to close it. Any further discussion of the issue or implementation should be moved to #1926. 

@pszxzsd if at any point you wish you continue your work on this, feel free to re-open the PR 😄

**Pull request closed without merging**
