### PR TITLE
Add manually triggered mode for zero plugin

### PR DESCRIPTION
**Pull request by SJoshBrown**
I'm fairly new to the process so I hope I've done this correctly. Please let me know if I need to make any changes to get this merged up.

This is for Issue #2274

### CODE REVIEW

**Comment by SJoshBrown** [comment]
I've taken another pass at this and factored out some of the shared code. I also added a few more tests to increase the coverage.

**Comment by nathdwek** [comment]
I'm interested in this feature being added for consistency's sake, so I took a look at the whole plugin.
There is only one important thing I think should be added before going through with this, that is adding safeguards in manual mode when the query is empty, because of the nature of the operation (see #1286 )

However, I think the original plugin is a mess in terms of style and structure, cf my review. Maybe this is the occasion to revisit that?

**Comment by sampsyo** [comment]
Indeed, the plugin as it was was a bit of a mess. Thanks for looking into it, @nathdwek!

**Comment by nathdwek** [comment]
I opened #2345 . Some unexpected issues in the testing department, but would you be able to rewrite on top of that when that's fixed? We can also do it the other way around if it's more convenient for you?

**Comment by SJoshBrown** [comment]
I'm happy to wait until it gets some cleaning up. Then I can come back and rewrite this

**Comment by nathdwek** [comment]
I'll see tomorrow if I can sort this test thing out with a fresh mind. But my absolute priority is not getting in your way!

**Comment by sampsyo** [comment]
Either way seems to work from my perspective—I'd also be happy to merge this new feature first and then do the refactoring afterward.

**Comment by SJoshBrown** [comment]
@sampsyo  @nathdwek, I think this should be ready to go now. Let me know if there are any other changes we should make

**Comment by sampsyo** [comment]
All merged up. :sparkles: Thank you for taking care of this!

**Pull request merged**
