### PR TITLE
Add "play" option to "random" plugin

### PR DESCRIPTION
**Pull request by diomekes**
I copied some code from the random.py and added it to play.py to add two options to play plugin:
-r to randomize playlist items to play
-n to choose max number of random items to add (just like random plugin, default is 1)

The only problem I've encountered so far is that -n does not work without -r, because I did not add/edit any of the play plugin code.

I'm surprised I got it to work because I know no programming.

### CODE REVIEW

**Comment by sampsyo** [comment]
This is a good direction; thanks for taking the first step!

Before we consider merging this, we'll need to get rid of the duplicated code, which can become a maintenance nightmare down the road. This could work by just importing code from the random plugin module. Or, as #795 suggests, the "right way" to do this would be to add new query syntax that lets *any command at all* use random selection.

**Comment by diomekes** [comment]
Does it not make more sense, then, for random to be an option to comands instead of a new query syntax?

**Comment by sampsyo** [comment]
Right. Or rather, it's not that it doesn't make *sense* to extend commands—it's just that it would be *even better* to have query syntax. That way, all commands could take advantage of random selection "for free" without each one needing to be extended individually.

**Comment by bearcatsandor** [comment]
Food for thought: It would be really cool to have a random by time function. Such that when you had 30 minutes before you raced out the door, you could give the randomizer a time and it would pick tracks that would fit within that time constraint.

**Comment by sampsyo** [comment]
Great minds think alike, @bearcatsandor! I have been fantasizing about exactly the same idea lately, for when I have a meeting coming up and I need to fill the time with music.

For what it's worth, you can already randomize based on the length of an individual song already:

```
$ beet random length:120..240
```

but that's not exactly what you were proposing, of course.

**Comment by bearcatsandor** [comment]
I'd love for it to be part of the random command, not just the play command, so that it could be piped to other commands. (i feel like i'm thread-jacking a bit now. Can this be spiraled off to it's own request?)

**Comment by sampsyo** [comment]
Yes, good point—please do start a new thread for this (nifty) new feature request.

**Comment by bearcatsandor** [comment]
https://github.com/beetbox/beets/issues/2305

**Comment by sampsyo** [comment]
Here's one case where I frequently wish for random selection in queries: the web interface. It would be awesome to type `rand:5` or something into the search box to bring up a few songs from my library.

**Comment by diomekes** [comment]
I've updated the play plugin with hopefully better code to reduce repetition.  If it is merged, the play plugin will require the random plugin to play random items.

I decided to add the functionality to the play plugin since it made more sense to have "play random" then "random play."  

I'm not sure if there's a better way to suppress stdout from an imported module's function, and what I currently have is the best I could come up with, but maybe there's a more elegant solution.

**Comment by sampsyo** [comment]
OK, thanks for helping out! This does avoid the duplicated code from before. I'll continue to fiddle with this, but the ultimate solution may be to wrap your code up in query syntax.

**Comment by diomekes** [comment]
I imagine a list needs to be created from the items returned by a query and then shuffled and shortened.
  I can't figure out how do that through a query prefix.

Doesn't the query run before the creation of a list of values that can be manipulated?  I think dbcore.query returns True or False on patterns and values, how can w randomize values matched in the same function?

**Comment by sampsyo** [comment]
Yeah, it would be a little tricky—we'd need to design a new kind of query modifier that lets us take a random subset of the results that would be returned otherwise.

**Comment by diomekes** [comment]
See #2350.

**Comment by diomekes** [comment]
See #2350.

**Pull request closed without merging**
