### PR TITLE
Override match.require and match.ignored when searching for explicit IDs

### PR DESCRIPTION
**Pull request by Holzhaus**
Quick and dirty fix of the problem described in #1270.

### CODE REVIEW

**Comment by sampsyo** [comment]
Nice! This seems like the right approach. It might be nice to keep a warning, however, when these occur—perhaps that wouldn't be too hard to do either?

**Comment by Holzhaus** [comment]
Ok, now warnings are displayed to the user (using `text_highlight` color). Also, the recommendation is always set to none, so that user confirmation is necessary. That should mitigate accidental copy&pasting ;-)

Let me know if anything else is missing.

**Comment by Holzhaus** [comment]
Whoops, forgot to update the testcases. Also, it's probably better to use a `set` instead of a `list` to keep track of problems.

**Comment by Holzhaus** [comment]
@sampsyo Let me know if you want me to change something else.

**Comment by sampsyo** [comment]
Hey, sorry for dropping the thread on this! This looks good overall—could you perhaps look into adding some docstrings to describe what `problems` is supposed to contain in `AlbumMatch`?

**Comment by jtpavlock** [comment]
@Holzhaus do you intend to continue with this?

**Comment by Holzhaus** [comment]
> @Holzhaus do you intend to continue with this?

Not anytime soon. Feel free to take over and use my branch as a starting point.

**Comment by jtpavlock** [comment]
Thanks for the response. I'll close this for now and advise anyone that'd like to continue this work to re-open or open a new pr.

**Pull request closed without merging**
