### PR TITLE
Allow SQL preselection on queries

### PR DESCRIPTION
**Pull request by guibog**
Not sure this patch really makes sense. But still, on my db with 12000 tracks, it speeds up a lot a specific kind of queries: queries with a filter that can be handled by a normal SQL filter, plus another subquery trying to match some other item attributes (those stored in item_attributes).

The increase in query speed is important, I go from a 6 s. query time on master, to a much faster 0.2 s query time with this patch.

However, I am not sure this patch is not breaking some other use case I don't know of (and is not covered in a test case).

### CODE REVIEW

**Comment by guibog** [comment]
Was thinking about this PR under the shower. In fact I think the real solution is to have an index on all metadata attached to all items and albums, and first prefilter query result using this index, and then refine the result set.

**Comment by sampsyo** [comment]
I'm not quite sure if I understand how this works—can you explain a little more about how this code preserves correctness (and, secondarily, why it's faster)?

In particular, it looks like this affects all CollectionQuery classes. Did you mean for this to be special for AndQuery—that is, to do some SELECTing in SQLite and then filter the results with the rest of the AndQuery?

**Comment by guibog** [comment]
Not sure if this is really correct. It tried to add a few tests proving it one way or the other but I think it would break only if OrQuery was used, and it is not. Anyway I added a check on `joiner`, not ideal but maybe still better than copying the `clause_with_joiner` method to `AndQuery`.

This patch increases a lot speed on some "and" queries like [love custom_field:bar] because it allow a first prefiltering using SQL (selecting only items with "love" in their title, album, etc), and then loops on these items to check if they match the other criterium (do their custom_field have the value "*bar*").

Without this patch, as one subquery of the `AndQuery` is not about a field in the main `items` table, beets have to fetch all items and check them one by one, which is much longer.

**Comment by sampsyo** [comment]
Thanks for the extra background! Now that I understand, this is absolutely something I even intended to do after introducing "slow queries" some time ago; it was just a lower priority than the first cut.

This little enhancement will be good to have. As a little guidance to get this encapsulated:

* This should apply inside the `AndQuery` class specifically. This may require refactoring so the logic doesn't need to live in the generic `CollectionQuery`.
* It's currently a little odd that we're *reapplying* the same predicate after matching in the database. For simplicity, if not also for efficiency, it would be great to "split" the query so that the fast components don't get executed in Python later.
* The above is particularly important for queries that can currently be executed *entirely* in SQL. This patch currently actually slows those down: it does the work again on the Python side once the results are returned, even if the query doesn't need any more processing.

A complete solution would be to allow queries to break up into slow and fast components. What are currently "fast" queries would then have a null slow component, which would remove that unnecessary overhead.

**Comment by guibog** [comment]
I can try to find some time to work on this if you think it can be useful. However, I'd like to know how you would see a full indexing solution, which will not resort on selecting in `items` or `albums` tables with where clauses, but tokenize and index any attribute in a new table with this structure: "token | target_type | target_id | attribute_name". (This leaves aside the null-query and the numeric queries).

**Comment by sampsyo** [comment]
Can you explain a little more what you mean by "tokenizing" the attributes? How would this work, and what would the intended benefit be?

**Comment by guibog** [comment]
For example if the user adds a song called "[untitled]" from album Foo Baaaaar by Baz Band, with custom_attribute (e.g. lyrics) set to "aaa1 aaa2 bc-de 1234 5678.90", we would add these lines to the index table (where 123 is the entity_id of this song.

```
foo item 123 album
baa item 123 album
baz item 123 artist
ban item 123 artist
unt item 123 title
aaa item 123 custom_attribute
aaa item 123 custom_attribute
bc item 123 custom_attribute
de item 123 custom_attribute
123 item 123 custom_attribute
567 item 123 custom_attribute
```

So tokenization means "take a string and split it in in little tokens of 3 characters max that are efficient for searching in an index". I think PostgreSQL has a built-in function for that. Once we have this index a normal untyped query like [foo] becomes "select distinct entity_id where index.token = 'foo.*'" (I forgot the real syntax). Note that the result will be different than it is right now: it will match only songs with attributes that have a substring starting with "foo". So it is not a grep, it is more like a google search. But I think it is the normal way to query music databases.

**Comment by sampsyo** [comment]
Oh! I see—you're interested in splitting strings into n-grams for efficient full-text search.

This seems orthogonal to what's being proposed here. It also seems like SQLite's built-in full-text search mechanisms might be cleaner than reimplementing the string indexing ourselves.

**Comment by jtpavlock** [comment]
Unless @guibog is interested in continuing this, I don't see it being merged in in it's current state.

**Comment by guibog** [comment]
@jtpavlock sorry this is too old

**Pull request closed without merging**
