### PR TITLE
Create Python 3 tests

### PR DESCRIPTION
**Pull request by jackwilsdon**
This PR creates some tests for the Python 3 code. These are currently allowed to fail, as there are still some issues that need to be resolved.

### CODE REVIEW

**Comment by sampsyo** [comment]
This looks fantastic! I'm excited to get these tests running since we're now working in earnest on py3k compatibility.

Out of curiosity: does running flake8 on Python 3 reveal anything different from flake8 on Python 2?

**Comment by jackwilsdon** [comment]
I asked myself that question and did a quick test.

    py -e py27flake8

>     GLOB sdist-make: /Users/jack/Documents/Development/Personal/beets/setup.py
    py27flake8 create: /Users/jack/Documents/Development/Personal/beets/.tox/py27flake8
    py27flake8 installdeps: flake8, flake8-future-import, pep8-naming
    py27flake8 inst: /Users/jack/Documents/Development/Personal/beets/.tox/dist/beets-1.3.18.zip
    py27flake8 installed: beets==1.3.18,enum34==1.1.6,flake8==2.5.4,flake8-future-import==0.4.1,jellyfish==0.5.4,mccabe==0.4.0,munkres==1.0.7,musicbrainzngs==0.6,mutagen==1.32,pep8==1.7.0,pep8-naming==0.3.3,pyflakes==1.0.0,PyYAML==3.11,Unidecode==0.4.19
    py27flake8 runtests: PYTHONHASHSEED='2822864337'
    py27flake8 runtests: commands[0] | flake8 beets beetsplug beet test setup.py docs
    _______________________________________ summary ________________________________________
      py27flake8: commands succeeded
      congratulations :)

    py -e py35flake8

>     GLOB sdist-make: /Users/jack/Documents/Development/Personal/beets/setup.py
    py35flake8 create: /Users/jack/Documents/Development/Personal/beets/.tox/py35flake8
    py35flake8 installdeps: flake8, flake8-future-import, pep8-naming
    py35flake8 inst: /Users/jack/Documents/Development/Personal/beets/.tox/dist/beets-1.3.18.zip
    py35flake8 installed: beets==1.3.18,enum34==1.1.6,flake8==2.5.4,flake8-future-import==0.4.1,jellyfish==0.5.4,mccabe==0.4.0,munkres==1.0.7,musicbrainzngs==0.6,mutagen==1.32,pep8==1.7.0,pep8-naming==0.3.3,pyflakes==1.0.0,PyYAML==3.11,Unidecode==0.4.19
    py35flake8 runtests: PYTHONHASHSEED='3603913992'
    py35flake8 runtests: commands[0] | flake8 beets beetsplug beet test setup.py docs
    beets/importer.py:643:64: F821 undefined name 'unicode'
    beets/library.py:97:25: F821 undefined name 'buffer'
    beets/library.py:98:24: F821 undefined name 'buffer'
    beets/library.py:104:20: F821 undefined name 'buffer'
    beets/library.py:106:21: F821 undefined name 'buffer'
    beets/library.py:120:62: F821 undefined name 'unicode'
    beets/library.py:127:71: F821 undefined name 'unicode'
    beets/library.py:149:30: F821 undefined name 'unicode'
    beets/library.py:153:32: F821 undefined name 'buffer'
    beets/library.py:166:21: F821 undefined name 'buffer'
    beets/library.py:277:13: F821 undefined name 'unicode'
    beets/library.py:281:16: F821 undefined name 'unicode'
    beets/library.py:327:62: F821 undefined name 'unicode'
    beets/library.py:513:34: F821 undefined name 'unicode'
    beets/library.py:515:36: F821 undefined name 'buffer'
    beets/library.py:562:40: F821 undefined name 'long'
    beets/library.py:1057:67: F821 undefined name 'unicode'
    beets/library.py:1175:26: F821 undefined name 'unicode'
    beets/library.py:1251:34: F821 undefined name 'basestring'
    beets/library.py:1401:51: F821 undefined name 'unicode'
    beets/mediafile.py:131:36: F821 undefined name 'basestring'
    beets/mediafile.py:132:23: F821 undefined name 'unicode'
    beets/mediafile.py:147:22: F821 undefined name 'unicode'
    beets/mediafile.py:150:30: F821 undefined name 'unicode'
    beets/mediafile.py:153:20: F821 undefined name 'unicode'
    beets/mediafile.py:159:36: F821 undefined name 'basestring'
    beets/mediafile.py:160:23: F821 undefined name 'unicode'
    beets/mediafile.py:219:31: F821 undefined name 'unicode'
    beets/mediafile.py:406:37: F821 undefined name 'unicode'
    beets/mediafile.py:425:44: F821 undefined name 'unicode'
    beets/mediafile.py:426:44: F821 undefined name 'unicode'
    beets/mediafile.py:449:54: F821 undefined name 'unicode'
    beets/mediafile.py:471:57: F821 undefined name 'unicode'
    beets/mediafile.py:474:30: F821 undefined name 'unicode'
    beets/mediafile.py:477:25: F821 undefined name 'unicode'
    beets/mediafile.py:481:25: F821 undefined name 'unicode'
    beets/mediafile.py:591:64: F821 undefined name 'unicode'
    beets/mediafile.py:806:21: F821 undefined name 'unicode'
    beets/mediafile.py:822:47: F821 undefined name 'unicode'
    beets/mediafile.py:1073:48: F821 undefined name 'unicode'
    beets/mediafile.py:1112:31: F821 undefined name 'unicode'
    beets/mediafile.py:1193:35: F821 undefined name 'basestring'
    beets/mediafile.py:1194:50: F821 undefined name 'unicode'
    beets/mediafile.py:1195:38: F821 undefined name 'unicode'
    beets/mediafile.py:1232:20: F821 undefined name 'unicode'
    beets/mediafile.py:1359:54: F821 undefined name 'unicode'
    beets/plugins.py:57:54: F821 undefined name 'basestring'
    beets/plugins.py:60:37: F821 undefined name 'basestring'
    beets/autotag/hooks.py:206:29: F821 undefined name 'unicode'
    beets/autotag/hooks.py:207:29: F821 undefined name 'unicode'
    beets/autotag/hooks.py:360:16: F821 undefined name 'cmp'
    beets/autotag/mb.py:379:68: E901 SyntaxError: invalid syntax
    beets/dbcore/db.py:72:61: F821 undefined name 'unicode'
    beets/dbcore/db.py:455:33: F821 undefined name 'basestring'
    beets/dbcore/db.py:466:35: F821 undefined name 'basestring'
    beets/dbcore/query.py:232:32: F821 undefined name 'basestring'
    beets/dbcore/query.py:249:37: F821 undefined name 'basestring'
    beets/dbcore/query.py:252:41: F821 undefined name 'unicode'
    beets/dbcore/query.py:254:32: F821 undefined name 'buffer'
    beets/dbcore/query.py:255:39: F821 undefined name 'buffer'
    beets/dbcore/query.py:307:30: F821 undefined name 'basestring'
    beets/dbcore/query.py:798:64: F821 undefined name 'unicode'
    beets/dbcore/types.py:40:18: F821 undefined name 'unicode'
    beets/dbcore/types.py:66:16: F821 undefined name 'unicode'
    beets/dbcore/types.py:103:34: F821 undefined name 'buffer'
    beets/dbcore/types.py:105:34: F821 undefined name 'unicode'
    beets/dbcore/types.py:197:16: F821 undefined name 'unicode'
    beets/ui/__init__.py:519:67: F821 undefined name 'unicode'
    beets/ui/__init__.py:539:26: F821 undefined name 'basestring'
    beets/ui/__init__.py:539:59: F821 undefined name 'basestring'
    beets/ui/__init__.py:541:13: F821 undefined name 'unicode'
    beets/ui/__init__.py:542:13: F821 undefined name 'unicode'
    beets/ui/__init__.py:590:16: F821 undefined name 'unicode'
    beets/ui/__init__.py:590:28: F821 undefined name 'unicode'
    beets/ui/__init__.py:601:55: F821 undefined name 'unicode'
    beets/ui/__init__.py:669:27: F821 undefined name 'basestring'
    beets/ui/__init__.py:802:34: F821 undefined name 'unicode'
    beets/ui/__init__.py:855:35: F821 undefined name 'basestring'
    beets/ui/commands.py:166:29: F821 undefined name 'unicode'
    beets/ui/commands.py:239:24: F821 undefined name 'unicode'
    beets/ui/commands.py:241:20: F821 undefined name 'unicode'
    beets/util/__init__.py:68:36: F821 undefined name 'unicode'
    beets/util/__init__.py:70:38: F821 undefined name 'basestring'
    beets/util/__init__.py:75:36: F821 undefined name 'unicode'
    beets/util/__init__.py:344:27: F821 undefined name 'unicode'
    beets/util/__init__.py:348:16: F821 undefined name 'unicode'
    beets/util/__init__.py:367:29: F821 undefined name 'unicode'
    beets/util/__init__.py:632:28: F821 undefined name 'buffer'
    beets/util/__init__.py:637:16: F821 undefined name 'unicode'
    beets/util/__init__.py:763:24: F821 undefined name 'unicode'
    beets/util/__init__.py:799:35: F821 undefined name 'unicode'
    beets/util/__init__.py:800:22: F821 undefined name 'unicode'
    beets/util/confit.py:50:26: F821 undefined name 'unicode'
    beets/util/confit.py:51:30: F821 undefined name 'basestring'
    beets/util/confit.py:52:55: F821 undefined name 'long'
    beets/util/functemplate.py:81:26: F821 undefined name 'basestring'
    beets/util/functemplate.py:100:25: F821 undefined name 'basestring'
    beets/util/functemplate.py:193:34: F821 undefined name 'unicode'
    beets/util/functemplate.py:194:20: F821 undefined name 'unicode'
    beets/util/functemplate.py:245:33: F821 undefined name 'basestring'
    beets/util/functemplate.py:249:29: F821 undefined name 'unicode'
    beets/util/functemplate.py:259:33: F821 undefined name 'basestring'
    beets/util/functemplate.py:566:22: F821 undefined name 'unicode'
    beets/util/hidden.py:77:29: F821 undefined name 'unicode'
    beets/util/pipeline.py:434:35: E901 SyntaxError: invalid syntax
    beetsplug/badfiles.py:100:37: F821 undefined name 'unicode'
    beetsplug/bpm.py:34:13: F821 undefined name 'raw_input'
    beetsplug/chroma.py:184:59: F821 undefined name 'unicode'
    beetsplug/convert.py:57:47: F821 undefined name 'unicode'
    beetsplug/convert.py:76:52: F821 undefined name 'unicode'
    beetsplug/convert.py:80:43: F821 undefined name 'unicode'
    beetsplug/convert.py:83:56: F821 undefined name 'unicode'
    beetsplug/convert.py:387:53: F821 undefined name 'unicode'
    beetsplug/convert.py:420:41: F821 undefined name 'unicode'
    beetsplug/discogs.py:69:43: F821 undefined name 'unicode'
    beetsplug/discogs.py:70:49: F821 undefined name 'unicode'
    beetsplug/discogs.py:228:44: F821 undefined name 'unicode'
    beetsplug/duplicates.py:267:51: F821 undefined name 'unicode'
    beetsplug/edit.py:85:25: F821 undefined name 'unicode'
    beetsplug/edit.py:144:32: F821 undefined name 'unicode'
    beetsplug/fetchart.py:694:40: F821 undefined name 'unicode'
    beetsplug/fromfilename.py:135:26: F821 undefined name 'unicode'
    beetsplug/ftintitle.py:140:53: F821 undefined name 'unicode'
    beetsplug/fuzzy.py:47:44: F821 undefined name 'basestring'
    beetsplug/hook.py:82:44: F821 undefined name 'unicode'
    beetsplug/hook.py:83:48: F821 undefined name 'unicode'
    beetsplug/importfeeds.py:122:45: F821 undefined name 'unicode'
    beetsplug/inline.py:35:58: F821 undefined name 'unicode'
    beetsplug/inline.py:67:49: F821 undefined name 'unicode'
    beetsplug/inline.py:74:49: F821 undefined name 'unicode'
    beetsplug/keyfinder.py:55:59: F821 undefined name 'unicode'
    beetsplug/lastimport.py:113:41: F821 undefined name 'unicode'
    beetsplug/lastimport.py:195:16: F821 undefined name 'xrange'
    beetsplug/lyrics.py:78:16: F821 undefined name 'unichr'
    beetsplug/lyrics.py:180:26: F821 undefined name 'unicode'
    beetsplug/lyrics.py:253:53: F821 undefined name 'unicode'
    beetsplug/lyrics.py:464:53: F821 undefined name 'unicode'
    beetsplug/lyrics.py:465:57: F821 undefined name 'unicode'
    beetsplug/lyrics.py:506:20: F821 undefined name 'unicode'
    beetsplug/mbcollection.py:60:47: F821 undefined name 'unicode'
    beetsplug/mbcollection.py:61:47: F821 undefined name 'unicode'
    beetsplug/mpdstats.py:50:17: F821 undefined name 'unicode'
    beetsplug/mpdstats.py:65:47: F821 undefined name 'unicode'
    beetsplug/mpdstats.py:72:39: F821 undefined name 'unicode'
    beetsplug/mpdstats.py:84:47: F821 undefined name 'unicode'
    beetsplug/mpdupdate.py:89:39: F821 undefined name 'unicode'
    beetsplug/mpdupdate.py:91:43: F821 undefined name 'unicode'
    beetsplug/mpdupdate.py:104:31: F821 undefined name 'unicode'
    beetsplug/replaygain.py:225:54: E901 SyntaxError: invalid syntax
    beetsplug/rewrite.py:54:30: F821 undefined name 'unicode'
    beetsplug/smartplaylist.py:109:41: F821 undefined name 'basestring'
    beetsplug/spotify.py:174:27: F821 undefined name 'unicode'
    beetsplug/the.py:84:53: F821 undefined name 'unicode'
    beetsplug/thumbnails.py:173:37: F821 undefined name 'unicode'
    beetsplug/zero.py:116:29: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:308:27: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:309:27: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:310:27: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:311:29: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:312:35: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:313:26: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:326:31: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:327:33: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:471:31: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:472:29: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:572:30: F821 undefined name 'basestring'
    beetsplug/bpd/__init__.py:576:28: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:774:25: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:781:17: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:783:29: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:786:39: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:790:42: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:795:37: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:920:33: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:941:34: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:945:31: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:945:53: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:960:28: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:961:27: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:962:26: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:963:27: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:965:32: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:966:30: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:1062:44: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:1074:28: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:1075:31: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:1183:69: F821 undefined name 'unicode'
    beetsplug/bpd/__init__.py:1187:52: F821 undefined name 'unicode'
    beetsplug/bpd/gstplayer.py:113:29: F821 undefined name 'unicode'
    beetsplug/lastgenre/__init__.py:74:33: F821 undefined name 'unicode'
    beetsplug/lastgenre/__init__.py:189:45: F821 undefined name 'unicode'
    beetsplug/lastgenre/__init__.py:224:51: F821 undefined name 'unicode'
    beetsplug/lastgenre/__init__.py:300:59: F821 undefined name 'unicode'
    beetsplug/web/__init__.py:324:50: F821 undefined name 'unicode'
    test/helper.py:67:30: F821 undefined name 'unicode'
    test/helper.py:123:29: F821 undefined name 'unicode'
    test/test_config_command.py:117:23: F821 undefined name 'unicode'
    test/test_config_command.py:118:42: F821 undefined name 'unicode'
    test/test_dbcore.py:352:43: F821 undefined name 'unicode'
    test/test_lastgenre.py:41:41: F821 undefined name 'basestring'
    test/test_lastgenre.py:45:45: F821 undefined name 'basestring'
    test/test_library.py:966:46: F821 undefined name 'unicode'
    test/test_library.py:1053:26: F821 undefined name 'unicode'
    test/test_library.py:1176:68: F821 undefined name 'unicode'
    test/test_logging.py:221:38: E901 SyntaxError: invalid syntax
    test/test_lyrics.py:355:15: F821 undefined name 'unicode'
    test/test_mediafile.py:351:23: F821 undefined name 'unicode'
    test/test_mediafile.py:357:23: F821 undefined name 'unicode'
    test/test_mediafile_edge.py:127:18: F821 undefined name 'unicode'
    test/test_mediafile_edge.py:128:40: F821 undefined name 'unicode'
    test/test_mediafile_edge.py:348:39: F821 undefined name 'unicode'
    test/test_mediafile_edge.py:359:39: F821 undefined name 'unicode'
    test/test_query.py:302:38: F821 undefined name 'unicode'
    test/test_query.py:306:52: F821 undefined name 'unicode'
    test/test_query.py:307:50: F821 undefined name 'unicode'
    test/test_replaygain.py:65:31: E901 SyntaxError: invalid syntax
    test/test_template.py:33:29: F821 undefined name 'basestring'
    test/test_template.py:230:23: F821 undefined name 'unicode'
    test/test_template.py:261:41: F821 undefined name 'basestring'
    test/test_ui.py:740:61: E901 SyntaxError: invalid syntax
    test/test_ui_importer.py:72:30: F821 undefined name 'unicode'
    test/test_util.py:125:45: F821 undefined name 'unicode'
    test/test_util.py:134:45: F821 undefined name 'unicode'
    ERROR: InvocationError: '/Users/jack/Documents/Development/Personal/beets/.tox/py35flake8/bin/flake8 beets beetsplug beet test setup.py docs'
    _______________________________________ summary ________________________________________
    ERROR:   py35flake8: commands failed

So it looks like it's just checking the new Python 3 syntax and keywords more than anything, do you think it's worth keeping?

**Comment by jrobeson** [comment]
shouldn't we use py 3.3 instead of 3.5 here? 3.3 is likely to be our minimal version.

**Comment by jrobeson** [comment]
@sampsyo : i already had a similiar config locally in my python3-compat branch, but this one is better (since I didn't really get how to do what i wanted with tox)

**Comment by jrobeson** [comment]
@jackwilsdon : i think it's worth keeping due to min-version in setup.cfg. Maybe we can override it to min-version=3.3 in the tox.cfg . I'm not sure how the option inheritance works

**Comment by jrobeson** [comment]
@jackwilsdon : I've done some work on py3 locally, so it'd be cool if we could chat about that if you'd like to help.

**Comment by jackwilsdon** [comment]
I'm currently revamping the `tox.ini`, it seems there may be a better way to lay out our current one.

What do you guys think of moving our dependencies into their own files? We could put them in a directory named `requirements` or just leave them in the top level directory, it's up to you.

The main reason we'd do this is so we don't need to keep track of our dependencies in 2+ places (currently `tox.ini` and `setup.py` and maybe elsewhere too), as we can just read them in there instead. This also means someone can start development right away by just cloning beets and doing `pip -r requirements.txt`.

tox has full support for this by just adding `-rrequirements.txt` as a dependency and there is the function [`pip.req.parse_requirements`](http://stackoverflow.com/a/16624700/2664985) that allows us to use our `requirements.txt` files in the setup function.

**Comment by jackwilsdon** [comment]
Closing in favour of #2035.

**Pull request closed without merging**
