### PR TITLE
Fix bug #4815

### LINKED ISSUE #4815: Fetched lyrics from Genius are incomplete
### Problem

This is and example of the fetched lyrics

[Verse 1: Killer Mike]
Hear what I say, we are the business today
Fuck shit is finished today (What)
RT and J—we the new PB & J
We dropped a classic today (What)
We did a tablet of acid today
Lit joints with the matches and ashes away
SKRRRT! We dash away
Donner and Dixon, the pistol is blasting away```

[Verse 2: El-P]
Doctors of death
Curing our patients of breath
We are the pain you can trust
Crooked at work
Cookin' up curses and slurs
Smokin' my brain into mush
I became famous for flamin' you fucks
Maimin' my way through the brush
There is no training or taming of me and my bruh
Look like a man, but I'm animal raw

[Verse 3: Killer Mike]
We are the murderous pair
That went to jail and we murdered the murderers there
Then went to Hell and discovered the devil
Delivered some hurt and despair
Used to have powder to push
Now I smoke pounds of the kush
Holy, I'm burnin' a bush
Now I give a fuck about none of this shit
Jewel runner over and out of this bitch

While this is the link of the lyrics 
[https://genius.com/Run-the-jewels-legend-has-it-lyrics](https://genius.com/Run-the-jewels-legend-has-it-lyrics
)

### Setup

* OS: arch linux
* Python version: 3.11.3
* beets version: 1.6.1
* Turning off plugins made problem go away (yes/no):  no

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    force: yes
    sources: genius
    auto: yes
    bing_client_secret: REDACTED
    bing_lang_to:
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    fallback:
    local: no
    dist_thresh: 0.1
library: ~/.config/beets/library.db
directory: /data/media/audio

plugins: zero lyrics

import:
    copy: no
    from_scratch: yes
    incremental: yes
    log: /data/media/audio/beetlogs.txt
    move: no
    quiet: no
    quiet_fallback: skip
    resume: ask
    timid: no
    write: yes
zero:
    auto: yes
    update_database: yes
    fields: images
    keep_fields: []


```
Also there isnt nothing in the documentation in how to configure the genius_api_key parameter

### PR DESCRIPTION
**Pull request by HomerHaddock**
## Description

Fixes #4815.

I used the code from [this comment](https://github.com/beetbox/beets/issues/4815#issuecomment-1705752877), pasted it in then formatted it. I ran this across some songs I have and it grabs them perfectly.

## To Do

- [x] ~Documentation~
- [x] ~Changelog~
- [ ] Tests

### CODE REVIEW

**Comment by HomerHaddock** [comment]
Quickly changed changelog.

**Comment by Serene-Arc** [comment]
Hi! Thanks for the PR. Are you able to write some tests for this that fail before this patch and succeed after?

**Comment by HomerHaddock** [comment]
I cannot, I am new to making PRs and unfamiliar to making tests for Python. I would if I had the knowledge to.

**Comment by Serene-Arc** [comment]
Sure, that's not a problem. It just means that this PR will have to wait to be merged until a maintainer or another contributor can write a couple tests for it. This is simple enough, so I'll write some now.

**Pull request merged**
