### PR TITLE
Fix command formatting for hook plugin

### PR DESCRIPTION
**Pull request by jackwilsdon**
Hopefully this is a fix for #1979 as well as a fix for the bug mentioned below by @sampsyo.

### CODE REVIEW

**Comment by sampsyo** [comment]
Wow, this is a little crazy!

For the shlex trouble, at least, we do already have a utility function for working around that: https://github.com/beetbox/beets/blob/04bbdede3857dfcae5a2c8bd8b60f5ceb204f985/beets/util/__init__.py#L751

**Comment by sampsyo** [comment]
Hey, since we only use `kwargs` for this formatting, can we perhaps get away without needing to support `{}` (which only makes sense for positional arguments)?

**Comment by jackwilsdon** [comment]
Yeah, sure can 👍 I don't really know what I was thinking as positional arguments wouldn't work anyway 😆!

**Comment by sampsyo** [comment]
Great. I'd recommend a docstring for `CodingFormatter`, but beyond that, please merge when ready! ⛵

Looking at this code this time around also made me realize another potential pitfall, but I'll fiddle with that separately.

**Comment by jackwilsdon** [comment]
I have some free time if you want me to sort it 😄.

I'll write a docstring for this now.

**Comment by sampsyo** [comment]
Well OK, if you're up for it!

The problem is that the current code runs `shlex.split` after tempting. But what if a formatted field contains a space or a " character? It won't get treated as a single argument anymore.

The `convert` plugin has a solution to this: format each piece of the pre-split command string. Like this:

```py
# Substitute $source and $dest in the argument list.
args = shlex.split(command)
for i, arg in enumerate(args):
    args[i] = Template(arg).safe_substitute({
        b'source': source,
        b'dest': dest,
    })
```

That uses `Template` for argument substitution, but it should work more or less the same way with `Formatter`.

**Comment by jackwilsdon** [comment]
> The problem is that the current code runs `shlex.split` after tempting. But what if a formatted field contains a space or a " character? It won't get treated as a single argument anymore.

What do you mean by "tempting"? Are you saying we should `shlex.split` the unformatted command, individually format each piece and then execute them?

**Comment by jackwilsdon** [comment]
> The problem is that the current code runs `shlex.split` after tempting. But what if a formatted field contains a space or a " character? It won't get treated as a single argument anymore.

What do you mean by "tempting"? Are you saying we should `shlex.split` the unformatted command, individually format each piece and then execute the command?

**Comment by sampsyo** [comment]
Oops! Sorry; I meant "templating." (Mac autocorrect got me.) But that's exactly it; yes!

**Comment by jackwilsdon** [comment]
Aha, that makes sense. I'll expand the scope of this PR and fix it 😁. Thanks!

**Comment by jackwilsdon** [comment]
Do you think this is good for merging then, @sampsyo?

**Comment by sampsyo** [comment]
Yes; this looks perfect! Thank you! :sparkles:

**Pull request merged**
