### PR TITLE
Tentative fix for issue 2734: also check for RETAG

### PR DESCRIPTION
**Pull request by Vrihub**
This is a tentative fix for issue #2734 , based on the suggestion in https://github.com/beetbox/beets/issues/2734#issuecomment-341888432

I've tested it and it fixes the problem for me, but I'm not sure if other changes are required for a complete solution, since my knowledge of the code base is very limited. Please review!

### CODE REVIEW

**Comment by wordofglass** [comment]
Yep, that's exactly the code I meant to suggest.

`grep -r RETAG` shows that the `edit` plugin is the only piece of code using this choice and the following comment from `ìmporter.py` also suggests that the difference between `APPLY` and `RETAG` is really only the source of the metadata. Apart from that they both occur for the same kinds of import tasks and the same plugin actions should probably happen.

```python
action = Enum('action',
              ['SKIP', 'ASIS', 'TRACKS', 'APPLY', 'ALBUMS', 'RETAG'])
# The RETAG action represents "don't apply any match, but do record
# new metadata". It's not reachable via the standard command prompt but
# can be used by plugins.
```

Note that I'm not intimately familiar with the importer, either.

**Comment by sampsyo** [comment]
This looks great; thank you!

It looks like Travis has pointed out a too-long line: https://travis-ci.org/beetbox/beets/jobs/297512858#L1095

Also, would you mind adding a changelog entry that summarizes the problem that was fixed?

**Comment by Vrihub** [comment]
Uhm, no idea why AppVeyor fails here: https://ci.appveyor.com/project/beetbox/beets/build/2228

Also, no idea why all my commits here appear as by user "test" WTF?

**Comment by sampsyo** [comment]
Thank you! :sparkles: I'm pretty sure that AppVeyor failure is spurious, so I'll merge this now. Woohoo!

**Pull request merged**
