### PR TITLE
Add extra replaygain fields from loudgain

### PR DESCRIPTION
**Pull request by Moonbase59**
As [discussed in forum](https://discourse.beets.io/t/better-replaygain-2-loudgain-support/947), here are the new MediaFile fields to make magic happen in beets.

### CODE REVIEW

**Comment by jtpavlock** [comment]
I'm confused, is `loudgain` supported by beets, or is this PR attempting to preemptively add fields for an unsupported backend component?

**Comment by sampsyo** [comment]
Indeed; as I mentioned recently in #3368, I've sort of lost the context here.

**Comment by jtpavlock** [comment]
In that case I'm closing this for now. I think it would also make sense to couple this change with the actual implementation of `loudgain`

**Comment by jtpavlock** [comment]
Looks like https://github.com/beetbox/mediafile/pull/19 is relevant, which provides the implementation of these fields, but still doesn't make sense unless we actually switch or add `loudgain` as a replay gain backend.

**Pull request closed without merging**
