### PR TITLE
Add pip caching for travis

### PR DESCRIPTION
**Pull request by jrobeson**
Documented here: https://docs.travis-ci.com/user/caching/

### CODE REVIEW

**Comment by jackwilsdon** [comment]
We're using `tox` for our builds, which has it's own virtualenv inside `.tox`. Maybe we should cache that using [Arbitrary Directories](https://docs.travis-ci.com/user/caching/#Arbitrary-directories)?

**Comment by jrobeson** [comment]
aha.. you're right.  I'm not really all that familar with tox, so I didn't realize that

**Comment by jackwilsdon** [comment]
What do you think of caching `.tox`, @sampsyo? Is it safe to do?

According to the travis documentation, it is only cached per build type, so our `pypi`, `flake8`, `py27` and such will have separate `.tox` caches.

**Comment by sampsyo** [comment]
I'm not 100% sure—we'd need to do a little digging to find out if it's safe. In particular, it might be useful to search GitHub for other repositories that have the relevant lines in their `.travis.yml`. It seems like it's *probably* safe to do?

**Comment by jackwilsdon** [comment]
Here's some repositories I found:
 - [benoitc/gunicorn](https://github.com/benoitc/gunicorn) (2,988 stars): [`.travis.yml`](https://github.com/benoitc/gunicorn/blob/9d158bec94c91c62cd5cc28a27268a5b8804d795/.travis.yml)
 - [hylang/hy](https://github.com/hylang/hy) (1382 stars): [`.travis.yml`](https://github.com/hylang/hy/blob/a0251a25ed373e7acdd96aaf7fb4ee5970d9a82e/.travis.yml)
 - [rgalanakis/goless](https://github.com/rgalanakis/goless) (353 stars): [`.travis.yml`](https://github.com/rgalanakis/goless/blob/ce4931e6305e4b37a9942958a2e52588f8a61320/.travis.yml)
So I'd assume it's safe from these repositories?

**Comment by sampsyo** [comment]
Nice! Thanks for doing all that research. I'm convinced. :+1:

**Comment by jrobeson** [comment]
@jackwilsdon : so are you gonna submit the PR for that?

**Comment by jrobeson** [comment]
I went ahead and did it. @jackwilsdon : thanks for the research

**Pull request closed without merging**
