### PR TITLE
Use the six package to handle py2/p3 compatibility

### PR DESCRIPTION
**Pull request by jrobeson**
These results were mostly obtained via the modernize script.

Some of the fixes not currently applied are:

 * importing six.moves.{zip|range|map} everywhere we those functions
 * unconditional wrapping of map, filter, iter{values|items}, zip with lists
 * unconditional wrapping of beets internal keys,values methods with lists

### CODE REVIEW

**Comment by sampsyo** [comment]
Woohoo! This is not quite as onerous as I was expecting it to be -- this stuff is looking great.

I might comb through and continue backporting a few things that look like they might not even need six. For example, some of the places where we used `dict.iteritems()` in a `for` loop aren't really necessary -- `items` would work just as well and port cleanly.

As for the logstics, in case anyone else is reading: we plan on merging this for the next release after the impending bug-fix one. That release will, of course, incur a new dependency on `six`.

**Comment by jrobeson** [comment]
I rebased this on top of the `ur` fix just to see how the 3.x tests looked.

**Comment by jrobeson** [comment]
@sampsyo : can you either hold off on those iteritems changes until we merge six OR handle the rebase yourself?

**Comment by sampsyo** [comment]
Absolutely.

**Comment by jrobeson** [comment]
I think I've done all I can here.   I won't be rebasing it or anything like that until it's ready for merge.

**Comment by sampsyo** [comment]
Sounds great. Thanks for your patience.

**Comment by jrobeson** [comment]
you should take a look at this commit, see if you have any other ideas https://github.com/beetbox/beets/pull/2066/commits/b6678019ea31dcd25ef67d6017080bbe1ab4d3ea

**Pull request merged**
