### PR TITLE
First tentative fix for issue 2738.

### PR DESCRIPTION
**Pull request by Vrihub**
Don't ignore anymore filenames such as "01.mp3", instead use the number
in the filename as track number.

### CODE REVIEW

**Comment by samawsome** [comment]
#github

**Comment by sampsyo** [comment]
Hi! Sorry for the delay in reviewing this, but it looks perfect!

Would you mind adding a brief changelog entry about the new capability? Then this should be ready to merge as-is, if it's been working for you. :sparkles:

**Comment by Vrihub** [comment]
Ok, I've added a changelog entry (and fixed a conflict, since my branch was a bit old), did some more fixes to the regular expressions (see commit message 84cf336 ), fixed a line-too-long.
If you agree with the changes I think we should be ready to merge.

**Comment by sampsyo** [comment]
Perfect! Thank you for the updates, and for the clean fix for this shortcoming. :sparkles: Woohoo!

**Pull request merged**
