### PR TITLE
Add spotify as a fetchart source

### PR DESCRIPTION
**Pull request by arsaboo**
Added `spotify` as a fetchart source. 

Let me know if this approach looks fine. 

## To Do

- [x] Documentation. (If you've add a new command-line flag, for example, find the appropriate page under `docs/` to describe it.)
- [x] Changelog. (Add an entry to `docs/changelog.rst` near the top of the document.)
- [ ] Tests. (Encouraged but not strictly required.)

### CODE REVIEW

**Comment by wisp3rwind** [comment]
Looks reasonable at a first glance :tada: (Without checking anything Spotify-specific.) One small thing: We list `beautifulsoup` as an optional dependency, so we need to import in conditionally. See for example the `lyrics` plugin and the dependency specification in `setup.py`.

**Comment by wisp3rwind** [comment]
Looking good! Would you mind rebasing on (or merging) master in order to get https://github.com/beetbox/beets/pull/4772 for a proper CI run?

**Comment by arsaboo** [comment]
Thanks @wisp3rwind for that fix...all green now ✅

**Comment by wisp3rwind** [comment]
Great! I didn't check whether the Spotify "API" usage is correct, but since this is well-contained and otherwise the code looks good, I'm just going ahead and merge.

**Pull request merged**
