### PR TITLE
Abort quickly on user request

### PR DESCRIPTION
**Pull request by ssssam**
First attempt at fixing https://github.com/beetbox/beets/issues/3139

This branch greatly reduces the delay when I tell Beets to abort. It's not perfect, but it's survived my testing so far.

I haven't added any automated tests for this functionality. It's not immediately obvious how best to do that.

### CODE REVIEW

**Comment by sampsyo** [comment]
Thanks for quickly putting together a proposal! In spirit, something like this—setting and checking a synchronized "cancellation" flag to gently request that long-running stages finish up—might be one of the only ways to do this.

However, I am really sad about the amount of additional coupling and threading-through that this approach requires. One thing that makes me particularly sad, for example, is that `tag_album` and `tag_item` now have a `cancelable` parameter, which we will need to begin explaining as a value of a class that's defined somewhere else entirely—in the `pipeline` module. It would be really sad to couple this self-contained description of "work to do" with the library that orchestrates parallelism, which is a seemingly distinct concern.

I'll have to ponder this. This approach might be the only way, but it comes with unfortunate consequences. Some creativity will be required to come up with something that achieves the goals without the downsides—or else we'll need to convince ourselves that the additional complexity is essential and can't be avoided.

**Comment by ssssam** [comment]
I understand your concern and I'll be happy if you can come up with a better way to do it!

Note that the Cancellable object is independent of the 'pipeline' module. It happens to be defined there at the moment, but it could equally be in its own module. 

I suspect that we could achieve a much nicer solution using the Python [asyncio](https://docs.python.org/3/library/asyncio.html) module. That already [supports task cancellation](https://docs.python.org/3/library/asyncio-task.html#asyncio.Task.cancel) for example. I've not spent the time to fully learn how to use that module though, and it's also only available in Python 3.6 and later.

**Comment by sampsyo** [comment]
Here’s one crazy idea: turn certain interruptible things into coroutines. For example, the fingerprinter function could `yield` between each file. Then we could add support to the pipeline module for handling `yield`s that don’t produce anything—they’d just be a no-op, except that they give the pipeline module a chance to check for the shutdown flag.

Not sure that would be better or worse!

**Comment by ssssam** [comment]
> Here’s one crazy idea: turn certain interruptible things into coroutines. For example, the fingerprinter function could `yield` between each file. Then we could add support to the pipeline module for handling `yield`s that don’t produce anything—they’d just be a no-op, except that they give the pipeline module a chance to check for the shutdown flag.

I don't see how that could work for the 'chroma' plugin, because the slow task isn't triggered directly from the pipeline module but rather from `plugins.send()`. Currently the return value of that function is ignored almost everywhere, so if the chroma plugin returns a generator it'll never actually get executed.

**Comment by sampsyo** [comment]
Ah, yes, good point—I was thinking of the plugins that add entire import stages to the pipeline, but chroma does not do that.

**Comment by jtpavlock** [comment]
I believe [asyncio is also in 3.5](https://docs.python.org/3.5/library/asyncio.html), which will be the minimum supported python version started with beets v1.5.

**Comment by ssssam** [comment]
I'm not going to pursue this further at the moment. I'd love to see a solution, especially a clean one using asyncio :)

**Pull request closed without merging**
