### PR TITLE
Fix jumping time in beets.js

### PR DESCRIPTION
**Pull request by waweic**
Round was used instead of floor, so the minute counter jumped after each 30 seconds

### CODE REVIEW

**Comment by waweic** [comment]
You are welcome, of course. I have never contributed to a changelog before and don't really know how to write an entry. How would you formulate that?

**Comment by sampsyo** [comment]
Sure! Just add a bullet to the end of the current "Fixes" list at the top of `changelog.rst` saying, for example:

```rst
* :doc:`/plugins/web`: The time display in the web interface would incorrectly jump
  at the 30-second mark of every minute. Now, it correctly changes over at zero
  seconds. :bug:`2822`
```

**Comment by waweic** [comment]
Thanks! If you don't mind, I will just take this for the changelog entry.

**Comment by sampsyo** [comment]
Looks great; thank you! :sparkles:

**Pull request merged**
