### PR TITLE
More test improvements

### PR DESCRIPTION
**Pull request by JesseWeinstein**
No need to merge quite yet; I plan to add more. Just wanted to make the PR to get it out of the way.

### CODE REVIEW

**Comment by sampsyo** [comment]
So far so good!

**Comment by sampsyo** [comment]
This is looking good---happy to merge whenever.

**Comment by JesseWeinstein** [comment]
OK, I haven't worked on this for a couple days -- might as well merge it.

**Comment by sampsyo** [comment]
Awesome; thanks!

I'm also inviting you to be a collaborator. This would be a great kind of thing to push directly if you like (although PRs for code review are always welcome too).

**Pull request merged**
