### PR TITLE
fix bug with pathlib

### PR DESCRIPTION
**Pull request by eljojo**
Hi,

The `thumbnails` plugin was failing for me. The following patch fixed it.

```
$ python --version
Python 3.5.7
jojo at jojo-mini in ~/code/beets (master●)
$ beet thumbnails
Traceback (most recent call last):
  File "/Users/jojo/.asdf/installs/python/3.5.7/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.9', 'console_scripts', 'beet')()
  File "/Users/jojo/.asdf/installs/python/3.5.7/lib/python3.5/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/Users/jojo/.asdf/installs/python/3.5.7/lib/python3.5/site-packages/beets/ui/__init__.py", line 1253, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/Users/jojo/.asdf/installs/python/3.5.7/lib/python3.5/site-packages/beetsplug/thumbnails.py", line 78, in process_query
    self.process_album(album)
  File "/Users/jojo/.asdf/installs/python/3.5.7/lib/python3.5/site-packages/beetsplug/thumbnails.py", line 133, in process_album
    wrote &= self.make_cover_thumbnail(album, 128, NORMAL_DIR)
  File "/Users/jojo/.asdf/installs/python/3.5.7/lib/python3.5/site-packages/beetsplug/thumbnails.py", line 144, in make_cover_thumbnail
    target = os.path.join(target_dir, self.thumbnail_file_name(album.path))
  File "/Users/jojo/.asdf/installs/python/3.5.7/lib/python3.5/site-packages/beetsplug/thumbnails.py", line 165, in thumbnail_file_name
    uri = self.get_uri(path)
  File "/Users/jojo/.asdf/installs/python/3.5.7/lib/python3.5/site-packages/beetsplug/thumbnails.py", line 227, in uri
    return PurePosixPath(path).as_uri()
  File "/Users/jojo/.asdf/installs/python/3.5.7/lib/python3.5/pathlib.py", line 622, in __new__
    return cls._from_parts(args)
  File "/Users/jojo/.asdf/installs/python/3.5.7/lib/python3.5/pathlib.py", line 651, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/Users/jojo/.asdf/installs/python/3.5.7/lib/python3.5/pathlib.py", line 643, in _parse_args
    % type(a))
TypeError: argument should be a path or str object, not <class 'bytes'>
```

### CODE REVIEW

**Comment by sampsyo** [comment]
Thanks for finding this! Instead of hard-coding a string encoding, however, can you please use our [py3_path](https://github.com/beetbox/beets/blob/00ac5928c1a55e1ed07e0b4069f6fe02ac29f04a/beets/util/__init__.py#L694) utility, which represents paths (which beets always represents as bytes internally) as strings for APIs that demand them, as pathlib apparently does?

**Comment by eljojo** [comment]
very interesting! I just updated my PR, but haven't been able to test my changes.

**Comment by sampsyo** [comment]
Awesome; thanks! If you get a chance to try it out and it fixes the problem you were seeing, we can merge this.

**Comment by jtpavlock** [comment]
@eljojo any follow-up to this?

**Comment by eljojo** [comment]
@jtpavlock I don't really remember what ended up happening to this, I think the changes worked?
@sampsyo would either of you be interested in taking over?

**Comment by sampsyo** [comment]
It looks like the right thing to me—let's merge it with a changelog entry

**Pull request merged**
