### PR TITLE
Fix #1583: Only show modified files with 'beet move'

### LINKED ISSUE #1583: Only show files that are really moved when using the 'move' command
The `beet move` command is showing *ALL* files in my collection when using the `--pretend` flag, even if the path is the same before and after the `move` operation. Wouldn't it be better to show only the files that are actually moved?

### PR DESCRIPTION
**Pull request by fxthomas**

### CODE REVIEW

**Comment by sampsyo** [comment]
Thanks for getting this started! It looks like some tests are failing (maybe they need to be fixed?). Also, we should add to the documentation and write a changelog entry.

**Comment by fxthomas** [comment]
Added a quick changelog entry, but I'm unsure about where to add this in the docs.

Re: tests, I did not handle the case where the objects being moved were albums. Good thing there are tests, next time I'll run them before submitting the PR.

Also, there's a second thing that I did not take into account : if there is an existing file with the same name, beets adds e.g. `.1` to the file name for disambiguation, so these files will still be displayed every time.

**Comment by sampsyo** [comment]
> Added a quick changelog entry, but I'm unsure about where to add this in the docs.

The "command-line interface" page section for the "beet move" command should be fine—just briefly mention that the command only shows files that won't be in the same place as they were before.

> Re: tests, I did not handle the case where the objects being moved were albums. Good thing there are tests, next time I'll run them before submitting the PR.

Good point.

> Also, there's a second thing that I did not take into account : if there is an existing file with the same name, beets adds e.g. .1 to the file name for disambiguation, so these files will still be displayed every time.

Hmm, that's not ideal, but probably fine. We could work around it by applying that disambiguation too in the preview.> Added a quick changelog entry, but I'm unsure about where to add this in the docs.

The "command-line interface" page section for the "beet move" command should be fine—just briefly mention that the command only shows files that won't be in the same place as they were before.

> Re: tests, I did not handle the case where the objects being moved were albums. Good thing there are tests, next time I'll run them before submitting the PR.

Good point.

> Also, there's a second thing that I did not take into account : if there is an existing file with the same name, beets adds e.g. .1 to the file name for disambiguation, so these files will still be displayed every time.

Hmm, that's not ideal, but probably fine. We could work around it by applying that disambiguation too in the preview.

**Comment by fxthomas** [comment]
I've been busy with real life, but at last I'm able to work on this a little. I've rebased against `master` and made the necessary corrections. This time the test suite now passes, and I've checked against my own library that it indeed works. Happy new year! :)

**Comment by sampsyo** [comment]
Looks awesome! Merging now. (And no worries whatsoever about life intervening.)

**Pull request merged**
