### PR TITLE
chore: makes discussions more visible

### PR DESCRIPTION
**Pull request by jef**
## Description

I created a `config.yml` thats helps make [Discussions](https://github.com/beetbox/beets/discussions) more visible.

Example (from another repository):

image

Open links point to Discussions.

I have also removed feature request as it seems more fitting to have Discussions about a feature and then use the [Issues](https://github.com/beetbox/beets/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for valid tickets/things being worked on.

### CODE REVIEW

**Comment by sampsyo** [comment]
Cool; thanks for getting this going!

FWIW, I do think it's cool to have tickets for feature requests as well as bugs in the tracker… but I get your intent to put vague "ideas" on the discussion board. Maybe we should keep the template around but just clarify that it's for cases where you know pretty much what you want and are ready to write a coherent proposal, whereas discussions are for when you just want to chat about an idea?

**Comment by jef** [comment]
What do we think, should we add this in?

**Comment by sampsyo** [comment]
Oh yeah, sounds good to me! But maybe we should leave the Discourse link for now just to see how things go?

**Comment by jef** [comment]
> Oh yeah, sounds good to me! But maybe we should leave the Discourse link for now just to see how things go?

I agree!

**Comment by sampsyo** [comment]
Nice; looks pretty good to me! And I think the CI failures may be resolved my updating with master? In any case, I think it's about good to go.

**Comment by jef** [comment]
> And I think the CI failures may be resolved my updating with master

Not sure why, I can rerun if needed.

**Comment by sampsyo** [comment]
Odd… just to be sure, maybe we should try merging #3907 first and seeing if that helps clear things up on this PR?

**Comment by jef** [comment]
I also did a merge. I didn't realize that this was roughly _300 commits_ behind. Probably had something to do with it 😅

**Comment by sampsyo** [comment]
Ah, that'd do it! LGTM, except that it looks like maybe the feature request template file might have gotten accidentally deleted?

**Comment by jef** [comment]
Ah, good question. I removed it on purpose. Since the `config.yaml` will point folks to the Discussion board, they'll be able to discuss a feature in length. If we decide to pull it in, we can create put it on the board in a way we like.

This doesn't prohibit the user to define a feature request either way, but just leads them in the direction.

If you don't like this approach, I have no problem reverting.

**Comment by sampsyo** [comment]
Got it! I don't object, certainly. Here's a question, though: when a feature request eventually makes its way over from vague discussion to a concrete proposal, will we want to follow a template then? (One option might be to add an encouragement to do discussion ahead of time to the template itself.)

**Comment by jef** [comment]
Aha, makes sense to me. The feature issue could definitely lose it's structure overtime, so that's good idea! I'll update.

**Comment by sampsyo** [comment]
Nice. This all looks good to go from here!

**Pull request merged**
