### PR TITLE
Add some more docs to canonicalization with example

### PR DESCRIPTION
**Pull request by svenstaro**
It really didn't make sense to me before I did some further research. You shouldn't have to do further research to understand this apart form reading the docs.

### CODE REVIEW

**Comment by sampsyo** [comment]
Cool! Thank you for expanding this.

It seems like a short example YAML snippet would be helpful here. Maybe you can illustrate the parent/child relationship you're talking about with a short listing?

Also, @Kraymer, can you weigh in about the accuracy here as the patron saint of genre canonicalization?

**Comment by svenstaro** [comment]
Well, there you go.

**Comment by Kraymer** [comment]
LGTM, good addition to the doc
Le 6 févr. 2016 8:46 AM, "Sven-Hendrik Haase" <notifications@github.com> a
écrit :

**Comment by sampsyo** [comment]
Done!

**Pull request merged**
