### PR TITLE
Fix bugs in beatport plugin

### PR DESCRIPTION
**Pull request by jbaiter**
As mentioned in the last PR, I had not tested the integration with beets.
Turns out there were two bugs lurking, one due to a naming confusion and another due to incompatibility with the API of the previous plugin version.
Both are fixed and according to my superficial test the plugin should now work as expected.

### CODE REVIEW

**Comment by sampsyo** [comment]
Looks great; thanks for the fast response! I invited you to the @beetbox org, so please feel to merge this after the CI results come in.

**Comment by brianroach** [comment]
@jbaiter I tried running it with your new commit & got the following error. Should I re-authorize somehow?
```
Warning: configuration uses "list_format_item" which is deprecated in favor of "format_item" now that it affects all commands. See changelog & documentation.
Warning: configuration uses "list_format_album" which is deprecated in favor of "format_album" now that it affects all commands. See changelog & documentation.
> /Users/anodigital/github/beets/beetsplug/beatport.py(270)setup()
-> c_key = self.config['apikey'].get(unicode)
(Pdb)
```

**Comment by jbaiter** [comment]
Gah, sorry, that was a remnant from my debugging session that I forgot to remove :flushed:

**Comment by brianroach** [comment]
@jbaiter even with that line removed I am still getting an error: 

```
briansmac:~ anodigital$ beet import '/Volumes/BRIAN ROACH/Music/320 Pool/Tunes'

/Volumes/BRIAN ROACH/Music/320 Pool/Tunes (746 items)
No matching release found for 746 tracks.
For help, see: http://beets.readthedocs.org/en/latest/faq.html#nomatch
[U]se as-is, as Tracks, Group albums, Skip, Enter search, enter Id, aBort? T
Traceback (most recent call last):
  File "/Users/anodigital/.pyenv/versions/2.7.10/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.18', 'console_scripts', 'beet')()
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/ui/__init__.py", line 1250, in main
    _raw_main(args)
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/ui/__init__.py", line 1240, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/ui/commands.py", line 967, in import_func
    import_files(lib, paths, query)
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/ui/commands.py", line 944, in import_files
    session.run()
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/importer.py", line 320, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/util/pipeline.py", line 304, in run
    for msg in _allmsgs(out):
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/util/pipeline.py", line 455, in pull
    out = coro.send(msg)
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/util/pipeline.py", line 183, in coro
    func(*(args + (task,)))
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/importer.py", line 1264, in lookup_candidates
    task.lookup_candidates()
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/importer.py", line 834, in lookup_candidates
    self.item, search_ids=self.search_ids)
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/autotag/match.py", line 493, in tag_item
    for track_info in hooks.item_candidates(item, search_artist, search_title):
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/autotag/hooks.py", line 606, in item_candidates
    out.extend(plugins.item_candidates(item, artist, title))
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/plugins.py", line 364, in item_candidates
    out.extend(plugin.item_candidates(item, artist, title))
  File "/Users/anodigital/github/beets/beetsplug/beatport.py", line 355, in item_candidates
    return self._get_tracks(query)
  File "/Users/anodigital/github/beets/beetsplug/beatport.py", line 454, in _get_tracks
    bp_tracks = self.client.search(query, release_type='track').results
AttributeError: 'generator' object has no attribute 'results'
briansmac:~ anodigital$```

**Comment by brianroach** [comment]
@jbaiter just out of curiosity, could you post one of your queries and the results of that query? I have folders of EPs labeled ```%Artist% - %Album Title%``` and am trying to run ```beet import '/Users/anodigital/Downloads/Claude VonStroke - Who's Afraid of Detroit - 10th Anniversary Remixes'``` but my terminal just hangs forever and doesn't return any results...
2016-06-22 at 1 30 pm

**Comment by jbaiter** [comment]
Hm, I can't reproduce your problem. I tried importing some of my albums (renamed some of them to match your scheme) and it works for me. Also searching for your artist and album returns results from Beatport for me. Can you run with `--verbose` and see if the output can shed some more light on the issue?

**Comment by brianroach** [comment]
Hmmm, so I tried that, but still no luck. What's also weird is when I entered the URL for the release it still didn't work:
```
briansmac:beets anodigital$ beet import ~/Downloads/tsting

/Users/anodigital/Downloads/tsting/Claude VonStroke - Who's Afraid of Detroit (Remixes) (5 items)
No matching release found for 5 tracks.
For help, see: http://beets.readthedocs.org/en/latest/faq.html#nomatch
[U]se as-is, as Tracks, Group albums, Skip, Enter search, enter Id, aBort? g

/Users/anodigital/Downloads/tsting/Claude VonStroke - Who's Afraid of Detroit (Remixes)/Claude VonStroke - Who's Afraid of Detroit (10 Year Anniversary Mix).aif
/Users/anodigital/Downloads/tsting/Claude VonStroke - Who's Afraid of Detroit (Remixes)/Claude VonStroke - Who's Afraid of Detroit (Marc Houle Remix).aif
/Users/anodigital/Downloads/tsting/Claude VonStroke - Who's Afraid of Detroit (Remixes)/Claude VonStroke - Who's Afraid of Detroit (Octave One Remix).aif
/Users/anodigital/Downloads/tsting/Claude VonStroke - Who's Afraid of Detroit (Remixes)/Claude VonStroke - Who's Afraid Of Detroit (Original Mix).aif
/Users/anodigital/Downloads/tsting/Claude VonStroke - Who's Afraid of Detroit (Remixes)/Claude VonStroke - Who's Afraid of Detroit (Visionquest Remix).aif (5 items)
No matching release found for 5 tracks.
For help, see: http://beets.readthedocs.org/en/latest/faq.html#nomatch
[U]se as-is, as Tracks, Group albums, Skip, Enter search, enter Id, aBort? i
Enter release ID: https://www.beatport.com/release/whos-afraid-of-detroit-10th-anniversary-remixes/1773570
Traceback (most recent call last):
  File "/Users/anodigital/.pyenv/versions/2.7.10/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.18', 'console_scripts', 'beet')()
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/ui/__init__.py", line 1250, in main
    _raw_main(args)
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/ui/__init__.py", line 1240, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/ui/commands.py", line 967, in import_func
    import_files(lib, paths, query)
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/ui/commands.py", line 944, in import_files
    session.run()
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/importer.py", line 320, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/util/pipeline.py", line 304, in run
    for msg in _allmsgs(out):
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/util/pipeline.py", line 455, in pull
    out = coro.send(msg)
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/util/pipeline.py", line 160, in coro
    task = func(*(args + (task,)))
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/importer.py", line 1285, in user_query
    task.choose_match(session)
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/importer.py", line 779, in choose_match
    choice = session.choose_match(self)
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/ui/commands.py", line 755, in choose_match
    task.items, search_ids=search_id.split()
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/autotag/match.py", line 407, in tag_album
    search_cands.extend(hooks.albums_for_id(search_id))
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/autotag/hooks.py", line 541, in albums_for_id
    plugin_albums = plugins.album_for_id(album_id)
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/plugins.py", line 373, in album_for_id
    res = plugin.album_for_id(album_id)
  File "/Users/anodigital/github/beets/beetsplug/beatport.py", line 368, in album_for_id
    release = self.client.get_release(match.group(2))
  File "/Users/anodigital/github/beets/beetsplug/beatport.py", line 150, in get_release
    response = self._get('/catalog/3/releases', id=beatport_id)
  File "/Users/anodigital/github/beets/beetsplug/beatport.py", line 195, in _get
    .format(response))
beetsplug.beatport.BeatportAPIError: Error 401 for '/catalog/3/releases?id=1773570
```

**Comment by brianroach** [comment]
@jbaiter this is weird. 
```
briansmac:beets anodigital$ !! --verbose
beet import ~/Downloads/tsting --verbose
Usage: beet import [options]

beet import: error: no such option: --verbose
```

How can I remove everything and re-authorize with beatport? I tried just deleting the beets folder, but that didn't prompt me to re-authorize again or anything. Also, I've gotten this a few times:

```briansmac:beets anodigital$ beet import ~/Downloads/tsting
error: communication with Beatport failed```

**Comment by sampsyo** [comment]
FWIW about the above: the verbose flag is a global option, so it has to go `beet --verbose import` as opposed to `beet import --verbose`.

**Comment by brianroach** [comment]
@sampsyo ahh, gotcha. Thanks for the tip. Newbie here so thanks for baring with me. 👊

**Pull request merged**
