### PR TITLE
Limit search query length to 100 characters - Fixes #5105

### LINKED ISSUE #5105: Spotify 400 totally stops import
```
Error: MusicBrainz not reachable in recording search with query {'artist': 'willie nelson, jimmy buffett, emmylou harris, sheryl crow, eric church, george strait, dave matthews, chris stapleton, derek trucks, kris kristofferson, the avett brothers, bobby bare, jack johnson, jamey johnson, lee ann womack, lukas nelson, lyle lovett, margo price, micah nelson, nathaniel rateliff, norah jones, the little willies, ray benson, steve earle, susan tedeschi, vince gill', 'recording': 'roll me up and smoke me when i die - live'}
error: Spotify API error:
{
  "error" : {
    "status" : 400,
    "message" : "Bad request."
  }
}
```
It seems like this is caused due to a really long artist list. Every time I import interactive or not this happens

### PR DESCRIPTION
**Pull request by Explosion-Scratch**
## Description

Fixes #5105 

(...)

## To Do

- [ ] Documentation. (If you've added a new command-line flag, for example, find the appropriate page under `docs/` to describe it.)
- [ ] Changelog. (Add an entry to `docs/changelog.rst` to the bottom of one of the lists near the top of the document.)
- [ ] Tests. (Very much encouraged but not strictly required.)

### CODE REVIEW

**Comment by Explosion-Scratch** [comment]
Why is formatting check failing? I didn't change anything to at least 13 of the 14 files it fails on

**Comment by arsaboo** [comment]
Here's another PR (https://github.com/beetbox/beets/pull/4901) that fixes this issue.

**Comment by Explosion-Scratch** [comment]
> Here's another PR #4901 that fixes this issue.

Yours would still crash if 2 artists names' were longer than 25 characters

**Comment by arsaboo** [comment]
The limit is 100? where did you get 25 characters from?

**Comment by Explosion-Scratch** [comment]
> Where did you get 25 characters from? Instead of randomly truncating at 100 characters, searching for two artists is a better idea. Can you try that PR and see if it fixes the issue for you?

25 + 25 = 50 (not sure why you went for 50):

https://github.com/beetbox/beets/blob/a197d4cae5603522e221a6d8ee08bb970164b838/beetsplug/spotify.py#L556

This PR would fix the issue most of the time but there could be cases when this error still occurs. If you added a trunctuate to 100 characters in addition to your PR it would be good I think

**Comment by Serene-Arc** [comment]
> Why is formatting check failing? I didn't change anything to at least 13 of the 14 files it fails on

Black updated their formatter and it changed some lines. The issue has been resolved and didn't just affect your PR. I have pinned the versions in our CI pipeline so it doesn't happen again.

**Comment by Serene-Arc** [comment]
I prefer @arsaboo's solution to this. Truncating the search randomly has a greater chance of making a meaningless/nonsensical search and thus wrong or no results. Better to properly get at least some of the artists. However some work needs to be done on that PR as well. If you'd like to move to #4901 we can continue discussion.

**Pull request closed without merging**
