### PR TITLE
Add pydocstyle checking

### PR DESCRIPTION
**Pull request by jackwilsdon**
Sadly we have to add a new tox environment and test to the travis matrix for this, as we can't easily integrate this with flake8.

As we currently stand (using the default configuration), there are a large number of errors output by [`pydocstyle`](https://github.com/PyCQA/pydocstyle), although I'm sure we can fine tune it to suit our needs.

### CODE REVIEW

**Comment by sampsyo** [comment]
Very cool! This will be fun to play with. Here are a few initial reactions:

- PEP 257 definitely does recommend blank lines after docstrings in classes, but I've for some reason never been in the habit. I suppose it's probably worth standardizing that.
- I'm a little confused by `First line should end with a period`. Does this really mean that the first sentence in every docstring is limited to 72 characters or whatever?
- I definitely like the idea of encouraging docstrings on every function, but sometimes I worry that requiring it will put too much friction on potential contributors. I'm not sure which way to go on this—it's a difficult balance between productivity and long-term documentation health.
- It's pretty cool that it can check English grammar (i.e., docstrings in imperative mood).

Anyway, unlike with the naming checker, there are probably too many violations here to be fixed in one go. But this will be a good goal to work toward long-term—perhaps we can consider merging this but telling Travis to ignore failures for now?

**Comment by jackwilsdon** [comment]
> I'm a little confused by `First line should end with a period`. Does this really mean that the first sentence in every docstring is limited to 72 characters or whatever?

It certainly looks like the summary line of docstrings is limited to 72 characters. We may have to disable the check or open an issue on [pydocstyle], as [PEP 257] itself is rather vague with it's line length and wrapping.

> Anyway, unlike with the naming checker, there are probably too many violations here to be fixed in one go. But this will be a good goal to work toward long-term—perhaps we can consider merging this but telling Travis to ignore failures for now?

This certainly sounds like the best course of action for the time being. This would also help with your third point, as it would mean contributors (at least for now) would not need to write the docstrings.

I'll tell Travis to ignore the failure for now 😄.

[pydocstyle]: https://github.com/PyCQA/pydocstyle
[PEP 257]: https://www.python.org/dev/peps/pep-0257/

**Comment by jtpavlock** [comment]
I like the idea, and wish it were implemented as I find myself struggling to understand the codebase sometimes 😄 

Not sure if there is still an interest in implementing this, but it may be worthwhile to consider the flake8 plugin for pydocstyle, [flake8-docstring](https://pypi.org/project/flake8-docstrings/).

As far as current code errors, we could generate docstrings for existing code via a tool such as [pyment](https://github.com/dadadel/pyment). 

If it's an ultimate goal for `beets` to also act a library i.e. `import beets`, then [code documentation with Sphinx](https://pythonhosted.org/an_example_pypi_project/sphinx.html) could also be useful given a standard such as[ Google docstring format](https://google.github.io/styleguide/pyguide.html#381-docstrings) exists. Again, this type of docstring could be  generated with pyment for existing code, and then enforced via the flake8 plugin.

As far as discouraging potential contributors, you could always advise them to run pyment on their code which would do the bare minimum docstring for them.

**Comment by jtpavlock** [comment]
@sampsyo If you're cool with what I suggested, and @jackwilsdon doesn't mind, I can open a PR for the implementation/conversion work.

**Comment by sampsyo** [comment]
Yes, this seems cool! I would love to stop manually correcting `'''` docstrings and such. :smiley:

The one thing I'm less enthusiastic about is automatically generating docstrings. pyment looks cool for reformatting especially, but I don't really see the value in _fully_ automatic docstring generation… it can only echo things we already know about a function/class from its signature!

I do not have a strong preference between Google and Numpy styles, although it looks like Google may be slightly closer to the *de facto* style that currently exists in the codebase?

FWIW, we actually do have some Sphinx-generated API docs already:
https://beets.readthedocs.io/en/stable/dev/api.html

**Comment by jtpavlock** [comment]
I think `pyment` should be used to convert the existing codebase's docstrings, and then, if wanted by the user, to provide a template for them to fill in the actual documentation we care about. I didn't mean for it to be OK for a new user to just run `pyment` and call it good as you're right, that would just cloud the codebase in non-useful info.

I'm fine with Google! And if it's the current de facto, then that means we hopefully won't upset too many people that have contributed 😄

**Pull request closed without merging**
