### PR TITLE
remove import of unicode_literals

### PR DESCRIPTION
**Pull request by pkess**
Hi,
as mentioned in #1484 i started a new branch to remove the import of unicode_literals.
With the remove of this import we should explicit mark some strings in the code as unicode strings. In my opinion all output strings and strings compared against some input should be marked as unicode strings.
Please leave your comments!

### CODE REVIEW

**Comment by untitaker** [comment]
You need to be careful with converting too eagerly to unicode strings: Python 2's support for equality comparisons is garbage and doesn't work if you're dealing with non-ascii data.

Really you need to deal with three types: `u""`, `b""`, `""`.

Ideally we'd do all of the following in one huge step:

* Port to click
* Remove unicode literals imports
* **Drop Python 2**

**Comment by sampsyo** [comment]
Awesome! Thanks for taking the first step.

Yes, the majority of string literals should be `u` literals. A few rules of thumb come to mind:

* `log.debug/warn/info/etc('foo' ...`: Always `u`.
* Pieces of filenames: Always `b`, unless it's in some parts of the `destination` method before the path is encoded.
* URLs and data for HTTP requests: Probably unannotated ("native") string literals.
* Arguments to exceptions: Almost always `u`.
* `print_` and such: Always `u`.

We should also consider running [unicode-nazi](https://github.com/mitsuhiko/unicode-nazi) occasionally to catch some bad comparisons.

**Comment by pkess** [comment]
What will we do with SQL statements?

**Comment by sampsyo** [comment]
Good question. After a little googling, I think the answer is native/unannotated strings.

**Comment by pkess** [comment]
Ok,
there is only one file left with import of unicode_literals: test/test_iu
I started to remove it in https://github.com/pkess/beets/tree/no_unicode_literals_test_ui
There are two errors i can't explain or debug. Could anyone help here?

**Comment by pkess** [comment]
Please review the above commits and feel free to leave comments

**Comment by untitaker** [comment]
@pkess I opened a PR. I still get one failure, but I haven't looked into it yet.

**Comment by pkess** [comment]
Hi, thank you for your support. I don't get any failures by running tox on my local machine. I will merge the here to see if travis reports any failures

**Comment by sampsyo** [comment]
AWESOME! :sparkles: This was a truly huge amount of work. You even got the coveted "diff too large to display" message on GitHub. :fish:

I've scanned over the entire diff and changed a few tiny style things. I also synced with the master branch so this PR can merge cleanly. Everything looks great. Unless there's anything else outstanding, I move to merge this now.

**Comment by pkess** [comment]
Ok, would you like to hit the merge button?

**Comment by pkess** [comment]
I just added a wiki page with the conventions for strings discussed here:
https://github.com/beetbox/beets/wiki/String-literals
I hope you agree with this

**Comment by sampsyo** [comment]
Woohoo! :sparkles:

And yes, that wiki page looks great.

**Pull request merged**
